In [1]:
!gcloud auth application-default login

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=YMSC2dBCwERLXKUj1cNcmUA7mlOiIT&access_type=offline&code_challenge=9pcSgUX5aikxx5jTyf9TG0OHXsZo8npDaJhZ9h2bI-I&code_challenge_method=S256


Credentials saved to file: [/Users/yt4/.config/gcloud/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).

Quota project "open-targets-genetics-dev" was added to ADC which can be used by Google client libraries for billing and quota. Note that some services may still bill the project owning the resource.


Updates are available for some Google Cloud CLI components.  To install them,
please run:
  $ gcloud components update



To take a quick anonymous survey, run:
  $ gcloud survey

In [1]:
import os

import hail as hl
import numpy as np
import pyspark.sql.functions as f
from pyspark.sql import DataFrame

from gentropy.common.session import Session
from gentropy.dataset.study_index import StudyIndex
from gentropy.dataset.summary_statistics import SummaryStatistics
from gentropy.dataset.study_locus import StudyLocus
from gentropy.susie_finemapper import SusieFineMapperStep
from gentropy.method.drug_enrichment_from_evid import chemblDrugEnrichment

"""Common utilities for the project."""

import os
from pathlib import Path
from gentropy.common.session import Session
import logging


def get_gcs_credentials() -> str:
    """Get the credentials for google cloud storage."""
    app_default_credentials = os.path.join(
        os.getenv("HOME", "."), ".config/gcloud/application_default_credentials.json"
    )

    service_account_credentials = os.path.join(
        os.getenv("HOME", "."), ".config/gcloud/service_account_credentials.json"
    )

    if Path(app_default_credentials).exists():
        return app_default_credentials
    else:
        raise FileNotFoundError("No GCS credentials found.")


def get_gcs_hadoop_connector_jar() -> str:
    """Get the google cloud storage hadoop connector for spark.

    This function will return the url to download the hadoop jar.
    """

    return (
        "https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop3-latest.jar"
    )


def gcs_conf(
    credentials_path=None, project="open-targets-genetics-dev"
) -> dict[str, str]:
    """Get the spark configuration with hadoop connector for google cloud storage."""
    credentials_path = credentials_path or get_gcs_credentials()
    return {
        "spark.driver.memory": "12g",
        "spark.kryoserializer.buffer.max": "500m",
        "spark.driver.maxResultSize":"2g",
        "spark.hadoop.fs.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem",
        "spark.jars": get_gcs_hadoop_connector_jar(),
        "spark.hadoop.google.cloud.auth.service.account.enable": "true",
        "spark.hadoop.fs.gs.project.id": project,
        "spark.hadoop.google.cloud.auth.service.account.json.keyfile": credentials_path,
        "spark.hadoop.fs.gs.requester.pays.mode": "AUTO",
    }


class GentropySession(Session):
    def __init__(self, *args, **kwargs):
        if "extended_spark_conf" in kwargs:
            kwargs["extended_spark_conf"].update(gcs_conf())
        else:
            kwargs["extended_spark_conf"] = gcs_conf()
        super().__init__(*args, **kwargs)

    @property
    def conf(self):
        logging.warning(
            "To change the config restart the session and use the `extended_spark_conf` parameter."
        )
        return self.spark.sparkContext.getConf().getAll()

session= GentropySession()

/Users/yt4/Projects/gentropy/.venv/lib/python3.11/site-packages/pyspark/sql/pandas/functions.py:407: UserWarning:

In Python 3.6+ and Spark 3.0+, it is preferred to specify type hints for pandas UDF instead of specifying pandas UDF type which will be deprecated in the future releases. See SPARK-28264 for more details.

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/11/06 21:16:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [2]:
path_to_release_folder="gs://open-targets-data-releases/25.06/"


si=StudyIndex.from_parquet(session,path_to_release_folder+"output/study/")
sl=StudyLocus.from_parquet(session,path_to_release_folder+"output/credible_set/")

sl_eff=session.spark.read.parquet("gs://genetics-portal-dev-analysis/ss60/gentropy-manuscript/chapters/variant-effect-prediction/25.07/lead_variant_effect")

l2g_full=session.spark.read.parquet("gs://genetics-portal-dev-analysis/yt4/20250403_for_gentropy_paper/list_of_prioritised_genes_per_CS.parquet")

In [3]:
variant_pleiotropy = session.spark.read.parquet('gs://genetics-portal-dev-analysis/dc16/output/gentropy_paper/variant_pleiotropy')

In [6]:
variant_pleiotropy.count()

40706

In [7]:
variant_pleiotropy.printSchema()

root
 |-- variantId: string (nullable = true)
 |-- nonEURProportion: double (nullable = true)
 |-- minAbsBeta: double (nullable = true)
 |-- maxAbsBeta: double (nullable = true)
 |-- minCoefficientDetermination: double (nullable = true)
 |-- maxCoefficientDetermination: double (nullable = true)
 |-- minEffectiveSampleSize: double (nullable = true)
 |-- maxEffectiveSampleSize: double (nullable = true)
 |-- minVarG: double (nullable = true)
 |-- maxVarG: double (nullable = true)
 |-- maxMAF: double (nullable = true)
 |-- averageBetaSign: double (nullable = true)
 |-- stdBetaSign: double (nullable = true)
 |-- betaSignConcordance: double (nullable = true)
 |-- earliestPublicationDate: string (nullable = true)
 |-- uniqueDiseases: integer (nullable = true)
 |-- uniqueTherapeuticAreas: integer (nullable = true)
 |-- cancerOrBenignTumor: long (nullable = true)
 |-- infectiousDisease: long (nullable = true)
 |-- pregnancyOrPerinatalDisease: long (nullable = true)
 |-- disorderOfVisualSystem: long (nullable = true)
 |-- cardiovascularDisease: long (nullable = true)
 |-- pancreasDisease: long (nullable = true)
 |-- gastrointestinalDisease: long (nullable = true)
 |-- reproductiveSystemOrBreastDisease: long (nullable = true)
 |-- integumentarySystemDisease: long (nullable = true)
 |-- endocrineSystemDisease: long (nullable = true)
 |-- respiratoryOrThoracicDisease: long (nullable = true)
 |-- urinarySystemDisease: long (nullable = true)
 |-- musculoskeletalOrConnectiveTissueDisease: long (nullable = true)
 |-- disorderOfEar: long (nullable = true)
 |-- immuneSystemDisease: long (nullable = true)
 |-- hematologicDisease: long (nullable = true)
 |-- nervousSystemDisease: long (nullable = true)
 |-- psychiatricDisorder: long (nullable = true)
 |-- nutritionalOrMetabolicDisease: long (nullable = true)
 |-- geneticFamilialOrCongenitalDisease: long (nullable = true)
 |-- injuryPoisoningOrOtherComplication: long (nullable = true)
 |-- signOrSymptom: long (nullable = true)
 |-- other: long (nullable = true)
 |-- uniqueDiseaseNames: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- uniqueTherapeuticAreaNames: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- prioritisedGenes: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- totalStudies: long (nullable = true)
 |-- gerpNormalised: double (nullable = true)
 |-- vepScore: float (nullable = true)

In [4]:
variant_pleiotropy.filter(f.col("uniqueDiseases")>=10).count()

197

In [9]:
variant_pleiotropy.filter(f.col("uniqueTherapeuticAreas")>1).count()

5900

In [12]:
# collect to pandas if it fits in driver memory
pdf = (
    variant_pleiotropy
    .select("uniqueTherapeuticAreas", "uniqueDiseases")
    .na.drop()
    .toPandas()
)
pdf["uniqueTherapeuticAreas"] = pdf["uniqueTherapeuticAreas"].astype(float)
pdf["uniqueDiseases"] = pdf["uniqueDiseases"].astype(float)

from scipy.stats import pearsonr, spearmanr
pearson_r, pearson_p = pearsonr(pdf["uniqueTherapeuticAreas"], pdf["uniqueDiseases"])
spearman_r, spearman_p = spearmanr(pdf["uniqueTherapeuticAreas"], pdf["uniqueDiseases"])

print("Pearson r, p-value:", pearson_r, pearson_p)
print("Spearman rho, p-value:", spearman_r, spearman_p)

Pearson r, p-value: 0.7635021976212528 0.0
Spearman rho, p-value: 0.7516418172256819 0.0

25/11/06 15:35:44 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 155341 ms exceeds timeout 120000 ms
25/11/06 15:35:44 WARN SparkContext: Killing executors is not supported by current scheduler.
25/11/06 15:35:46 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:642)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1223)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:295)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@mib118093s.internal.sanger.ac.uk:57372
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:316)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:307)
	at scala.concurrent.impl.Promise.transformWith(Promise.scala:40)
	at scala.concurrent.impl.Promise.transformWith$(Promise.scala:38)
	at scala.concurrent.impl.Promise$DefaultPromise.transformWith(Promise.scala:187)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.asyncSetupEndpointRefByURI(NettyRpcEnv.scala:150)
	... 17 more
25/11/06 15:35:46 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@mib118093s.internal.sanger.ac.uk:57372
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:316)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:307)
	at scala.concurrent.impl.Promise.transformWith(Promise.scala:40)
	at scala.concurrent.impl.Promise.transformWith$(Promise.scala:38)
	at scala.concurrent.impl.Promise$DefaultPromise.transformWith(Promise.scala:187)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.asyncSetupEndpointRefByURI(NettyRpcEnv.scala:150)
	... 17 more
25/11/06 15:35:56 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@mib118093s.internal.sanger.ac.uk:57372
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.trySuccess(Promise.scala:94)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:94)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:225)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:239)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:238)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.Promise.success(Promise.scala:86)
	at scala.concurrent.Promise.success$(Promise.scala:86)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:187)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
25/11/06 15:35:56 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:642)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1223)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:295)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@mib118093s.internal.sanger.ac.uk:57372
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)

In [3]:
x=session.spark.read.parquet('gs://genetics-portal-dev-analysis/dc16/output/gentropy_paper/pleiotropic_discordant_variants')

In [5]:
x.count()

52

In [6]:
x.printSchema()

root
 |-- variantId: string (nullable = true)
 |-- betaSignConcordance: double (nullable = true)
 |-- uniqueDiseases: integer (nullable = true)
 |-- uniqueTherapeuticAreas: integer (nullable = true)
 |-- uniqueDiseaseNames: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- uniqueTherapeuticAreaNames: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- prioritisedGenes: array (nullable = true)
 |    |-- element: string (containsNull = true)

In [7]:
x.show(1)

+---------------+-------------------+--------------+----------------------+--------------------+--------------------------+-----------------+
|      variantId|betaSignConcordance|uniqueDiseases|uniqueTherapeuticAreas|  uniqueDiseaseNames|uniqueTherapeuticAreaNames| prioritisedGenes|
+---------------+-------------------+--------------+----------------------+--------------------+--------------------------+-----------------+
|19_44908684_T_C| 0.6594594594594595|            85|                    15|[MONDO_0021187, E...|      [OTAR_0000020, EF...|[ENSG00000130203]|
+---------------+-------------------+--------------+----------------------+--------------------+--------------------------+-----------------+
only showing top 1 row

In [8]:
x.select("prioritisedGenes").distinct().count()

41

In [14]:
x_exploded=x.withColumn("gene",f.explode("prioritisedGenes"))

In [15]:
x_exploded.count()

60

In [16]:
x_exploded.select("gene").distinct().count()

44

In [ ]:
x.toPandas().to_csv("./data/antagonistic_pl.csv",index=False)

25/11/06 19:25:39 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 220041 ms exceeds timeout 120000 ms
25/11/06 19:25:39 WARN SparkContext: Killing executors is not supported by current scheduler.
25/11/06 19:25:44 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@mib118093s.internal.sanger.ac.uk:60545
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:316)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:307)
	at scala.concurrent.impl.Promise.transformWith(Promise.scala:40)
	at scala.concurrent.impl.Promise.transformWith$(Promise.scala:38)
	at scala.concurrent.impl.Promise$DefaultPromise.transformWith(Promise.scala:187)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.asyncSetupEndpointRefByURI(NettyRpcEnv.scala:150)
	... 17 more
25/11/06 19:25:44 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:642)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1223)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:295)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@mib118093s.internal.sanger.ac.uk:60545
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:316)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:307)
	at scala.concurrent.impl.Promise.transformWith(Promise.scala:40)
	at scala.concurrent.impl.Promise.transformWith$(Promise.scala:38)
	at scala.concurrent.impl.Promise$DefaultPromise.transformWith(Promise.scala:187)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.asyncSetupEndpointRefByURI(NettyRpcEnv.scala:150)
	... 17 more
25/11/06 19:26:41 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@mib118093s.internal.sanger.ac.uk:60545
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.trySuccess(Promise.scala:94)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:94)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:225)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:239)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:238)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.Promise.success(Promise.scala:86)
	at scala.concurrent.Promise.success$(Promise.scala:86)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:187)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
25/11/06 19:26:41 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:642)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1223)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:295)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@mib118093s.internal.sanger.ac.uk:60545
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)

In [9]:
target=session.spark.read.parquet("gs://open-targets-pipeline-runs/il/25.09-testrun-1/output/target")

In [10]:
target.printSchema()

root
 |-- id: string (nullable = true)
 |-- approvedSymbol: string (nullable = true)
 |-- biotype: string (nullable = true)
 |-- transcriptIds: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- canonicalTranscript: struct (nullable = true)
 |    |-- id: string (nullable = true)
 |    |-- chromosome: string (nullable = true)
 |    |-- start: long (nullable = true)
 |    |-- end: long (nullable = true)
 |    |-- strand: string (nullable = true)
 |-- canonicalExons: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- genomicLocation: struct (nullable = true)
 |    |-- chromosome: string (nullable = true)
 |    |-- start: long (nullable = true)
 |    |-- end: long (nullable = true)
 |    |-- strand: integer (nullable = true)
 |-- alternativeGenes: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- approvedName: string (nullable = true)
 |-- go: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- source: string (nullable = true)
 |    |    |-- evidence: string (nullable = true)
 |    |    |-- aspect: string (nullable = true)
 |    |    |-- geneProduct: string (nullable = true)
 |    |    |-- ecoId: string (nullable = true)
 |-- hallmarks: struct (nullable = true)
 |    |-- attributes: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- pmid: long (nullable = true)
 |    |    |    |-- description: string (nullable = true)
 |    |    |    |-- attribute_name: string (nullable = true)
 |    |-- cancerHallmarks: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- pmid: long (nullable = true)
 |    |    |    |-- description: string (nullable = true)
 |    |    |    |-- impact: string (nullable = true)
 |    |    |    |-- label: string (nullable = true)
 |-- synonyms: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- label: string (nullable = true)
 |    |    |-- source: string (nullable = true)
 |-- symbolSynonyms: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- label: string (nullable = true)
 |    |    |-- source: string (nullable = true)
 |-- nameSynonyms: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- label: string (nullable = true)
 |    |    |-- source: string (nullable = true)
 |-- functionDescriptions: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- subcellularLocations: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- location: string (nullable = true)
 |    |    |-- source: string (nullable = true)
 |    |    |-- termSL: string (nullable = true)
 |    |    |-- labelSL: string (nullable = true)
 |-- targetClass: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- id: long (nullable = true)
 |    |    |-- label: string (nullable = true)
 |    |    |-- level: string (nullable = true)
 |-- obsoleteSymbols: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- label: string (nullable = true)
 |    |    |-- source: string (nullable = true)
 |-- obsoleteNames: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- label: string (nullable = true)
 |    |    |-- source: string (nullable = true)
 |-- constraint: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- constraintType: string (nullable = true)
 |    |    |-- score: float (nullable = true)
 |    |    |-- exp: float (nullable = true)
 |    |    |-- obs: integer (nullable = true)
 |    |    |-- oe: float (nullable = true)
 |    |    |-- oeLower: float (nullable = true)
 |    |    |-- oeUpper: float (nullable = true)
 |    |    |-- upperRank: integer (nullable = true)
 |    |    |-- upperBin: integer (nullable = true)
 |    |    |-- upperBin6: integer (nullable = true)
 |-- tep: struct (nullable = true)
 |    |-- targetFromSourceId: string (nullable = true)
 |    |-- description: string (nullable = true)
 |    |-- therapeuticArea: string (nullable = true)
 |    |-- url: string (nullable = true)
 |-- proteinIds: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- source: string (nullable = true)
 |-- dbXrefs: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- source: string (nullable = true)
 |-- chemicalProbes: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- control: string (nullable = true)
 |    |    |-- drugId: string (nullable = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- isHighQuality: boolean (nullable = true)
 |    |    |-- mechanismOfAction: array (nullable = true)
 |    |    |    |-- element: string (containsNull = true)
 |    |    |-- origin: array (nullable = true)
 |    |    |    |-- element: string (containsNull = true)
 |    |    |-- probeMinerScore: long (nullable = true)
 |    |    |-- probesDrugsScore: long (nullable = true)
 |    |    |-- scoreInCells: long (nullable = true)
 |    |    |-- scoreInOrganisms: long (nullable = true)
 |    |    |-- targetFromSourceId: string (nullable = true)
 |    |    |-- urls: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- niceName: string (nullable = true)
 |    |    |    |    |-- url: string (nullable = true)
 |-- homologues: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- speciesId: string (nullable = true)
 |    |    |-- speciesName: string (nullable = true)
 |    |    |-- homologyType: string (nullable = true)
 |    |    |-- targetGeneId: string (nullable = true)
 |    |    |-- isHighConfidence: string (nullable = true)
 |    |    |-- targetGeneSymbol: string (nullable = true)
 |    |    |-- queryPercentageIdentity: double (nullable = true)
 |    |    |-- targetPercentageIdentity: double (nullable = true)
 |    |    |-- priority: integer (nullable = true)
 |-- tractability: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- modality: string (nullable = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- value: boolean (nullable = true)
 |-- safetyLiabilities: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- event: string (nullable = true)
 |    |    |-- eventId: string (nullable = true)
 |    |    |-- effects: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- direction: string (nullable = true)
 |    |    |    |    |-- dosing: string (nullable = true)
 |    |    |-- biosamples: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- cellFormat: string (nullable = true)
 |    |    |    |    |-- cellLabel: string (nullable = true)
 |    |    |    |    |-- tissueId: string (nullable = true)
 |    |    |    |    |-- tissueLabel: string (nullable = true)
 |    |    |-- datasource: string (nullable = true)
 |    |    |-- literature: string (nullable = true)
 |    |    |-- url: string (nullable = true)
 |    |    |-- studies: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- description: string (nullable = true)
 |    |    |    |    |-- name: string (nullable = true)
 |    |    |    |    |-- type: string (nullable = true)
 |-- pathways: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- pathwayId: string (nullable = true)
 |    |    |-- pathway: string (nullable = true)
 |    |    |-- topLevelTerm: string (nullable = true)
 |-- tss: long (nullable = true)

In [11]:
target=target.select("approvedSymbol","id").withColumnRenamed("id","prioritisedGenes")

In [13]:
target.show(1)

+--------------+----------------+
|approvedSymbol|prioritisedGenes|
+--------------+----------------+
|        TSPAN6| ENSG00000000003|
+--------------+----------------+
only showing top 1 row

In [12]:
x=x.join(target,"prioritisedGenes","inner").cache()
x.count()

25/11/06 17:59:24 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

AnalysisException: [DATATYPE_MISMATCH.BINARY_OP_DIFF_TYPES] Cannot resolve "(prioritisedGenes = prioritisedGenes)" due to data type mismatch: the left and right operands of the binary operator have incompatible types ("ARRAY<STRING>" and "STRING").;
'Project [prioritisedGenes#172, variantId#166, betaSignConcordance#167, uniqueDiseases#168, uniqueTherapeuticAreas#169, uniqueDiseaseNames#170, uniqueTherapeuticAreaNames#171, approvedSymbol#230]
+- 'Join Inner, (prioritisedGenes#172 = prioritisedGenes#290)
   :- Relation [variantId#166,betaSignConcordance#167,uniqueDiseases#168,uniqueTherapeuticAreas#169,uniqueDiseaseNames#170,uniqueTherapeuticAreaNames#171,prioritisedGenes#172] parquet
   +- Project [approvedSymbol#230, id#229 AS prioritisedGenes#290]
      +- Project [approvedSymbol#230, id#229]
         +- Relation [id#229,approvedSymbol#230,biotype#231,transcriptIds#232,canonicalTranscript#233,canonicalExons#234,genomicLocation#235,alternativeGenes#236,approvedName#237,go#238,hallmarks#239,synonyms#240,symbolSynonyms#241,nameSynonyms#242,functionDescriptions#243,subcellularLocations#244,targetClass#245,obsoleteSymbols#246,obsoleteNames#247,constraint#248,tep#249,proteinIds#250,dbXrefs#251,chemicalProbes#252,... 5 more fields] parquet

In [6]:
vlp=session.spark.read.parquet("./data/varaint_effects_diseases")

In [7]:
vlp.count()

77405

In [8]:
vlp.select("variantId").distinct().count()

40706

In [9]:
vlp.select("diseaseId").distinct().count()

1403

In [10]:
vlp.show(1)

+--------------------+--------------------+---------------+--------------------+------+-------------------+---------------------+--------------------+-----------------+----------+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------------+------------------+------------------+-------------+
|             studyId|        studyLocusId|      variantId|             variant|geneId|       originalBeta|originalStandardError|     locusStatistics|finemappingMethod|isTransQtl|       variantEffect|majorLdPopulation|majorLdPopulationMaf| majorLdPopulationAf|   variantStatistics|     studyStatistics|  rescaledStatistics|traitFromSourceMappedIds|  absEstimatedBeta|               maf|    diseaseId|
+--------------------+--------------------+---------------+--------------------+------+-------------------+---------------------+--------------------+-----------------+----------+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------------+------------------+------------------+-------------+
|FINNGEN_R12_L12_P...|e955bcd0571170b09...|5_132287665_A_G|{5, 132287665, 13...|  NULL|-0.0290862861939678|             0.053922|{84, 475078, 1320...|            SuSie|      NULL|[{VEP, upstream_g...|       {fin, 1.0}|{0.29577731490248...|{fin_adj, 0.29577...|{33.5743867074724...|{844, 432874, 433...|{-, -5.7943409208...|         [MONDO_0026045]|0.3093166935496854|0.2957773149024806|MONDO_0026045|
+--------------------+--------------------+---------------+--------------------+------+-------------------+---------------------+--------------------+-----------------+----------+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------------+------------------+------------------+-------------+
only showing top 1 row

In [11]:
from pyspark.sql.window import Window

# Create window partitioned by variantId and studyId, ordered by absEstimatedBeta descending
window = Window.partitionBy("variantId", "studyId").orderBy(f.desc("absEstimatedBeta"))

# Keep only the row with the highest absEstimatedBeta for each variantId-studyId combination
vlp_deduplicated = vlp.withColumn("row_num", f.row_number().over(window)) \
                      .filter(f.col("row_num") == 1) \
                      .drop("row_num")

In [12]:
from pyspark.sql.window import Window

# Create a window partitioned by diseaseId and variantId, ordered by absEstimatedBeta descending
window = Window.partitionBy("diseaseId", "variantId").orderBy(f.desc("absEstimatedBeta"))

# Add row number and filter for the first row (max absEstimatedBeta)
vlp_beta_max = vlp_deduplicated.withColumn("row_num", f.row_number().over(window)) \
             .filter(f.col("row_num") == 1) \
             .drop("row_num") \
             .cache()

vlp_beta_max.count()

54728

In [13]:
# Count unique diseases per variant
ps = vlp_deduplicated.groupBy("variantId").agg(
    f.countDistinct("diseaseId").alias("uniqueDiseases")
)

# Show the result
ps.show()

+----------------+--------------+
|       variantId|uniqueDiseases|
+----------------+--------------+
| 1_176005154_T_C|             1|
| 17_71220546_T_C|             1|
|  9_35522667_A_G|             1|
| 3_107499086_T_A|             1|
|10_121156039_T_C|             2|
|  6_20377383_C_T|             1|
|12_109806478_T_C|             2|
| 18_33833715_C_T|             1|
| X_130238143_G_C|             1|
|  9_21998661_G_A|             1|
|10_62672213_CT_C|             1|
| 6_126434496_T_G|             1|
|  19_7200979_C_T|             1|
|  6_19377102_A_G|             1|
| 6_133947684_G_A|             1|
|  9_21973423_G_T|             2|
| 3_128179658_A_C|             1|
|12_111440722_T_C|             1|
| 16_53796143_C_G|             1|
|  4_81665896_A_G|             2|
+----------------+--------------+
only showing top 20 rows

In [14]:
ps.filter(f.col("uniqueDiseases")>10).show()

+----------------+--------------+
|       variantId|uniqueDiseases|
+----------------+--------------+
|  6_36679512_G_A|            11|
|11_116778201_G_C|            21|
| 16_53772541_A_G|            15|
| 7_130023656_C_T|            11|
|  2_43845437_G_T|            13|
|   5_1287079_G_A|            16|
|   5_1279675_C_T|            22|
|  9_22103814_A_G|            12|
| 16_53769311_G_A|            13|
| 12_57133500_T_C|            16|
|  9_22124505_A_T|            16|
| 22_43928850_C_T|            18|
| 2_162267541_C_T|            15|
|12_111395984_G_A|            12|
| 19_33235671_G_A|            11|
| 11_76582682_G_T|            11|
| 4_102267552_C_T|            41|
| 16_20381010_G_A|            14|
| 8_125487789_C_G|            12|
| 7_150993088_C_T|            20|
+----------------+--------------+
only showing top 20 rows

In [15]:
vlp_beta_max_high_ps=vlp_beta_max.join(ps.filter(f.col("uniqueDiseases")>10).select("variantId"),"variantId","inner")
vlp_beta_max_high_ps.count()

2153

In [16]:
from scipy.stats import gamma
import pandas as pd
import numpy as np

# Assume spark session exists
# spark = SparkSession.builder.getOrCreate()

# Define a UDF to fit gamma and return shape, scale
def fit_gamma_udf(values):
    values = np.array(values)
    values = values[values > 0]  # Gamma requires positive values
    if len(values) < 10:
        return (None, None)
    # Fit gamma: use method-of-moments or MLE
    # scipy.stats.gamma.fit returns (shape, loc, scale)
    try:
        shape, loc, scale = gamma.fit(values, floc=0)
        return float(shape), float(scale)
    except Exception:
        return (None, None)

from pyspark.sql.types import StructType, StructField, DoubleType

gamma_schema = StructType([
    StructField("shape", DoubleType(), True),
    StructField("scale", DoubleType(), True)
])

# Collect absEstimatedBeta list per variantId
beta_grouped = (vlp_beta_max_high_ps
                .groupBy("variantId")
                .agg(f.collect_list(f.col("absEstimatedBeta")).alias("beta_list")))

# Register UDF
fit_gamma_spark_udf = f.udf(fit_gamma_udf, gamma_schema)

# Fit gamma on absEstimatedBeta
gamma_fitted = beta_grouped.withColumn("gamma_fit_beta", fit_gamma_spark_udf("beta_list"))

# Extract shape/scale
gamma_fitted = gamma_fitted.select(
    "variantId",
    gamma_fitted["gamma_fit_beta"].shape.alias("beta_shape"),
    gamma_fitted["gamma_fit_beta"].scale.alias("beta_scale")
)

# Now also fit gamma for absEstimatedBeta^2
def fit_gamma_squared_udf(values):
    values = np.array(values)
    values = values[values > 0]  # gamma positive
    values = values ** 2
    if len(values) < 10:
        return (None, None)
    try:
        shape, loc, scale = gamma.fit(values, floc=0)
        return float(shape), float(scale)
    except Exception:
        return (None, None)

fit_gamma_sq_udf = f.udf(fit_gamma_squared_udf, gamma_schema)

gamma_fitted = gamma_fitted.join(
    beta_grouped.withColumn("gamma_fit_beta2", fit_gamma_sq_udf("beta_list"))
                .select("variantId",
                        f.col("gamma_fit_beta2").shape.alias("beta2_shape"),
                        f.col("gamma_fit_beta2").scale.alias("beta2_scale")),
    on="variantId"
)

# Collect to pandas
gamma_params_df = gamma_fitted.toPandas()

In [17]:
gamma_params_df

               variantId  beta_shape  beta_scale  beta2_shape  beta2_scale
0          5_1286401_C_A    1.368556    0.220707     0.496392     0.292685
1        2_102319699_T_A    9.228355    0.016719     2.254006     0.011999
2       12_111569952_C_T    3.794427    0.017385     0.972369     0.006166
3        1_113761186_C_A    2.016312    0.163392     0.666888     0.237130
4        5_111066174_T_C    2.615563    0.059133     0.725366     0.050328
..                   ...         ...         ...          ...          ...
113      20_33950585_G_C    3.105251    0.088427     1.015774     0.093242
114      15_27985172_C_T    7.109712    0.023085     1.974074     0.015544
115      16_53769662_T_A    5.147720    0.014265     1.468838     0.004382
116  1_152312600_CACTG_C    3.706280    0.108171     1.078367     0.191155
117       5_56148856_G_A    1.694628    0.093558     0.435536     0.134230

[118 rows x 5 columns]

In [18]:
vlp_beta_max_high_ps.filter(f.col("variantId")=="9_22124745_C_G").select("absEstimatedBeta").show(100)

+--------------------+
|    absEstimatedBeta|
+--------------------+
| 0.07883535278110519|
|0.030872661279000867|
| 0.05363171690758647|
| 0.03850553581657284|
| 0.13520505194742938|
| 0.06502301093338424|
| 0.07489795645306359|
| 0.04365983747099578|
| 0.11083026574244388|
| 0.12445843669420355|
| 0.07684962939896704|
| 0.11580216127797223|
| 0.22287798151967794|
| 0.05991694265080245|
|  0.1888225775300826|
| 0.03891898167610717|
| 0.05491866198626455|
| 0.20340966480076852|
|  0.2052254670613944|
+--------------------+

In [19]:
import numpy as np
from sklearn.mixture import GaussianMixture

# Initialize output array
out = np.full((1,6), np.nan)

# Original |β| values
vals = np.array([
    0.07883535278110519,0.030872661279000867,0.03891898167610717,
    0.05363171690758647,0.03850553581657284,0.13520505194742938,
    0.06502301093338424,0.07489795645306359,0.04365983747099578,
    0.11083026574244388,0.12445843669420355,0.07684962939896704,
    0.11580216127797223,0.22287798151967794,0.05991694265080245,
    0.1888225775300826,0.03891898167610717,0.05491866198626455,
    0.20340966480076852,0.2052254670613944
])

# Square the values
X2 = vals**2
X2_reshaped = X2.reshape(-1,1)

# Fit 1-component Gaussian mixture
mix1 = GaussianMixture(n_components=1, random_state=123)
mix1.fit(X2_reshaped)

# Fit 2-component Gaussian mixture
mix2 = GaussianMixture(n_components=2, random_state=123)
mix2.fit(X2_reshaped)

# Compute BIC and AIC
bic1 = mix1.bic(X2_reshaped)
bic2 = mix2.bic(X2_reshaped)
aic1 = mix1.aic(X2_reshaped)
aic2 = mix2.aic(X2_reshaped)

# Cluster assignments for 2-component mixture
clusters2 = mix2.predict(X2_reshaped)

# Proportion of points in cluster 2
prop2 = np.mean(clusters2 == 1)  # sklearn labels 0/1
cluster_balance = min(prop2, 1-prop2)

# Fill output array
out[0,0] = len(vals)
out[0,1] = bic1
out[0,2] = bic2
out[0,3] = aic1
out[0,4] = aic2
out[0,5] = cluster_balance

print(out)

[[  20.         -104.25565878 -117.76160009 -106.24712332 -122.74026146
     0.2       ]]

In [34]:
import numpy as np
import pandas as pd
from sklearn.mixture import GaussianMixture
from pyspark.sql import functions as f
from pyspark.sql.types import StructType, StructField, DoubleType, StringType, LongType

# Define output schema with cluster means, max_vals2, and maxMAF added
schema = StructType([
    StructField("variantId", StringType()),
    StructField("n_points", LongType()),
    StructField("bic1", DoubleType()),
    StructField("bic2", DoubleType()),
    StructField("aic1", DoubleType()),
    StructField("aic2", DoubleType()),
    StructField("cluster_balance", DoubleType()),
    StructField("cluster1_mean", DoubleType()),
    StructField("cluster2_mean", DoubleType()),
    StructField("max_vals2", DoubleType()),
    StructField("maxMAF", DoubleType())
])

def fit_gaussian_mixture(pdf: pd.DataFrame) -> pd.DataFrame:
    results = []
    # ensure variantId is a string
    variant_id = str(pdf["variantId"].iloc[0])
    vals = pdf["absEstimatedBeta"].dropna().values
    vals2 = vals ** 2
    
    # Calculate max of vals2
    max_vals2 = float(np.max(vals2)) if len(vals2) > 0 else np.nan
    
    # Calculate max of MAF
    maf_values = pdf["maf"].dropna().values
    max_maf = float(np.max(maf_values)) if len(maf_values) > 0 else np.nan

    if len(vals2) < 10:
        results.append([variant_id, len(vals2), np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, max_vals2, max_maf])
    else:
        X2 = vals2.reshape(-1, 1)
        try:
            # Fit 1- and 2-component Gaussian mixtures
            mix1 = GaussianMixture(n_components=1, random_state=123).fit(X2)
            mix2 = GaussianMixture(n_components=2, random_state=123).fit(X2)

            # Compute AIC/BIC
            bic1, bic2 = mix1.bic(X2), mix2.bic(X2)
            aic1, aic2 = mix1.aic(X2), mix2.aic(X2)

            # Cluster balance
            clusters2 = mix2.predict(X2)
            prop2 = np.mean(clusters2 == 1)
            cluster_balance = min(prop2, 1 - prop2)

            # Extract cluster means from the 2-component mixture
            cluster1_mean = float(mix2.means_[0][0])
            cluster2_mean = float(mix2.means_[1][0])

            results.append([variant_id, len(vals2), bic1, bic2, aic1, aic2, cluster_balance, cluster1_mean, cluster2_mean, max_vals2, max_maf])

        except Exception:
            results.append([variant_id, len(vals2), np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, max_vals2, max_maf])

    return pd.DataFrame(results, columns=[c.name for c in schema.fields])

# Apply grouped Pandas UDF
result_sdf = vlp_beta_max_high_ps.groupBy("variantId").applyInPandas(fit_gaussian_mixture, schema)

# Collect to pandas
result_df = result_sdf.toPandas()

print(result_df.head())

          variantId  n_points       bic1       bic2       aic1       aic2  \
0  10_112994312_T_C        16 -41.334811 -52.940810 -42.879988 -56.803754
1  10_112995025_T_C        11 -37.636370 -37.303100 -38.432160 -39.292576
2  10_112998590_C_T        52  92.424144 -46.297962  88.521657 -56.054181
3    10_6052734_C_T        14 -33.607757 -61.393513 -34.885871 -64.588800
4  11_116778201_G_C        21  15.086185  -4.056822  12.997140  -9.279434

   cluster_balance  cluster1_mean  cluster2_mean  max_vals2    maxMAF
0         0.500000       0.004935       0.080194   0.199758  0.293772
1         0.363636       0.068489       0.015255   0.124536  0.293328
2         0.019231       0.036446       3.896852   3.896852  0.293143
3         0.142857       0.180886       0.019192   0.228003  0.089884
4         0.047619       0.099144       1.286829   1.286829  0.137992

In [35]:
result_df

,variantId,n_points,bic1,bic2,aic1,aic2,cluster_balance,cluster1_mean,cluster2_mean,max_vals2,maxMAF
0,10_112994312_T_C,16,-41.334811,-52.940810,-42.879988,-56.803754,0.500000,0.004935,0.080194,0.199758,0.293772
1,10_112995025_T_C,11,-37.636370,-37.303100,-38.432160,-39.292576,0.363636,0.068489,0.015255,0.124536,0.293328
2,10_112998590_C_T,52,92.424144,-46.297962,88.521657,-56.054181,0.019231,0.036446,3.896852,3.896852,0.293143
3,10_6052734_C_T,14,-33.607757,-61.393513,-34.885871,-64.588800,0.142857,0.180886,0.019192,0.228003,0.089884
4,11_116778201_G_C,21,15.086185,-4.056822,12.997140,-9.279434,0.047619,0.099144,1.286829,1.286829,0.137992
...,...,...,...,...,...,...,...,...,...,...,...
113,9_133274293_AC_A,12,-88.522244,-87.255805,-89.492057,-89.680338,0.333333,0.002913,0.011640,0.017171,0.202442
114,9_133274295_A_T,15,-31.729255,-60.200595,-33.145356,-63.740846,0.400000,0.005587,0.134466,0.199179,0.194176
115,9_22103814_A_G,12,-45.709796,-50.606293,-46.679609,-53.030826,0.083333,0.027593,0.114795,0.114795,0.490481
116,9_22124505_A_T,16,-95.397682,-103.909833,-96.942859,-107.772776,0.500000,0.003969,0.020996,0.036819,0.498646
117,9_22124745_C_G,19,-98.473954,-110.657731,-100.362832,-115.379926,0.210526,0.006451,0.042205,0.049675,0.497881

In [36]:
sum(result_df["bic2"]<result_df["bic1"])

100

In [37]:
result_df["cluster_balance"].describe()

count    118.000000
mean       0.222058
std        0.151927
min        0.019231
25%        0.083333
50%        0.197856
75%        0.356061
max        0.500000
Name: cluster_balance, dtype: float64

In [38]:
100/118

0.847457627118644

In [39]:
result_df[result_df["cluster_balance"]==0.5]

,variantId,n_points,bic1,bic2,aic1,aic2,cluster_balance,cluster1_mean,cluster2_mean,max_vals2,maxMAF
0,10_112994312_T_C,16,-41.334811,-52.940810,-42.879988,-56.803754,0.5,0.004935,0.080194,0.199758,0.293772
5,11_1219991_G_T,12,38.786597,27.272622,37.816784,24.848089,0.5,0.047727,1.700959,2.971126,0.114920
45,19_10352442_G_C,18,-27.340383,-42.285845,-29.121127,-46.737704,0.5,0.162768,0.023078,0.366773,0.044501
116,9_22124505_A_T,16,-95.397682,-103.909833,-96.942859,-107.772776,0.5,0.003969,0.020996,0.036819,0.498646

In [26]:
vlp_beta_max_high_ps.filter(f.col("variantId")=="11_1219991_G_T").show(100)

+--------------+--------------------+--------------------+--------------------+------+--------------------+---------------------+--------------------+-----------------+----------+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------------+-------------------+-------------------+-------------+
|     variantId|             studyId|        studyLocusId|             variant|geneId|        originalBeta|originalStandardError|     locusStatistics|finemappingMethod|isTransQtl|       variantEffect|majorLdPopulation|majorLdPopulationMaf| majorLdPopulationAf|   variantStatistics|     studyStatistics|  rescaledStatistics|traitFromSourceMappedIds|   absEstimatedBeta|                maf|    diseaseId|
+--------------+--------------------+--------------------+--------------------+------+--------------------+---------------------+--------------------+-----------------+----------+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------------+-------------------+-------------------+-------------+
|11_1219991_G_T|     FINNGEN_R12_IPF|b733c60b0ccb911f9...|{11, 1219991, 121...|  NULL|   0.987311953819738|            0.0337249|{1, 0, 1219991, 1...|            SuSie|      NULL|[{VEP, splice_reg...|       {fin, 1.0}|{0.11491973559962...|{fin_adj, 0.11491...|{930.217208465043...|{2700, 494583, 49...|{+, 30.4994624291...|           [EFO_0009448]| 1.3049350054237743|0.11491973559962229|  EFO_0009448|
|11_1219991_G_T|        GCST90476035|d632a8d98454c7b0c...|{11, 1219991, 121...|  NULL|0.010094655164228382|                 NULL|{1, 0, 1219991, 1...|        SuSiE-inf|      NULL|[{VEP, splice_reg...|       {nfe, 1.0}|{0.11029887627228...|{nfe_adj, 0.11029...|{46.8251983868463...|{32246, 399549, 4...|{+, 6.84289400669...|           [EFO_0009686]|0.08941966889293186|0.11029887627228334|  EFO_0009686|
|11_1219991_G_T|          GCST004986|57879008973767831...|{11, 1219991, 121...|  NULL|   1.061256502124341|                 NULL|{1, 0, 1219991, 1...|             PICS|      NULL|[{VEP, splice_reg...|       {nfe, 1.0}|{0.11029887627228...|{nfe_adj, 0.11029...|{297.786611661662...|{602, 3366, 3968,...|{+, 17.2564947675...|           [EFO_0000768]| 1.7236953223778386|0.11029887627228334|  EFO_0000768|
|11_1219991_G_T|FINNGEN_R12_J10_A...|0ebf3aea44a4f9f89...|{11, 1219991, 121...|  NULL|   0.415224515978242|            0.0748017|{1, 0, 1219991, 1...|            SuSie|      NULL|[{VEP, splice_reg...|       {fin, 1.0}|{0.11491973559962...|{fin_adj, 0.11491...|{34.3871312627566...|{807, 494595, 495...|{+, 5.86405416608...|           [EFO_0007153]|  0.458048628873216|0.11491973559962229|  EFO_0007153|
|11_1219991_G_T|FINNGEN_R12_ILD_E...|a339cfa94ad66e337...|{11, 1219991, 121...|  NULL|    0.77039468344078|            0.0252372|{1, 0, 1219991, 1...|            SuSie|      NULL|[{VEP, splice_reg...|       {fin, 1.0}|{0.11491973559962...|{fin_adj, 0.11491...|{1003.55280473651...|{5765, 494583, 50...|{+, 31.6789015708...|           [EFO_0004244]| 0.9304291648706933|0.11491973559962229|  EFO_0004244|
|11_1219991_G_T|        GCST90476532|16b78e6055a96e6e2...|{11, 1219991, 121...|  NULL|               1.198|  0.08673470239250028|{1, 0, 1219991, 1...|             PICS|      NULL|[{VEP, splice_reg...|       {amr, 1.0}|{0.08503267973856...|{amr_adj, 0.08503...|{142.959201805958...|{414, 59195, 5960...|{+, 11.9565547632...|           [EFO_0000684]| 1.4948877063351689|0.08503267973856209|  EFO_0000684|
|11_1219991_G_T|        GCST90454507|2e8caca0a3571b80c...|{11, 1219991, 121...|  NULL|             -0.1024| 0.014540815383804088|{1, 0, 1219991, 1...|             PICS|      NULL|[{VEP, splice_reg...|       {nfe, 0.0}|{0.11029887627228...|{nfe_adj, 0.11029...|{49.4839626884232...|{4702, 68573, 733...|{-, -7.0344838253...|         [MONDO_0100096]|0.23936705082420268|0.11029887627228334|MONDO_0100096|
|11_1219991_G_T|FINNGEN_R12_ILD_I...|53054869b4883beb0...|{11, 1219991, 121...|  NULL|   0.830282374407972|             0.056961|{1, 0, 1219991, 1...|            SuSie|      NULL|[{VEP, splice_reg...|       {fin, 1.0}|{0.11491973559962...|{fin_adj, 0.11491...|{216.550835951744...|{1047, 494583, 49...|{+, 14.7156663441...|    [HP_0002093, EFO_...| 1.0093973419868447|0.11491973559962229|   HP_0002093|
|11_1219991_G_T|        GCST90476043|ab10b99830690c0a1...|{11, 1219991, 121...|  NULL|0.011547605084078507|                 NULL|{1, 0, 1219991, 1...|        SuSiE-inf|      NULL|[{VEP, splice_reg...|       {nfe, 1.0}|{0.11029887627228...|{nfe_adj, 0.11029...|{56.6361920059650...|{37129, 380175, 4...|{+, 7.52570209388...|            [HP_0002088]|0.09236390409155924|0.11029887627228334|   HP_0002088|
|11_1219991_G_T|        GCST90476042|84c5b5e508f5a1579...|{11, 1219991, 121...|  NULL|0.010054360295797343|                 NULL|{1, 0, 1219991, 1...|        SuSiE-inf|      NULL|[{VEP, splice_reg...|       {nfe, 1.0}|{0.11029887627228...|{nfe_adj, 0.11029...|{39.3856907106382...|{73299, 314625, 3...|{+, 6.27580199740...|            [HP_0002094]|0.05809975583400051|0.11029887627228334|   HP_0002094|
|11_1219991_G_T|        GCST90476031|4ab5e35b5899a8887...|{11, 1219991, 121...|  NULL|               1.082|  0.08163265123659251|{1, 0, 1219991, 1...|             PICS|      NULL|[{VEP, splice_reg...|       {amr, 1.0}|{0.08503267973856...|{amr_adj, 0.08503...|{135.995332768690...|{510, 58927, 5943...|{+, 11.6617036820...|         [MONDO_0001438]| 1.3147327053440152|0.08503267973856209|MONDO_0001438|
|11_1219991_G_T|        GCST90476037|8bd553a760c48fd47...|{11, 1219991, 121...|  NULL|0.009539365235021153|                 NULL|{1, 0, 1219991, 1...|        SuSiE-inf|      NULL|[{VEP, splice_reg...|       {nfe, 1.0}|{0.11029887627228...|{nfe_adj, 0.11029...|{45.6869096293976...|{9729, 432527, 44...|{+, 6.75920924586...|           [EFO_0010720]| 0.1564117710175771|0.11029887627228334|  EFO_0010720|
+--------------+--------------------+--------------------+--------------------+------+--------------------+---------------------+--------------------+-----------------+----------+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------------+-------------------+-------------------+-------------+

In [27]:
result_df[result_df["bic2"]>result_df["bic1"]]

,variantId,n_points,bic1,bic2,aic1,aic2,cluster_balance,cluster1_mean,cluster2_mean,max_vals2
1,10_112995025_T_C,11,-37.636370,-37.303100,-38.432160,-39.292576,0.363636,0.068489,0.015255,0.124536
6,11_30204809_T_C,15,-74.562824,-71.704089,-75.978925,-75.244340,0.466667,0.038542,0.011952,0.065551
22,12_120978847_A_C,14,-133.035484,-126.577561,-134.313599,-129.772847,0.071429,0.005693,0.003313,0.008016
25,14_36269155_C_T,11,-5.077636,-3.955558,-5.873427,-5.945034,0.454545,0.336557,0.061098,0.473455
29,15_27985172_C_T,13,-56.051988,-52.908664,-57.181887,-55.733411,0.461538,0.041639,0.013519,0.095792
35,16_20381010_G_A,14,-60.820320,-58.500846,-62.098434,-61.696132,0.428571,0.011839,0.045499,0.087406
39,16_53769662_T_A,17,-122.840930,-122.700684,-124.507357,-126.866751,0.294118,0.003324,0.012030,0.022424
48,19_33235671_G_A,11,-74.400470,-74.328151,-75.196261,-76.317627,0.272727,0.008110,0.021603,0.024135
49,19_40847202_T_C,13,-96.653475,-91.729436,-97.783374,-94.554183,0.461538,0.014992,0.007315,0.020991
62,1_152313385_G_A,16,30.156168,33.237726,28.610990,29.374782,0.375000,0.894115,0.161287,1.974053
65,1_55039974_G_T,21,-49.493153,-45.284227,-51.582198,-50.506839,0.333333,0.058240,0.164437,0.255355
67,20_34077942_A_G,18,-30.420740,-27.584852,-32.201484,-32.036711,0.111111,0.078216,0.301745,0.345673
85,5_1279913_G_A,11,-36.987175,-36.775759,-37.782966,-38.765235,0.454545,0.075265,0.015471,0.103106
90,5_33951588_C_G,20,-18.308775,-17.057229,-20.300239,-22.035890,0.300000,0.090804,0.342556,0.465460
95,6_160576086_A_T,11,-35.082170,-30.001445,-35.877961,-31.990921,0.272727,0.128694,0.065212,0.142997
98,6_160591981_T_C,27,-5.478298,-1.116864,-8.069972,-7.596048,0.185185,0.239124,0.497225,0.874803
106,7_29092663_A_G,11,-42.078698,-38.826472,-42.874489,-40.815948,0.363636,0.030313,0.083375,0.099228
113,9_133274293_AC_A,12,-88.522244,-87.255805,-89.492057,-89.680338,0.333333,0.002913,0.011640,0.017171

In [28]:
vlp_beta_max_high_ps.filter(f.col("variantId")=="6_160591981_T_C").show(100)

+---------------+--------------------+--------------------+--------------------+------+--------------------+---------------------+--------------------+-----------------+----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------------+-------------------+--------------------+---------------+
|      variantId|             studyId|        studyLocusId|             variant|geneId|        originalBeta|originalStandardError|     locusStatistics|finemappingMethod|isTransQtl|       variantEffect|   majorLdPopulation|majorLdPopulationMaf| majorLdPopulationAf|   variantStatistics|     studyStatistics|  rescaledStatistics|traitFromSourceMappedIds|   absEstimatedBeta|                 maf|      diseaseId|
+---------------+--------------------+--------------------+--------------------+------+--------------------+---------------------+--------------------+-----------------+----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------------+-------------------+--------------------+---------------+
|6_160591981_T_C|          GCST007990|ba05d086c2caba441...|{6, 160591981, 16...|  NULL|  0.6523251860396901|                 NULL|{1, 0, 160591981,...|             PICS|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{90.3454999206281...|{4831, 115455, 12...|{+, 9.50502498264...|           [EFO_0001645]| 0.8029210233300071|0.015346621979185042|    EFO_0001645|
|6_160591981_T_C|        GCST90043957|ae1d04e68887b7dd5...|{6, 160591981, 16...|  NULL|0.021896156167056414|                 NULL|{1, 0, 160591981,...|        SuSiE-inf|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{199.382366484566...|{16041, 440307, 4...|{+, 14.1202820964...|         [MONDO_0021661]| 0.6528822346718518|0.015346621979185042|  MONDO_0021661|
|6_160591981_T_C|FINNGEN_R12_I9_CA...|53a1cede56df70c19...|{6, 160591981, 16...|  NULL|   0.533341543089951|            0.0610883|{1, 0, 160591981,...|            SuSie|      NULL|[{VEP, intron_var...|          {fin, 1.0}|{0.00790662650602...|{fin_adj, 0.00790...|{76.6461920481785...|{12418, 487930, 5...|{+, 8.75478109653...|           [EFO_0000266]| 0.6351698909122793|0.007906626506024096|    EFO_0000266|
|6_160591981_T_C|FINNGEN_R12_E4_HY...|e91c8fa1726189ee8...|{6, 160591981, 16...|  NULL|   0.497738017567368|            0.0518354|{1, 0, 160591981,...|            SuSie|      NULL|[{VEP, intron_var...|          {fin, 1.0}|{0.00790662650602...|{fin_adj, 0.00790...|{93.0142184257184...|{17615, 420066, 4...|{+, 9.64438792385...|         [MONDO_0021187]| 0.5921974648835305|0.007906626506024096|  MONDO_0021187|
|6_160591981_T_C|        GCST90435753|925f089460bacdcc8...|{6, 160591981, 16...|  NULL|0.021209268312473252|                 NULL|{1, 0, 160591981,...|        SuSiE-inf|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{167.173973441275...|{35927, 373034, 4...|{+, 12.9295774656...|           [EFO_0000589]| 0.4108445315362582|0.015346621979185042|    EFO_0000589|
|6_160591981_T_C|        GCST90475992|3a497ad3a8ab33181...|{6, 160591981, 16...|  NULL|              0.3325|  0.03571428966765501|{1, 0, 160591981,...|             PICS|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{81.2390568797854...|{24982, 414741, 4...|{+, 9.01327115312...|           [EFO_0009659]| 0.3377589432103398|0.015346621979185042|    EFO_0009659|
|6_160591981_T_C|   FINNGEN_R12_E4_FH|3a741111cabdc86f7...|{6, 160591981, 16...|  NULL|  0.0775621125473084|            0.0853316|{300, 2951157, 15...|            SuSie|      NULL|[{VEP, intron_var...|          {fin, 1.0}|{0.00790662650602...|{fin_adj, 0.00790...|{24.3621910742990...|{6545, 420066, 42...|{+, 4.93580703373...|           [EFO_0004911]|0.49087817335225065|0.007906626506024096|    EFO_0004911|
|6_160591981_T_C|        GCST90435755|0c5969e54d1254e31...|{6, 160591981, 16...|  NULL|0.020918559802206894|                 NULL|{1, 0, 160591981,...|        SuSiE-inf|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{163.812175094512...|{33242, 373034, 4...|{+, 12.7989130434...|            [HP_0003124]| 0.4214080310977648|0.015346621979185042|     HP_0003124|
|6_160591981_T_C|        GCST90436077|846c8f935b794e1a0...|{6, 160591981, 16...|  NULL|0.018701283205195773|                 NULL|{1, 0, 160591981,...|        SuSiE-inf|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{130.135122886209...|{14921, 377103, 3...|{+, 11.4076782425...|           [EFO_0003777]| 0.5477237198313495|0.015346621979185042|    EFO_0003777|
|6_160591981_T_C|        GCST90475914|f196105f8b376ad53...|{6, 160591981, 16...|  NULL|0.015730316027213892|                 NULL|{3, 98687, 160591...|        SuSiE-inf|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{92.5197068996511...|{20077, 418636, 4...|{+, 9.61871648920...|           [EFO_0009531]|0.39973906948163723|0.015346621979185042|    EFO_0009531|
|6_160591981_T_C|  FINNGEN_R12_I9_IHD|3cefa23a3fe1d36f0...|{6, 160591981, 16...|  NULL|   0.380750867833675|            0.0312442|{1, 0, 160591981,...|            SuSie|      NULL|[{VEP, intron_var...|          {fin, 1.0}|{0.00790662650602...|{fin_adj, 0.00790...|{140.306795037901...|{84088, 416260, 5...|{+, 11.8451169279...|           [EFO_1001375]| 0.3575519908153094|0.007906626506024096|    EFO_1001375|
|6_160591981_T_C|        GCST90480135|48a382bdaf62cc0c7...|{6, 160591981, 16...|  NULL| 0.00898572233580819|                 NULL|{3, 98687, 160591...|        SuSiE-inf|      NULL|[{VEP, intron_var...|{nfe, 0.786718084...|{0.01534662197918...|{nfe_adj, 0.01534...|{45.9908084894579...|{4282, 564130, 56...|{+, 6.78165234212...|           [EFO_0000319]| 0.5983993712046254|0.015346621979185042|    EFO_0000319|
|6_160591981_T_C|        GCST90436072|0007ab98d1684c596...|{6, 160591981, 16...|  NULL|0.014765583557664443|                 NULL|{1, 0, 160591981,...|        SuSiE-inf|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{76.5386987589726...|{5181, 377103, 38...|{+, 8.74863982336...|           [EFO_1000985]| 0.7039368897296913|0.015346621979185042|    EFO_1000985|
|6_160591981_T_C|          GCST009541|ef1d1ffb10d2ba513...|{6, 160591981, 16...|  NULL|0.006796699337223395|                 NULL|{2, 261482, 16033...|        SuSiE-inf|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{42.4086853337419...|{47309, 930014, 9...|{+, 6.51219512405...|           [EFO_0003144]| 0.1765496065469878|0.015346621979185042|    EFO_0003144|
|6_160591981_T_C|FINNGEN_R12_I9_AB...|7030db646299f32d1...|{6, 160591981, 16...|  NULL|   0.465878542600573|            0.0999363|{2, 62371, 160591...|            SuSie|      NULL|[{VEP, intron_var...|          {fin, 1.0}|{0.00790662650602...|{fin_adj, 0.00790...|{31.2173080130412...|{4439, 463106, 46...|{+, 5.58724511839...|           [EFO_0004214]|  0.672728415859717|0.007906626506024096|    EFO_0004214|
|6_160591981_T_C|FINNGEN_R12_I9_ANGIO|eb3ce99915154de68...|{6, 160591981, 16...|  NULL|   0.547988695151375|            0.0570836|{1, 0, 160591981,...|            SuSie|      NULL|[{VEP, intron_var...|          {fin, 1.0}|{0.00790662650602...|{fin_adj, 0.00790...|{92.2115208651255...|{18248, 416171, 4...|{+, 9.60268300346...|           [EFO_0003951]| 0.5798512141197723|0.007906626506024096|    EFO_0003951|
|6_160591981_T_C|  FINNGEN_R12_I9_VHD|4cd73a13947f48c74...|{6, 160591981, 16...|  NULL|   0.158203603083976|            0.0460645|{11, 261890, 1603...|            SuSie|      NULL|[{VEP, intron_var...|          {fin, 1.0}|{0.00790662650602...|{fin_adj, 0.00790...|{45.2513616821567...|{28602, 375343, 4...|{+, 6.72691323581...|           [EFO_1001161]|0.32944103881127257|0.007906626506024096|    EFO_1001161|
|6_160591981_T_C|        GCST90475999|aa3c4a1ac2d0518ec...|{6, 160591981, 16...|  NULL|                0.58|  0.07653061528595126|{8, 216822, 16047...|             PICS|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{48.6886339943431...|{3957, 442419, 44...|{+, 6.97772412713...|            [HP_0001907]| 0.6409161569322525|0.015346621979185042|     HP_0001907|
|6_160591981_T_C|        GCST90310293|1bca62902a2068503...|{6, 160591981, 16...|  NULL|0.010701571937669638|                 NULL|{1, 0, 160591981,...|        SuSiE-inf|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{103.016871591123...|{14819, 941863, 9...|{+, 10.1497227346...|    [EFO_0000266, EFO...|0.48336097000360023|0.015346621979185042|    EFO_0005239|
|6_160591981_T_C|        GCST90436073|478af76c14e1afeb9...|{6, 160591981, 16...|  NULL|0.017641348063744212|                 NULL|{1, 0, 160591981,...|        SuSiE-inf|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{110.010716372385...|{11703, 377103, 3...|{+, 10.4885993522...|           [EFO_0000612]| 0.5662944379380147|0.015346621979185042|    EFO_0000612|
|6_160591981_T_C|FINNGEN_R12_RX_ST...|afada91fc64d7b706...|{6, 160591981, 16...|  NULL|   0.500440879081886|            0.0258402|{1, 0, 160591981,...|            SuSie|      NULL|[{VEP, intron_var...|          {fin, 1.0}|{0.00790662650602...|{fin_adj, 0.00790...|{330.569647838986...|{183578, 316770, ...|{+, 18.1815744048...|            [GO_0036273]|0.42579283392960043|0.007906626506024096|     GO_0036273|
|6_160591981_T_C|        GCST90043953|89b14accd87610539...|{6, 160591981, 16...|  NULL|  0.0110477337403497|                 NULL|{1, 0, 160591981,...|        SuSiE-inf|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{52.5782300973064...|{4403, 451945, 45...|{+, 7.25108475314...|           [EFO_0003913]| 0.6316417645788861|0.015346621979185042|    EFO_0003913|
|6_160591981_T_C|        GCST90480197|fff00145519df7429...|{6, 160591981, 16...|  NULL| 0.01292783387592382|                 NULL|{2, 62371, 160591...|        SuSiE-inf|      NULL|[{VEP, intron_var...|{nfe, 0.712915922...|{0.01534662197918...|{nfe_adj, 0.01534...|{95.5425583988519...|{13493, 606935, 6...|{+, 9.77458737742...|           [EFO_0003914]|  0.489390678709425|0.015346621979185042|    EFO_0003914|
|6_160591981_T_C| FINNGEN_R12_I9_CABG|244a4a5592789b9d6...|{6, 160591981, 16...|  NULL|   0.827289899069155|            0.0611299|{1, 0, 160591981,...|            SuSie|      NULL|[{VEP, intron_var...|          {fin, 1.0}|{0.00790662650602...|{fin_adj, 0.00790...|{181.783562332689...|{13681, 416171, 4...|{+, 13.4827134632...|           [EFO_0003776]| 0.9353089024352683|0.007906626506024096|    EFO_0003776|
|6_160591981_T_C|FINNGEN_R12_E4_LI...|11f1e9e31691de547...|{6, 160591981, 16...|  NULL|   0.383783279065978|            0.0322186|{1, 0, 160591981,...|            SuSie|      NULL|[{VEP, intron_var...|          {fin, 1.0}|{0.00790662650602...|{fin_adj, 0.00790...|{134.284984254033...|{59366, 420066, 4...|{+, 11.5881398099...|       [Orphanet_309005]|0.40566047182591314|0.007906626506024096|Orphanet_309005|
|6_160591981_T_C|        GCST90476000|fa2e6b2b822e6ba23...|{6, 160591981, 16...|  NULL|              0.7273|   0.0994898074743699|{9, 262957, 16042...|             PICS|      NULL|[{VEP, intron_var...|          {nfe, 1.0}|{0.01534662197918...|{nfe_adj, 0.01534...|{44.1769045622582...|{2088, 446675, 44...|{+, 6.64657088747...|           [EFO_0010671]| 0.8386524284181668|0.015346621979185042|    EFO_0010671|
|6_160591981_T_C|FINNGEN_R12_FG_DOAAC|c6bfc950d8a9f8d3b...|{6, 160591981, 16...|  NULL|   0.385076231913214|            0.0542049|{7, 261482, 16033...|            SuSie|      NULL|[{VEP, intron_var...|          {fin, 1.0}|{0.00790662650602...|{fin_adj, 0.00790...|{64.9426477552916...|{29658, 252810, 2...|{+, 8.05870012814...|           [EFO_0004264]|0.39490686546252446|0.007906626506024096|    EFO_0004264|
+---------------+--------------------+--------------------+--------------------+------+--------------------+---------------------+--------------------+-----------------+----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------------+-------------------+--------------------+---------------+

In [29]:
import pandas as pd

# Calculate ratios
ratios = np.maximum(result_df["cluster1_mean"]/result_df["cluster2_mean"], 
                   result_df["cluster2_mean"]/result_df["cluster1_mean"])

print(f"Maximum ratio: {ratios.max()}")
print(f"Mean ratio: {ratios.mean()}")
print(f"Median ratio: {ratios.median()}")

Maximum ratio: 168.6534023283377
Mean ratio: 14.464289782864922
Median ratio: 7.675197417731421

In [30]:
import pandas as pd

# Calculate ratios
ratios = np.minimum(result_df["max_vals2"]/result_df["cluster2_mean"], 
                   result_df["max_vals2"]/result_df["cluster1_mean"])

print(f"Maximum ratio: {ratios.max()}")
print(f"Mean ratio: {ratios.mean()}")
print(f"Median ratio: {ratios.median()}")

Maximum ratio: 4.52507029053172
Mean ratio: 1.4458633767044238
Median ratio: 1.2253036240593245

In [31]:
ratios = np.maximum(result_df["max_vals2"]/result_df["cluster2_mean"], 
                   result_df["max_vals2"]/result_df["cluster1_mean"])
print(f"Maximum ratio: {ratios.max()}")
print(f"Mean ratio: {ratios.mean()}")
print(f"Median ratio: {ratios.median()}")

Maximum ratio: 168.65340232833807
Mean ratio: 19.21939524029146
Median ratio: 11.534427595590818

In [40]:
result_df

,variantId,n_points,bic1,bic2,aic1,aic2,cluster_balance,cluster1_mean,cluster2_mean,max_vals2,maxMAF
0,10_112994312_T_C,16,-41.334811,-52.940810,-42.879988,-56.803754,0.500000,0.004935,0.080194,0.199758,0.293772
1,10_112995025_T_C,11,-37.636370,-37.303100,-38.432160,-39.292576,0.363636,0.068489,0.015255,0.124536,0.293328
2,10_112998590_C_T,52,92.424144,-46.297962,88.521657,-56.054181,0.019231,0.036446,3.896852,3.896852,0.293143
3,10_6052734_C_T,14,-33.607757,-61.393513,-34.885871,-64.588800,0.142857,0.180886,0.019192,0.228003,0.089884
4,11_116778201_G_C,21,15.086185,-4.056822,12.997140,-9.279434,0.047619,0.099144,1.286829,1.286829,0.137992
...,...,...,...,...,...,...,...,...,...,...,...
113,9_133274293_AC_A,12,-88.522244,-87.255805,-89.492057,-89.680338,0.333333,0.002913,0.011640,0.017171,0.202442
114,9_133274295_A_T,15,-31.729255,-60.200595,-33.145356,-63.740846,0.400000,0.005587,0.134466,0.199179,0.194176
115,9_22103814_A_G,12,-45.709796,-50.606293,-46.679609,-53.030826,0.083333,0.027593,0.114795,0.114795,0.490481
116,9_22124505_A_T,16,-95.397682,-103.909833,-96.942859,-107.772776,0.500000,0.003969,0.020996,0.036819,0.498646
117,9_22124745_C_G,19,-98.473954,-110.657731,-100.362832,-115.379926,0.210526,0.006451,0.042205,0.049675,0.497881

In [33]:
vlp_beta_max_high_ps.count()

2153

In [41]:
# Handle NaN values - only compute min if both values are not NaN
result_df['min_cluster_mean'] = result_df.apply(
    lambda row: min(row['cluster1_mean'], row['cluster2_mean']) 
    if pd.notna(row['cluster1_mean']) and pd.notna(row['cluster2_mean']) 
    else np.nan, 
    axis=1
)

In [42]:
result_df

,variantId,n_points,bic1,bic2,aic1,aic2,cluster_balance,cluster1_mean,cluster2_mean,max_vals2,maxMAF,min_cluster_mean
0,10_112994312_T_C,16,-41.334811,-52.940810,-42.879988,-56.803754,0.500000,0.004935,0.080194,0.199758,0.293772,0.004935
1,10_112995025_T_C,11,-37.636370,-37.303100,-38.432160,-39.292576,0.363636,0.068489,0.015255,0.124536,0.293328,0.015255
2,10_112998590_C_T,52,92.424144,-46.297962,88.521657,-56.054181,0.019231,0.036446,3.896852,3.896852,0.293143,0.036446
3,10_6052734_C_T,14,-33.607757,-61.393513,-34.885871,-64.588800,0.142857,0.180886,0.019192,0.228003,0.089884,0.019192
4,11_116778201_G_C,21,15.086185,-4.056822,12.997140,-9.279434,0.047619,0.099144,1.286829,1.286829,0.137992,0.099144
...,...,...,...,...,...,...,...,...,...,...,...,...
113,9_133274293_AC_A,12,-88.522244,-87.255805,-89.492057,-89.680338,0.333333,0.002913,0.011640,0.017171,0.202442,0.002913
114,9_133274295_A_T,15,-31.729255,-60.200595,-33.145356,-63.740846,0.400000,0.005587,0.134466,0.199179,0.194176,0.005587
115,9_22103814_A_G,12,-45.709796,-50.606293,-46.679609,-53.030826,0.083333,0.027593,0.114795,0.114795,0.490481,0.027593
116,9_22124505_A_T,16,-95.397682,-103.909833,-96.942859,-107.772776,0.500000,0.003969,0.020996,0.036819,0.498646,0.003969
117,9_22124745_C_G,19,-98.473954,-110.657731,-100.362832,-115.379926,0.210526,0.006451,0.042205,0.049675,0.497881,0.006451

In [43]:
result_df.to_csv("./data/gmm_fitting_results.csv",index=False)

In [68]:
result_df["cluster_balance"].describe()

count    118.000000
mean       0.222058
std        0.151927
min        0.019231
25%        0.083333
50%        0.197856
75%        0.356061
max        0.500000
Name: cluster_balance, dtype: float64

0      0.080194
1      0.068489
2      3.896852
3      0.180886
4      1.286829
         ...
113    0.011640
114    0.134466
115    0.114795
116    0.020996
117    0.042205
Length: 118, dtype: float64

In [73]:
np.corrcoef(result_df["max_vals2"],np.maximum(result_df["cluster1_mean"],result_df["cluster2_mean"]))

array([[1.        , 0.86235068],
       [0.86235068, 1.        ]])

In [74]:
np.corrcoef(result_df["max_vals2"],np.minimum(result_df["cluster1_mean"],result_df["cluster2_mean"]))

array([[1.        , 0.64212054],
       [0.64212054, 1.        ]])

# Prediction for variants

In [44]:
vlp.printSchema()

root
 |-- studyId: string (nullable = true)
 |-- studyLocusId: string (nullable = true)
 |-- variantId: string (nullable = true)
 |-- variant: struct (nullable = true)
 |    |-- chromosome: string (nullable = true)
 |    |-- start: integer (nullable = true)
 |    |-- end: integer (nullable = true)
 |    |-- type: string (nullable = true)
 |    |-- ref: string (nullable = true)
 |    |-- alt: string (nullable = true)
 |    |-- length: integer (nullable = true)
 |-- geneId: string (nullable = true)
 |-- originalBeta: double (nullable = true)
 |-- originalStandardError: double (nullable = true)
 |-- locusStatistics: struct (nullable = true)
 |    |-- locusSize: integer (nullable = true)
 |    |-- locusLength: integer (nullable = true)
 |    |-- locusStart: integer (nullable = true)
 |    |-- locusEnd: integer (nullable = true)
 |    |-- leadVariantPIP: double (nullable = true)
 |-- finemappingMethod: string (nullable = true)
 |-- isTransQtl: boolean (nullable = true)
 |-- variantEffect: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- method: string (nullable = true)
 |    |    |-- assessment: string (nullable = true)
 |    |    |-- score: float (nullable = true)
 |    |    |-- assessmentFlag: string (nullable = true)
 |    |    |-- targetId: string (nullable = true)
 |    |    |-- normalisedScore: double (nullable = true)
 |-- majorLdPopulation: struct (nullable = true)
 |    |-- ldPopulation: string (nullable = true)
 |    |-- relativeSampleSize: double (nullable = true)
 |-- majorLdPopulationMaf: struct (nullable = true)
 |    |-- value: double (nullable = true)
 |    |-- type: string (nullable = true)
 |-- majorLdPopulationAf: struct (nullable = true)
 |    |-- populationName: string (nullable = true)
 |    |-- alleleFrequency: double (nullable = true)
 |-- variantStatistics: struct (nullable = true)
 |    |-- chi2Stat: double (nullable = true)
 |    |-- pValueMantissa: float (nullable = true)
 |    |-- pValueExponent: integer (nullable = true)
 |    |-- ApproximatedVarianceExplained: double (nullable = true)
 |-- studyStatistics: struct (nullable = true)
 |    |-- nCases: integer (nullable = true)
 |    |-- nControls: integer (nullable = true)
 |    |-- nSamples: integer (nullable = true)
 |    |-- trait: string (nullable = true)
 |    |-- studyType: string (nullable = true)
 |    |-- traitClass: string (nullable = true)
 |    |-- molecularTrait: string (nullable = true)
 |-- rescaledStatistics: struct (nullable = true)
 |    |-- directionOfEffect: string (nullable = true)
 |    |-- zScore: double (nullable = true)
 |    |-- varG: double (nullable = true)
 |    |-- prevalence: double (nullable = true)
 |    |-- estimatedSE: double (nullable = true)
 |    |-- estimatedBeta: double (nullable = true)
 |    |-- majorAlleleEstimatedBeta: double (nullable = true)
 |-- traitFromSourceMappedIds: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- absEstimatedBeta: double (nullable = true)
 |-- maf: double (nullable = true)
 |-- diseaseId: string (nullable = true)

In [45]:
vlp.select("diseaseId").distinct().count()

1403

In [46]:
# Alternative: guarantees exactly one row per diseaseId
window = Window.partitionBy("diseaseId").orderBy(f.desc("studyStatistics.nSamples"))

vlp_max_samples = vlp.withColumn("row_num", f.row_number().over(window)) \
                     .filter(f.col("row_num") == 1) \
                     .drop("row_num")

In [47]:
vlp_max_samples.count()

1403

In [48]:
vlp_max_samples.show(1)

+----------+--------------------+----------------+--------------------+------+------------------+---------------------+--------------------+-----------------+----------+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------------+------------------+-------------------+-----------+
|   studyId|        studyLocusId|       variantId|             variant|geneId|      originalBeta|originalStandardError|     locusStatistics|finemappingMethod|isTransQtl|       variantEffect|majorLdPopulation|majorLdPopulationMaf| majorLdPopulationAf|   variantStatistics|     studyStatistics|  rescaledStatistics|traitFromSourceMappedIds|  absEstimatedBeta|                maf|  diseaseId|
+----------+--------------------+----------------+--------------------+------+------------------+---------------------+--------------------+-----------------+----------+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------------+------------------+-------------------+-----------+
|GCST002643|0cc8fd0b541113b4d...|11_128622844_T_C|{11, 128622844, 1...|  NULL|-0.173953307123438|                 NULL|{8, 5061, 1286194...|             PICS|      NULL|[{VEP, non_coding...|       {nfe, 1.0}|{0.45558692902732...|{nfe_adj, 0.54441...|{42.5189703286698...|{2728, 7758, 1048...|{-, -6.5206572006...|           [EFO_0000096]|0.2060792798322383|0.45558692902732434|EFO_0000096|
+----------+--------------------+----------------+--------------------+------+------------------+---------------------+--------------------+-----------------+----------+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------------+------------------+-------------------+-----------+
only showing top 1 row

In [49]:
diseaseIndex=vlp_max_samples.select(
    "diseaseId",
    "studyId",
    f.col("studyStatistics.nSamples").alias("nSamples"),
    f.col("rescaledStatistics.prevalence").alias("prevalence")
).cache()
diseaseIndex.count()

1403

In [50]:
diseaseIndex.show()

+-------------+--------------------+--------+--------------------+
|    diseaseId|             studyId|nSamples|          prevalence|
+-------------+--------------------+--------+--------------------+
|  EFO_0004254|          GCST010004|   11561| 0.32540437678401524|
|   HP_0000031|        GCST90478623|  409645|0.014807943463242563|
|MONDO_0009061|          GCST002025|    3059| 0.21052631578947367|
|  EFO_0006862|FINNGEN_R12_H8_ME...|  478519|0.007690394738766904|
|   HP_0001892|FINNGEN_R12_BLEEDING|  500348| 0.09798580188189021|
|MONDO_0005129|        GCST90271893|  818138| 0.04068629008798027|
|MONDO_0019640|        GCST90134254|   23859|0.005532503457814661|
|MONDO_0021116|        GCST90454345|  148877|   0.385553174768433|
|  EFO_0000571|        GCST90455519|  143595| 0.09670949545596992|
|  EFO_0000713|        GCST90018923|  626480|0.004622653556378495|
|  EFO_0004795|        GCST90077605|  422570| 0.17966017464562084|
|  EFO_0009485|        GCST90480612|  569533|0.003132390923791949|
|  EFO_0010698|          GCST009959|  364210|0.010919524450179841|
|  EFO_1000243|        GCST90480482|  598183| 0.07535319459095294|
|  EFO_1000244|          GCST009076|    5484| 0.05196936542669584|
|   HP_0000164|        GCST90480845|  614762|0.017019594574811066|
|   HP_0100022|        GCST90481059|  604514| 0.04188654026209484|
|  EFO_0004283|        GCST90018853|  633436|0.006059017801324838|
|  EFO_0021523|        GCST90479758|  534665| 0.17473558209346038|
|   HP_0032072|FINNGEN_R12_M13_B...|  360440|0.008020752413716569|
+-------------+--------------------+--------+--------------------+
only showing top 20 rows

In [51]:
diseaseIndex.toPandas().to_csv("./data/diseaseIndex.csv",index=False)

In [52]:
diseaseIndex=diseaseIndex.toPandas()

In [53]:
dind=diseaseIndex.copy()

In [54]:
def est_ps(beta,maxMAF,dind):
    from scipy.stats import ncx2
    #    (Intercept)            maxMAF         max_vals2  maxMAF:max_vals2  
    #     0.03798          -0.05967           0.05116          -0.14424  
    beta_small2=0.03798-0.05967*maxMAF+0.05116*(beta**2)-0.14424*maxMAF*(beta**2)
    #beta_small2=(beta**2)/11.534427595590818
    #beta_small2=(beta**2)/50
    dind["lin_beta2"]=beta_small2*((dind["prevalence"]*(1-dind["prevalence"]))**2)
    dind["r2"]=dind["lin_beta2"]*2*maxMAF*(1-maxMAF)
    dind["NCP"]=dind["r2"]*dind["nSamples"]
    p = ncx2.sf(32.84125, df=1, nc=dind["NCP"])
    obs_plei=sum(p)
    return obs_plei

In [57]:
beta=0.5
maxMAF=0.05
est_ps(beta,maxMAF,diseaseIndex)

125.98168901981343

In [59]:
varint_ps=pd.read_csv("/Users/yt4/Desktop/PSs/variants_with_fitness_scores.csv")

In [60]:
varint_ps["maxMAF"]

0        0.044689
1        0.393147
2        0.059694
3        0.356079
4        0.374352
           ...
40701    0.232871
40702    0.116953
40703    0.490541
40704    0.013248
40705    0.422718
Name: maxMAF, Length: 40706, dtype: float64

In [61]:
# Apply est_ps function to each row
varint_ps['predicted_pleiotropy'] = varint_ps.apply(
    lambda row: est_ps(row['maxAbsBeta'], row['maxMAF'], diseaseIndex.copy()), 
    axis=1
)

In [62]:
varint_ps

,variantId,nonEURProportion,minAbsBeta,maxAbsBeta,minCoefficientDetermination,maxCoefficientDetermination,minEffectiveSampleSize,maxEffectiveSampleSize,minVarG,maxVarG,...,gerpNormalised,vepScore,fullModelDiseasesResid,biologicalFactorsDiseasesResid,statisticalFactorsDiseasesResid,sum_beta_variant,weighted_sum_beta_variant,count_rows,max_maf_variant,predicted_pleiotropy
0,10_100231378_T_A,1.000000,0.241801,0.241801,0.001248,0.001248,3.431020e+04,3.431020e+04,0.085383,0.085383,...,0.439000,0.10,0.073335,-0.360528,0.043313,0.241801,0.178117,1,0.044689,97.261355
1,10_100660841_T_G,1.000000,0.017299,0.017299,0.000036,0.000036,1.424218e+06,1.424218e+06,0.477165,0.477165,...,0.000000,0.00,-0.780858,-0.386125,-0.740000,0.017299,0.009946,1,0.393147,172.521840
2,10_100835542_T_A,0.000000,0.064451,0.064451,0.000117,0.000117,2.602102e+05,2.602102e+05,0.112262,0.112262,...,0.192667,0.00,-0.229954,-0.178591,-0.410599,0.064451,0.038091,1,0.059694,114.449621
3,10_102219168_T_A,1.000000,0.035843,0.035843,0.000147,0.000147,1.600105e+05,1.600105e+05,0.458574,0.458574,...,0.105000,0.00,-0.245786,-0.386458,-0.303356,0.035843,0.021488,1,0.356079,182.864322
4,10_102380845_G_A,1.000000,0.043559,0.043559,0.000222,0.000222,2.282206e+05,2.282206e+05,0.468425,0.468425,...,0.172917,0.10,-0.283624,-0.420798,-0.292639,0.043559,0.022696,1,0.374352,178.158499
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40701,20_62357358_T_C,0.545455,0.035874,0.187506,0.000115,0.002549,1.374824e+04,3.012031e+05,0.289961,0.357285,...,0.000000,0.10,7.968783,8.587843,7.943598,1.244138,0.803380,10,0.232871,197.140371
40702,8_116618444_A_C,0.578947,0.055764,1.070688,0.000111,0.041044,1.848986e+03,4.739002e+05,0.143213,0.206550,...,0.910625,0.00,3.089929,9.280612,6.145730,0.599560,0.324768,12,0.116953,253.752933
40703,8_127401060_G_T,0.723404,0.029230,0.503670,0.000107,0.031699,1.848986e+03,5.218187e+05,0.187027,0.499821,...,0.900000,0.00,12.063827,16.698949,13.095563,2.479346,1.681755,19,0.490541,52.131894
40704,17_1880615_C_T,0.000000,0.207145,0.581642,0.000280,0.002211,1.886671e+04,3.679493e+05,0.026145,0.026145,...,0.810000,0.66,10.310941,10.302351,11.482443,4.829464,3.309419,13,0.013248,34.196148
40705,5_1287079_G_A,0.724138,0.037894,0.541976,0.000175,0.034282,2.452663e+03,3.552841e+05,0.397975,0.488055,...,0.247667,0.10,11.439524,13.884896,11.946399,2.772006,1.855576,16,0.422718,135.780789

In [63]:
# Fix the typo and use numpy.corrcoef or pandas.corr
np.corrcoef(varint_ps["predicted_pleiotropy"], varint_ps["uniqueDiseases"])[0, 1]

nan

In [64]:
varint_ps["uniqueDiseases"].describe()

count    40706.000000
mean         1.479610
std          1.544425
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         85.000000
Name: uniqueDiseases, dtype: float64

In [65]:
varint_ps["predicted_pleiotropy"].describe()

count    40668.000000
mean       160.678140
std         44.291446
min          0.000042
25%        144.182358
50%        175.462136
75%        191.386520
max        432.543384
Name: predicted_pleiotropy, dtype: float64

In [ ]:
varint_ps.to_csv("/Users/yt4/Desktop/PSs/variants_with_fitness_scores_pred.csv",index=False)

25/10/17 17:10:06 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 514060 ms exceeds timeout 120000 ms
25/10/17 17:10:06 WARN SparkContext: Killing executors is not supported by current scheduler.
25/10/17 17:10:09 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@192.168.0.224:55782
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:316)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:307)
	at scala.concurrent.impl.Promise.transformWith(Promise.scala:40)
	at scala.concurrent.impl.Promise.transformWith$(Promise.scala:38)
	at scala.concurrent.impl.Promise$DefaultPromise.transformWith(Promise.scala:187)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.asyncSetupEndpointRefByURI(NettyRpcEnv.scala:150)
	... 17 more
25/10/17 17:10:09 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:642)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1223)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:295)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@192.168.0.224:55782
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:316)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:307)
	at scala.concurrent.impl.Promise.transformWith(Promise.scala:40)
	at scala.concurrent.impl.Promise.transformWith$(Promise.scala:38)
	at scala.concurrent.impl.Promise$DefaultPromise.transformWith(Promise.scala:187)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.asyncSetupEndpointRefByURI(NettyRpcEnv.scala:150)
	... 17 more
25/10/17 17:25:29 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@192.168.0.224:55782
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.trySuccess(Promise.scala:94)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:94)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:225)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:239)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:238)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.Promise.success(Promise.scala:86)
	at scala.concurrent.Promise.success$(Promise.scala:86)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:187)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
25/10/17 17:25:29 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:642)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1223)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:295)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@192.168.0.224:55782
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)