In [1]:
!gcloud auth application-default login

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=xmuAxe4OhUBgFTvoHgKflkUl21rpcD&access_type=offline&code_challenge=QPHf7E0xpT7i5Qh-qGN0RyhLJxYW6LPzZ0czk7_V9qg&code_challenge_method=S256


Credentials saved to file: [/Users/yt4/.config/gcloud/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).

Quota project "open-targets-genetics-dev" was added to ADC which can be used by Google client libraries for billing and quota. Note that some services may still bill the project owning the resource.


Updates are available for some Google Cloud CLI components.  To install them,
please run:
  $ gcloud components update

In [1]:
import os

import hail as hl
import numpy as np
import pyspark.sql.functions as f
from pyspark.sql import DataFrame

from gentropy.common.session import Session
from gentropy.dataset.study_index import StudyIndex
from gentropy.dataset.summary_statistics import SummaryStatistics
from gentropy.dataset.study_locus import StudyLocus
from gentropy.susie_finemapper import SusieFineMapperStep

In [2]:
hail_dir = os.path.dirname(hl.__file__)
session = Session(hail_home=hail_dir, start_hail=True, extended_spark_conf={"spark.driver.memory": "12g","spark.kryoserializer.buffer.max": "500m","spark.driver.maxResultSize":"2g"})

24/09/18 12:29:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
pip-installed Hail requires additional configuration options in Spark referring
  to the path to the Hail Python module directory HAIL_DIR,
  e.g. /path/to/python/site-packages/hail:
    spark.jars=HAIL_DIR/backend/hail-all-spark.jar
    spark.driver.extraClassPath=HAIL_DIR/backend/hail-all-spark.jar
    spark.executor.extraClassPath=./hail-all-spark.jarRunning on Apache Spark version 3.3.4
SparkUI available at http://mib118093s.internal.sanger.ac.uk:4040
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.127-bb535cd096c5
LOGGING: writing to /dev/null

----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 60301)
Traceback (most recent call last):
  File "/Users/yt4/.pyenv/versions/3.10.8/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/yt4/.pyenv/versions/3.10.8/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/Users/yt4/.pyenv/versions/3.10.8/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/yt4/.pyenv/versions/3.10.8/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/Users/yt4/Library/Caches/pypoetry/virtualenvs/gentropy-krNFZEZg-py3.10/lib/python3.10/site-packages/pyspark/accumulators.py", line 281, in handle
    poll(accum_updates)
  File "/Users/yt4/Library/Caches/pypoetry/virtualenvs/gentropy-krNFZEZg-py3.10/lib/python3.10/site-packages/pyspark/accumulators.py", line 253, in poll
    if func():
  File "/Users/yt4/Library/Caches/pypoetry/virtualenvs/gentropy-krNFZEZg-py3.10/lib/python3.10/site-packages/pyspark/accumulators.py", line 257, in accum_updates
    num_updates = read_int(self.rfile)
  File "/Users/yt4/Library/Caches/pypoetry/virtualenvs/gentropy-krNFZEZg-py3.10/lib/python3.10/site-packages/pyspark/serializers.py", line 595, in read_int
    raise EOFError
EOFError
----------------------------------------

In [2]:
hail_dir = os.path.dirname(hl.__file__)
# Paths to required JAR files
hadoop_aws_jar = "/Users/yt4/Library/Caches/pypoetry/virtualenvs/gentropy-krNFZEZg-py3.10/lib/python3.10/site-packages/pyspark/jars/hadoop-aws-3.2.0.jar"
aws_sdk_jar = "/Users/yt4/Library/Caches/pypoetry/virtualenvs/gentropy-krNFZEZg-py3.10/lib/python3.10/site-packages/pyspark/jars/aws-java-sdk-bundle-1.11.375.jar"


session = Session(hail_home=hail_dir, start_hail=True,
extended_spark_conf={"spark.driver.memory": "12g",
                     "spark.kryoserializer.buffer.max": "500m",
                     "spark.hadoop.fs.s3a.path.style.access":"true",
                     "spark.driver.maxResultSize":"2g",
                     "spark.hadoop.fs.s3a.impl":"org.apache.hadoop.fs.s3a.S3AFileSystem",
                     "spark.hadoop.fs.s3a.endpoint":"s3.amazonaws.com",
                     "spark.jars":f"{hail_dir}/backend/hail-all-spark.jar,{hadoop_aws_jar},{aws_sdk_jar}",
                     "spark.driver.extraClassPath":f"{hail_dir}/backend/hail-all-spark.jar:{hadoop_aws_jar}:{aws_sdk_jar}",
                     "spark.executor.extraClassPath":f"{hail_dir}/backend/hail-all-spark.jar:{hadoop_aws_jar}:{aws_sdk_jar}",
                     "spark.serializer":"org.apache.spark.serializer.KryoSerializer",
                     "spark.kryo.registrator":"is.hail.kryo.HailKryoRegistrator"
                     })

24/09/13 13:52:53 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
pip-installed Hail requires additional configuration options in Spark referring
  to the path to the Hail Python module directory HAIL_DIR,
  e.g. /path/to/python/site-packages/hail:
    spark.jars=HAIL_DIR/backend/hail-all-spark.jar
    spark.driver.extraClassPath=HAIL_DIR/backend/hail-all-spark.jar
    spark.executor.extraClassPath=./hail-all-spark.jarRunning on Apache Spark version 3.3.4
SparkUI available at http://mib118093s:4040
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.127-bb535cd096c5
LOGGING: writing to /dev/null

In [3]:
df2=StudyLocus.from_parquet(session,"temp_fiels/nan_locus2")
df2=df2.df
df2.show()

+--------------------+---------------+----------+--------+------+------------+----------+------+--------------+--------------+-------------------------------+-------------+-------------------+---------------+-----------------+----------------+------------------+------------+-----------+----------+---------+----------+-----+--------------------+
|        studyLocusId|      variantId|chromosome|position|region|     studyId|      beta|zScore|pValueMantissa|pValueExponent|effectAlleleFrequencyFromSource|standardError|subStudyDescription|qualityControls|finemappingMethod|credibleSetIndex|credibleSetlog10BF|purityMeanR2|purityMinR2|locusStart| locusEnd|sampleSize|ldSet|               locus|
+--------------------+---------------+----------+--------+------+------------+----------+------+--------------+--------------+-------------------------------+-------------+-------------------+---------------+-----------------+----------------+------------------+------------+-----------+----------+---------+----------+-----+--------------------+
|-1012754541153341722|15_42986528_G_A|        15|42986528|  null|GCST90002322| -0.047893|  null|          1.96|           -14|                       0.025536|     0.006253|               null|             []|             null|            null|              null|        null|       null|  42236528| 43736528|      null| null|[{null, null, nul...|
| -103533209966396235| 7_99988175_C_G|         7|99988175|  null|GCST90002391|-0.0219766|  null|           3.3|           -23|                       0.563708|   0.00221467|               null|             []|             null|            null|              null|        null|       null|  99238175|100738175|      null| null|[{null, null, nul...|
|-1011231071050974680|11_46875702_G_C|        11|46875702|  null|GCST90025982|-0.0333561|  null|           1.6|           -70|                       0.655032|   0.00199044|               null|             []|             null|            null|              null|        null|       null|  46125702| 47625702|      null| null|[{null, null, nul...|
|-1001937030930569227| 3_47263902_G_A|         3|47263902|  null|GCST90025970| 0.0662625|  null|           3.4|           -70|                      0.0703513|   0.00392126|               null|             []|             null|            null|              null|        null|       null|  46513902| 48013902|      null| null|[{null, null, nul...|
|-1035767924310985877|15_77323689_A_G|        15|77323689|  null|GCST90013985| 0.0158569|  null|         7.971|           -11|                           null|    0.0024391|               null|           null|             null|            null|              null|        null|       null|  76246850| 77644713|      null| null|[{null, null, nul...|
|-1028210081609642911|20_34077942_A_G|        20|34077942|  null|GCST90029034|-0.0688555|  null|           2.2|          -282|                       0.897557|   0.00196273|               null|             []|             null|            null|              null|        null|       null|  33327942| 34827942|    344229| null|[{null, null, nul...|
|-1025465871319241012| 2_31585905_T_A|         2|31585905|  null|GCST90274493| -0.117794|  null|         2.002|           -11|                           0.56|    0.0175657|               null|           null|             null|            null|              null|        null|       null|  31287076| 32726815|      null| null|[{null, null, nul...|
|-1018262251190305220|16_67187541_G_C|        16|67187541|  null|GCST90013976|-0.0473038|  null|         7.331|            -9|                           null|   0.00817956|               null|             []|             null|            null|              null|        null|       null|  66437541| 67937541|      null| null|[{null, null, nul...|
|-1010313196581703077| 3_50831189_A_T|         3|50831189|  null|GCST90014008|-0.0160444|  null|         6.129|           -14|                           null|   0.00213775|               null|             []|             null|            null|              null|        null|       null|  50081189| 51581189|      null| null|[{null, null, nul...|
|-1030347428451315180|11_48669641_T_C|        11|48669641|  null|GCST90310294|   -0.4367|  null|         1.299|           -32|                         0.1401|       0.0367|               null|             []|             null|            null|              null|        null|       null|  47919641| 49419641|    992947| null|[{null, null, nul...|
|-1035576011340159380| 7_99735325_T_G|         7|99735325|  null|GCST90266034|  0.777649|  null|          6.19|           -12|                           0.06|     0.113109|               null|           null|             null|            null|              null|        null|       null|  99061103|100496354|      null| null|[{null, null, nul...|
|-1041429612550728944| 3_49273698_C_G|         3|49273698|  null|GCST90094828| -0.049522|  null|          1.53|            -9|                         0.5019|     0.008195|               null|           null|             null|            null|              null|        null|       null|  48585869| 49956597|    159571| null|[{null, null, nul...|
|-1039176771908555670| 7_66144830_A_G|         7|66144830|  null|GCST90103634|     0.002|  null|         7.744|           -13|                         0.4609|       3.0E-4|               null|             []|             null|            null|              null|        null|       null|  65394830| 66894830|   1002980| null|[{null, null, nul...|
+--------------------+---------------+----------+--------+------+------------+----------+------+--------------+--------------+-------------------------------+-------------+-------------------+---------------+-----------------+----------------+------------------+------------+-----------+----------+---------+----------+-----+--------------------+

In [4]:
si=StudyIndex.from_parquet(session,"gs://genetics_etl_python_playground/releases/24.06/study_index/gwas_catalog")

In [5]:
result_logging = SusieFineMapperStep.susie_finemapper_one_sl_row_v4_ss_gathered_boundaries_ldinterface(
session=session,
study_locus_row=df2.first(),
study_index=si,
max_causal_snps=10,
primary_signal_pval_threshold=1,
secondary_signal_pval_threshold=1,
purity_mean_r2_threshold=0,
purity_min_r2_threshold=0,
cs_lbf_thr=2,
sum_pips=0.99,
susie_est_tausq=False,
run_carma=False,
carma_tau=0.15,
run_sumstat_imputation=False,
carma_time_limit=60000,
imputed_r2_threshold=0.8,
ld_score_threshold=5,
)

In [6]:
result_logging["study_locus"].df.drop("locus").show(truncate=False)

+----------------+--------------------+------------+--------------------+---------------+----------+--------+-----------------+------------------+--------------------+---------------------+-------------------+--------------+--------------+
|credibleSetIndex|studyLocusId        |studyId     |region              |variantId      |chromosome|position|finemappingMethod|credibleSetlog10BF|purityMeanR2        |purityMinR2          |zScore             |pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+---------------+----------+--------+-----------------+------------------+--------------------+---------------------+-------------------+--------------+--------------+
|1               |-7473856272000447250|GCST90002322|15:42236528-43736528|15_43735687_T_C|15        |43735687|SuSiE-inf        |21.95817139892995 |0.013796527716166032|9.145083358635376E-20|-10.635212888377445|4.8932896     |-26           |
|2               |310803910236169473  |GCST90002322|15:42236528-43736528|15_43465641_C_G|15        |43465641|SuSiE-inf        |1.1010303118652438|0.013796527716166032|9.145083358635376E-20|-1.219721767594108 |4.492961      |-1            |
+----------------+--------------------+------------+--------------------+---------------+----------+--------+-----------------+------------------+--------------------+---------------------+-------------------+--------------+--------------+

In [7]:
result_logging["study_locus"].df.show()

+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+--------------------+--------------------+-------------------+--------------+--------------+
|credibleSetIndex|        studyLocusId|     studyId|              region|               locus|      variantId|chromosome|position|finemappingMethod|credibleSetlog10BF|        purityMeanR2|         purityMinR2|             zScore|pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+--------------------+--------------------+-------------------+--------------+--------------+
|               1|-7473856272000447250|GCST90002322|15:42236528-43736528|[{15_43735687_T_C...|15_43735687_T_C|        15|43735687|        SuSiE-inf| 21.95817139892995|0.013796527716166032|9.145083358635376...|-10.635212888377445|     4.8932896|           -26|
|               2|  310803910236169473|GCST90002322|15:42236528-43736528|[{15_43465641_C_G...|15_43465641_C_G|        15|43465641|        SuSiE-inf|1.1010303118652438|0.013796527716166032|9.145083358635376...| -1.219721767594108|      4.492961|            -1|
+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+--------------------+--------------------+-------------------+--------------+--------------+

In [8]:
result_logging["log"]

,N_gwas_before_dedupl,N_gwas,N_ld,N_overlap,N_outliers,N_imputed,N_final_to_fm,elapsed_time
0,8541,8541,8541,8541,0,0,8541,158.257764

In [11]:
result_logging["log"]

,N_gwas_before_dedupl,N_gwas,N_ld,N_overlap,N_outliers,N_imputed,N_final_to_fm,elapsed_time
0,8541,8541,8541,8541,18,0,8523,979.829959

In [13]:
si.df.filter(f.col("studyId")=="GCST90002322").show()

+------------+---------+---------+--------------------+------------------------+----------+------+---------------------+--------+--------------------+----------------------+---------------+------------------+----------------------------------+--------------------+--------------------+------+---------+--------+--------------------+---------------------+--------------------+------------------+---------------+-------------+--------------------+-----------+
|     studyId|projectId|studyType|     traitFromSource|traitFromSourceMappedIds|diseaseIds|geneId|biosampleFromSourceId|pubmedId|    publicationTitle|publicationFirstAuthor|publicationDate|publicationJournal|backgroundTraitFromSourceMappedIds|backgroundDiseaseIds|   initialSampleSize|nCases|nControls|nSamples|             cohorts|ldPopulationStructure|    discoverySamples|replicationSamples|qualityControls|analysisFlags|summarystatsLocation|hasSumstats|
+------------+---------+---------+--------------------+------------------------+----------+------+---------------------+--------+--------------------+----------------------+---------------+------------------+----------------------------------+--------------------+--------------------+------+---------+--------+--------------------+---------------------+--------------------+------------------+---------------+-------------+--------------------+-----------+
|GCST90002322|     GCST|     gwas|Mean corpuscular ...|           [EFO_0004528]|      null|  null|                 null|32888493|Trans-ethnic and ...|               Chen MH|     2020-09-01|              Cell|                              null|                null|486,823 European ...|     0|        0|  486823|[Airwave, BioME, ...|         [{nfe, 1.0}]|[{486823, European}]|                []|             []|           []|ftp://ftp.ebi.ac....|       true|
+------------+---------+---------+--------------------+------------------------+----------+------+---------------------+--------+--------------------+----------------------+---------------+------------------+----------------------------------+--------------------+--------------------+------+---------+--------+--------------------+---------------------+--------------------+------------------+---------------+-------------+--------------------+-----------+

In [5]:
df2=StudyLocus.from_parquet(session,"gs://genetics-portal-dev-analysis/yt4/TMP/nan_locus2")
df2.df.show()
rows = df2.df.collect()

+--------------------+---------------+----------+--------+------+------------+----------+------+--------------+--------------+-------------------------------+-------------+-------------------+---------------+-----------------+----------------+------------------+------------+-----------+----------+---------+----------+-----+--------------------+
|        studyLocusId|      variantId|chromosome|position|region|     studyId|      beta|zScore|pValueMantissa|pValueExponent|effectAlleleFrequencyFromSource|standardError|subStudyDescription|qualityControls|finemappingMethod|credibleSetIndex|credibleSetlog10BF|purityMeanR2|purityMinR2|locusStart| locusEnd|sampleSize|ldSet|               locus|
+--------------------+---------------+----------+--------+------+------------+----------+------+--------------+--------------+-------------------------------+-------------+-------------------+---------------+-----------------+----------------+------------------+------------+-----------+----------+---------+----------+-----+--------------------+
|-1012754541153341722|15_42986528_G_A|        15|42986528|  null|GCST90002322| -0.047893|  null|          1.96|           -14|                       0.025536|     0.006253|               null|             []|             null|            null|              null|        null|       null|  42236528| 43736528|      null| null|[{null, null, nul...|
| -103533209966396235| 7_99988175_C_G|         7|99988175|  null|GCST90002391|-0.0219766|  null|           3.3|           -23|                       0.563708|   0.00221467|               null|             []|             null|            null|              null|        null|       null|  99238175|100738175|      null| null|[{null, null, nul...|
|-1011231071050974680|11_46875702_G_C|        11|46875702|  null|GCST90025982|-0.0333561|  null|           1.6|           -70|                       0.655032|   0.00199044|               null|             []|             null|            null|              null|        null|       null|  46125702| 47625702|      null| null|[{null, null, nul...|
|-1001937030930569227| 3_47263902_G_A|         3|47263902|  null|GCST90025970| 0.0662625|  null|           3.4|           -70|                      0.0703513|   0.00392126|               null|             []|             null|            null|              null|        null|       null|  46513902| 48013902|      null| null|[{null, null, nul...|
|-1035767924310985877|15_77323689_A_G|        15|77323689|  null|GCST90013985| 0.0158569|  null|         7.971|           -11|                           null|    0.0024391|               null|           null|             null|            null|              null|        null|       null|  76246850| 77644713|      null| null|[{null, null, nul...|
|-1028210081609642911|20_34077942_A_G|        20|34077942|  null|GCST90029034|-0.0688555|  null|           2.2|          -282|                       0.897557|   0.00196273|               null|             []|             null|            null|              null|        null|       null|  33327942| 34827942|    344229| null|[{null, null, nul...|
|-1025465871319241012| 2_31585905_T_A|         2|31585905|  null|GCST90274493| -0.117794|  null|         2.002|           -11|                           0.56|    0.0175657|               null|           null|             null|            null|              null|        null|       null|  31287076| 32726815|      null| null|[{null, null, nul...|
|-1018262251190305220|16_67187541_G_C|        16|67187541|  null|GCST90013976|-0.0473038|  null|         7.331|            -9|                           null|   0.00817956|               null|             []|             null|            null|              null|        null|       null|  66437541| 67937541|      null| null|[{null, null, nul...|
|-1010313196581703077| 3_50831189_A_T|         3|50831189|  null|GCST90014008|-0.0160444|  null|         6.129|           -14|                           null|   0.00213775|               null|             []|             null|            null|              null|        null|       null|  50081189| 51581189|      null| null|[{null, null, nul...|
|-1030347428451315180|11_48669641_T_C|        11|48669641|  null|GCST90310294|   -0.4367|  null|         1.299|           -32|                         0.1401|       0.0367|               null|             []|             null|            null|              null|        null|       null|  47919641| 49419641|    992947| null|[{null, null, nul...|
|-1035576011340159380| 7_99735325_T_G|         7|99735325|  null|GCST90266034|  0.777649|  null|          6.19|           -12|                           0.06|     0.113109|               null|           null|             null|            null|              null|        null|       null|  99061103|100496354|      null| null|[{null, null, nul...|
|-1041429612550728944| 3_49273698_C_G|         3|49273698|  null|GCST90094828| -0.049522|  null|          1.53|            -9|                         0.5019|     0.008195|               null|           null|             null|            null|              null|        null|       null|  48585869| 49956597|    159571| null|[{null, null, nul...|
|-1039176771908555670| 7_66144830_A_G|         7|66144830|  null|GCST90103634|     0.002|  null|         7.744|           -13|                         0.4609|       3.0E-4|               null|             []|             null|            null|              null|        null|       null|  65394830| 66894830|   1002980| null|[{null, null, nul...|
+--------------------+---------------+----------+--------+------+------------+----------+------+--------------+--------------+-------------------------------+-------------+-------------------+---------------+-----------------+----------------+------------------+------------+-----------+----------+---------+----------+-----+--------------------+

In [12]:
results_logging = []
for row in rows[0:1]:
    result = SusieFineMapperStep.susie_finemapper_one_sl_row_v4_ss_gathered_boundaries_ldinterface(
    session=session,
    study_locus_row=row,
    study_index=si,
    max_causal_snps=10,
    primary_signal_pval_threshold=1,
    secondary_signal_pval_threshold=1,
    purity_mean_r2_threshold=0,
    purity_min_r2_threshold=0,
    cs_lbf_thr=2,
    sum_pips=0.99,
    susie_est_tausq=True,
    run_carma=True,
    carma_tau=0.04,
    run_sumstat_imputation=False,
    carma_time_limit=6000,
    imputed_r2_threshold=0.8,
    ld_score_threshold=5,
    )
    results_logging.append(result)

In [13]:
results_logging[0]["log"]

,N_gwas_before_dedupl,N_gwas,N_ld,N_overlap,N_outliers,N_imputed,N_final_to_fm,elapsed_time
0,8541,8541,8541,8541,1,0,8540,1373.646585

In [14]:
results_logging[0]["study_locus"].df.show(truncate=False)

+----------------+--------------------+------------+--------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------------+------------------+-------------------+--------------+--------------+
|credibleSetIndex|studyLocusId        |studyId     |region              |locus                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |variantId      |chromosome|position|finemappingMethod|credibleSetlog10BF|purityMeanR2      |purityMinR2       |zScore             |pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------------+------------------+-------------------+--------------+--------------+
|1               |-7473856272000447250|GCST90002322|15:42236528-43736528|[{15_43735687_T_C, 0.5107292928096012, 42.47663417099278, -0.0332469384856811}, {15_43735849_C_T, 0.29618768943798174, 41.93178782014505, -0.03296340430333603}, {15_43434427_A_C, 0.10059976070794159, 40.85194435984352, -0.03275341673535164}, {15_43528519_C_T, 0.07167971347403905, 40.51300225219511, -0.03251625758580826}, {15_43464986_T_C, 0.009324851310439329, 38.47347750097096, -0.03174283046590366}, {15_43658501_A_T, 0.007010224450372896, 38.18816419996145, -0.031579266501243326}]|15_43735687_T_C|15        |43735687|SuSiE-inf        |14.807719192014154|0.9520821427121849|0.9182543075387543|-10.635212888377445|4.8932896     |-26           |
+----------------+--------------------+------------+--------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------------+------------------+-------------------+--------------+--------------+

In [15]:
results_logging[0]["study_locus"].df.select("locus").show(truncate=False)

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|locus                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|[{15_43735687_T_C, 0.5107292928096012, 42.47663417099278, -0.0332469384856811}, {15_43735849_C_T, 0.29618768943798174, 41.93178782014505, -0.03296340430333603}, {15_43434427_A_C, 0.10059976070794159, 40.85194435984352, -0.03275341673535164}, {15_43528519_C_T, 0.07167971347403905, 40.51300225219511, -0.03251625758580826}, {15_43464986_T_C, 0.009324851310439329, 38.47347750097096, -0.03174283046590366}, {15_43658501_A_T, 0.007010224450372896, 38.18816419996145, -0.031579266501243326}]|
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

In [7]:
results_logging[0]["log"]

,N_gwas_before_dedupl,N_gwas,N_ld,N_overlap,N_outliers,N_imputed,N_final_to_fm,elapsed_time
0,3087,3087,3087,3087,0,0,3087,41.781145

In [8]:
results_logging[1]["log"]

,N_gwas_before_dedupl,N_gwas,N_ld,N_overlap,N_outliers,N_imputed,N_final_to_fm,elapsed_time
0,3498,3498,3498,3498,0,0,3498,26.811943

In [9]:
results_logging[2]["log"]

,N_gwas_before_dedupl,N_gwas,N_ld,N_overlap,N_outliers,N_imputed,N_final_to_fm,elapsed_time
0,438,438,438,438,0,0,438,31.828747

In [10]:
results_logging[0]["study_locus"].df.show()

+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+--------------+--------------+
|credibleSetIndex|        studyLocusId|     studyId|              region|               locus|      variantId|chromosome|position|finemappingMethod|credibleSetlog10BF|purityMeanR2|purityMinR2|             zScore|pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+--------------+--------------+
|               7|-6085008223147579656|GCST90002322|15:42236528-43736528|[{15_43658501_A_T...|15_43658501_A_T|        15|43658501|        SuSiE-inf| 50.31954122113802|         1.0|        1.0|-10.207749251850686|     5.4626327|           -24|
|               6|-6022298121111655759|GCST90002322|15:42236528-43736528|[{15_43481838_C_G...|15_43481838_C_G|        15|43481838|        SuSiE-inf| 50.94492987516624|         1.0|        1.0| -6.797022181707687|      9.362975|           -11|
|              10|-5327263775886500084|GCST90002322|15:42236528-43736528|[{15_43297635_A_G...|15_43297635_A_G|        15|43297635|        SuSiE-inf| 7.059770574099266|         1.0|        1.0| -5.653412648716343|      6.357559|            -8|
|               3|-2632831884834309933|GCST90002322|15:42236528-43736528|[{15_43510514_A_C...|15_43510514_A_C|        15|43510514|        SuSiE-inf| 579.6904757148425|         1.0|        1.0| 0.4236150708364402|     1.4884351|            -1|
|               8|-2273701730318034092|GCST90002322|15:42236528-43736528|[{15_43331199_T_G...|15_43331199_T_G|        15|43331199|        SuSiE-inf|  43.3363661157673|         1.0|        1.0| -7.412101593625498|      8.044181|           -13|
|               9| -983329156187741650|GCST90002322|15:42236528-43736528|[{15_42520524_T_G...|15_42520524_T_G|        15|42520524|        SuSiE-inf| 7.259124396651924|         1.0|        1.0| 1.9200000000000002|     1.8228915|            -2|
|               1|  923949982765216720|GCST90002322|15:42236528-43736528|[{15_43520398_G_C...|15_43520398_G_C|        15|43520398|        SuSiE-inf| 799.4030991589394|         1.0|        1.0|-6.0429371499688855|     6.6079173|            -9|
|               2| 3381653650770367723|GCST90002322|15:42236528-43736528|[{15_43521189_T_C...|15_43521189_T_C|        15|43521189|        SuSiE-inf| 745.9731020473508|         1.0|        1.0|-1.3934996402014872|      6.117377|            -1|
|               4| 6356608581566170109|GCST90002322|15:42236528-43736528|[{15_43509840_A_C...|15_43509840_A_C|        15|43509840|        SuSiE-inf|243.27219212815967|         1.0|        1.0| -6.140373470701867|     1.2146581|           -10|
|               5| 8858076177993068537|GCST90002322|15:42236528-43736528|[{15_43718994_T_C...|15_43718994_T_C|        15|43718994|        SuSiE-inf| 95.05538815524126|         1.0|        1.0|-1.8206816387013196|     1.4565525|            -2|
+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+--------------+--------------+

In [11]:
results_logging[1]["study_locus"].df.show()

+----------------+--------------------+------------+--------------------+--------------------+----------------+----------+---------+-----------------+------------------+------------+-----------+-------------------+--------------+--------------+
|credibleSetIndex|        studyLocusId|     studyId|              region|               locus|       variantId|chromosome| position|finemappingMethod|credibleSetlog10BF|purityMeanR2|purityMinR2|             zScore|pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+--------------------+----------------+----------+---------+-----------------+------------------+------------+-----------+-------------------+--------------+--------------+
|               6|-6245663969000871348|GCST90002391|7:99238175-100738175|[{7_99922677_C_CA...| 7_99922677_C_CA|         7| 99922677|        SuSiE-inf| 82.62157172286402|         1.0|        1.0| -5.191237951965294|      4.786969|            -7|
|              10|-4069378103230918336|GCST90002391|7:99238175-100738175|[{7_99696236_C_CT...| 7_99696236_C_CT|         7| 99696236|        SuSiE-inf|20.895737428072156|         1.0|        1.0|  2.808565481352992|     2.0095348|            -3|
|               5|-3991276074013514490|GCST90002391|7:99238175-100738175|[{7_100718429_C_G...| 7_100718429_C_G|         7|100718429|        SuSiE-inf| 85.40877012879567|         1.0|        1.0|-3.5407009878419453|      2.505854|            -4|
|               3|-2667457217629430909|GCST90002391|7:99238175-100738175|[{7_100638579_G_A...| 7_100638579_G_A|         7|100638579|        SuSiE-inf| 154.6461089444019|         1.0|        1.0| 22.032925673701083|     7.1797585|          -107|
|               1|-2344209115497115353|GCST90002391|7:99238175-100738175|[{7_99970285_C_T,...|  7_99970285_C_T|         7| 99970285|        SuSiE-inf| 211.2053189370907|         1.0|        1.0| -7.650038456812317|     4.9771247|           -14|
|               9|-1043583293921163803|GCST90002391|7:99238175-100738175|[{7_100621008_C_T...| 7_100621008_C_T|         7|100621008|        SuSiE-inf|27.831579463302216|         1.0|        1.0| 11.436719354482149|     3.6489232|           -30|
|               7| 4031220581531326506|GCST90002391|7:99238175-100738175|[{7_99613384_A_G,...|  7_99613384_A_G|         7| 99613384|        SuSiE-inf|  49.8326852857553|         1.0|        1.0|  9.024065216371504|      5.517667|           -19|
|               2| 4573296555111304122|GCST90002391|7:99238175-100738175|[{7_99969408_T_TA...| 7_99969408_T_TA|         7| 99969408|        SuSiE-inf|178.85404130608862|         1.0|        1.0|   5.18049084777481|      4.518696|            -7|
|               8| 5180506266232118271|GCST90002391|7:99238175-100738175|[{7_100717534_C_C...|7_100717534_C_CT|         7|100717534|        SuSiE-inf| 39.76262332653022|         1.0|        1.0|-10.770290838783989|     2.1030638|           -27|
+----------------+--------------------+------------+--------------------+--------------------+----------------+----------+---------+-----------------+------------------+------------+-----------+-------------------+--------------+--------------+

In [12]:
results_logging[2]["study_locus"].df.show()

+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+-------------------+-----------+-------------------+--------------+--------------+
|credibleSetIndex|        studyLocusId|     studyId|              region|               locus|      variantId|chromosome|position|finemappingMethod|credibleSetlog10BF|       purityMeanR2|purityMinR2|             zScore|pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+-------------------+-----------+-------------------+--------------+--------------+
|               1|-8772012305519000727|GCST90025982|11:46125702-47625702|[{11_46877220_T_C...|11_46877220_T_C|        11|46877220|        SuSiE-inf| 47.48953954222523|0.08418389634350017|        0.0|-16.776436426479382|      2.755014|           -63|
|               3|-3871230980544521946|GCST90025982|11:46125702-47625702|[{11_47565900_C_T...|11_47565900_C_T|        11|47565900|        SuSiE-inf| 4.238975060107001|0.08418389634350017|        0.0| -6.084134352541226|      8.538079|            -9|
|               4| 2246485394363609996|GCST90025982|11:46125702-47625702|[{11_46317543_C_T...|11_46317543_C_T|        11|46317543|        SuSiE-inf|1.6091716686898396|0.08418389634350017|        0.0| -6.800355426309625|      9.582091|           -11|
|               2| 7654308655369240319|GCST90025982|11:46125702-47625702|[{11_46864526_A_T...|11_46864526_A_T|        11|46864526|        SuSiE-inf| 5.136019675013526|0.08418389634350017|        0.0|  -7.94979613405312|      5.352783|           -15|
+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+-------------------+-----------+-------------------+--------------+--------------+

In [7]:
results_logging[0]["log"]

,N_gwas_before_dedupl,N_gwas,N_ld,N_overlap,N_outliers,N_imputed,N_final_to_fm,elapsed_time
0,8541,8541,8541,8541,0,0,8541,174.38088

In [8]:
results_logging[1]["log"]

,N_gwas_before_dedupl,N_gwas,N_ld,N_overlap,N_outliers,N_imputed,N_final_to_fm,elapsed_time
0,7983,7983,7983,7983,0,0,7983,95.302479

In [11]:
results_logging[2]["log"]

,N_gwas_before_dedupl,N_gwas,N_ld,N_overlap,N_outliers,N_imputed,N_final_to_fm,elapsed_time
0,899,899,899,899,0,0,899,13.053128

In [15]:
results_logging[0]["study_locus"].df.show()

+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+--------------------+--------------------+-------------------+--------------+--------------+
|credibleSetIndex|        studyLocusId|     studyId|              region|               locus|      variantId|chromosome|position|finemappingMethod|credibleSetlog10BF|        purityMeanR2|         purityMinR2|             zScore|pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+--------------------+--------------------+-------------------+--------------+--------------+
|               1|-7473856272000447250|GCST90002322|15:42236528-43736528|[{15_43735687_T_C...|15_43735687_T_C|        15|43735687|        SuSiE-inf| 21.95817139892995|0.013796527716166032|9.145083358635376...|-10.635212888377445|     4.8932896|           -26|
|               2|  310803910236169473|GCST90002322|15:42236528-43736528|[{15_43465641_C_G...|15_43465641_C_G|        15|43465641|        SuSiE-inf|1.1010303118652438|0.013796527716166032|9.145083358635376...| -1.219721767594108|      4.492961|            -1|
+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+--------------------+--------------------+-------------------+--------------+--------------+

In [16]:
results_logging[1]["study_locus"].df.show()

+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+---------+-----------------+------------------+------------------+--------------------+-------------------+--------------+--------------+
|credibleSetIndex|        studyLocusId|     studyId|              region|               locus|      variantId|chromosome| position|finemappingMethod|credibleSetlog10BF|      purityMeanR2|         purityMinR2|             zScore|pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+---------+-----------------+------------------+------------------+--------------------+-------------------+--------------+--------------+
|               1|-3977928675613916210|GCST90002391|7:99238175-100738175|[{7_100638347_C_A...|7_100638347_C_A|         7|100638347|        SuSiE-inf| 93.89790847468976|0.0792526005370054|2.042255683123205...| 22.033881794513025|      7.332933|          -107|
|               2|-1043583293921163803|GCST90002391|7:99238175-100738175|[{7_100621008_C_T...|7_100621008_C_T|         7|100621008|        SuSiE-inf|11.401836440829248|0.0792526005370054|2.042255683123205...| 11.436719354482149|     3.6489232|           -30|
|               3| 5122693100489028247|GCST90002391|7:99238175-100738175|[{7_100484854_G_A...|7_100484854_G_A|         7|100484854|        SuSiE-inf|2.1609597683757436|0.0792526005370054|2.042255683123205...| 3.3062785641389714|      1.057708|            -4|
|               4| 9133581251835403635|GCST90002391|7:99238175-100738175|[{7_99659678_G_A,...| 7_99659678_G_A|         7| 99659678|        SuSiE-inf|1.6329348587002714|0.0792526005370054|2.042255683123205...|-3.1738737410574345|      6.648092|            -3|
+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+---------+-----------------+------------------+------------------+--------------------+-------------------+--------------+--------------+

In [17]:
results_logging[2]["study_locus"].df.show()

+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+------------------+------------------+-------------------+--------------+--------------+
|credibleSetIndex|        studyLocusId|     studyId|              region|               locus|      variantId|chromosome|position|finemappingMethod|credibleSetlog10BF|      purityMeanR2|       purityMinR2|             zScore|pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+------------------+------------------+-------------------+--------------+--------------+
|               1|-8772012305519000727|GCST90025982|11:46125702-47625702|[{11_46877220_T_C...|11_46877220_T_C|        11|46877220|        SuSiE-inf| 53.29022453468571|0.6215246472296444|0.1808890200535872|-16.776436426479382|      2.755014|           -63|
|               3|-3871230980544521946|GCST90025982|11:46125702-47625702|[{11_47565900_C_T...|11_47565900_C_T|        11|47565900|        SuSiE-inf|3.6251639244849616|0.6215246472296444|0.1808890200535872| -6.084134352541226|      8.538079|            -9|
|               2| 7654308655369240319|GCST90025982|11:46125702-47625702|[{11_46864526_A_T...|11_46864526_A_T|        11|46864526|        SuSiE-inf|  3.69793807787237|0.6215246472296444|0.1808890200535872|  -7.94979613405312|      5.352783|           -15|
+----------------+--------------------+------------+--------------------+--------------------+---------------+----------+--------+-----------------+------------------+------------------+------------------+-------------------+--------------+--------------+