In [7]:
!gcloud auth application-default login

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=SBCoFVnfzo1qAX3JklPq5i4gJIWJe7&access_type=offline&code_challenge=uHpYaXY7OEvLge3NcX97aJic7bfIq61TiFhtfNqBeOs&code_challenge_method=S256


Credentials saved to file: [/Users/yt4/.config/gcloud/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).

Quota project "open-targets-genetics-dev" was added to ADC which can be used by Google client libraries for billing and quota. Note that some services may still bill the project owning the resource.

In [9]:
!gcloud auth login

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=32555940559.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&state=m3UDMbvUt5BcGTpsDdYYwgUIwpkNLo&access_type=offline&code_challenge=jVehlml18X1cYrzJharmWWR5BPlKfO98EbS_-5hgFO8&code_challenge_method=S256


You are now logged in as [yt4@sanger.ac.uk].
Your current project is [open-targets-genetics-dev].  You can change this setting by running:
  $ gcloud config set project PROJECT_ID

In [3]:
!gcloud config set project open-targets-genetics-dev

Updated property [core/project].

In [1]:
import os

import hail as hl
import numpy as np
import pyspark.sql.functions as f
from pyspark.sql import DataFrame

from gentropy.common.session import Session
from gentropy.dataset.study_index import StudyIndex
from gentropy.dataset.summary_statistics import SummaryStatistics
from gentropy.dataset.study_locus import StudyLocus
from gentropy.susie_finemapper import SusieFineMapperStep

In [2]:
hail_dir = os.path.dirname(hl.__file__)
session = Session(hail_home=hail_dir, start_hail=True, extended_spark_conf={
    "spark.driver.memory": "12g","spark.kryoserializer.buffer.max": "500m","spark.driver.maxResultSize":"2g",
    'spark.hadoop.fs.gs.requester.pays.buckets': 'requester-pays-bucket1,requester-pays-bucket2',
    'spark.hadoop.fs.gs.requester.pays.project.id': 'open-targets-genetics-dev',
    "spark.hadoop.fs.gs.requester.pays.mode":"AUTO"})

24/10/16 11:53:42 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
pip-installed Hail requires additional configuration options in Spark referring
  to the path to the Hail Python module directory HAIL_DIR,
  e.g. /path/to/python/site-packages/hail:
    spark.jars=HAIL_DIR/backend/hail-all-spark.jar
    spark.driver.extraClassPath=HAIL_DIR/backend/hail-all-spark.jar
    spark.executor.extraClassPath=./hail-all-spark.jarRunning on Apache Spark version 3.3.4
SparkUI available at http://mib118093s.internal.sanger.ac.uk:4040
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.127-bb535cd096c5
LOGGING: writing to /dev/null

In [3]:
from __future__ import annotations

from pyspark.sql.types import DoubleType, LongType, StringType, StructField, StructType

from gentropy.common.session import Session
from gentropy.datasource.gwas_catalog.study_index import StudyIndexGWASCatalogParser
from gentropy.datasource.gwas_catalog.study_index_ot_curation import (
    StudyIndexGWASCatalogOTCuration,
)

In [4]:
catalog_study_files=["gs://gwas_catalog_inputs/gwas_catalog_download_studies.tsv"]
catalog_ancestry_files=["gs://gwas_catalog_inputs/gwas_catalog_download_ancestries.tsv"]
gwas_catalog_study_curation_file="gs://genetics-portal-dev-analysis/yt4/gwas_catalog_curation/20241004_output_curation.tsv"
sumstats_qc_path="gs://genetics-portal-dev-analysis/yt4/20241015_GwasCatQCLogs"
harmonised_studies_index_path=None

In [5]:
# Core Study Index Generation:
study_index = StudyIndexGWASCatalogParser.from_source(
    session.spark.read.csv(list(catalog_study_files), sep="\t", header=True),
    session.spark.read.csv(list(catalog_ancestry_files), sep="\t", header=True),
)

# Annotate with curation if provided:
if gwas_catalog_study_curation_file:
    if gwas_catalog_study_curation_file.endswith(
        ".tsv"
    ) | gwas_catalog_study_curation_file.endswith(".tsv"):
        gwas_catalog_study_curation = StudyIndexGWASCatalogOTCuration.from_csv(
            session, gwas_catalog_study_curation_file
        )
    elif gwas_catalog_study_curation_file.startswith("http"):
        gwas_catalog_study_curation = StudyIndexGWASCatalogOTCuration.from_url(
            session, gwas_catalog_study_curation_file
        )
    else:
        raise ValueError(
            "Only CSV/TSV files or URLs are accepted as curation file."
        )
    study_index = study_index.annotate_from_study_curation(
        gwas_catalog_study_curation
    )

# Annotate with has summary statistics if provided:
if harmonised_studies_index_path:
    harmonised_studies = session.spark.read.csv(
        harmonised_studies_index_path, header=False
    )
    study_index = study_index.annotate_sumstats_info(harmonised_studies)

# Annotate with sumstats QC if provided:
if sumstats_qc_path:
    schema = StructType(
        [
            StructField("studyId", StringType(), True),
            StructField("mean_beta", DoubleType(), True),
            StructField("mean_diff_pz", DoubleType(), True),
            StructField("se_diff_pz", DoubleType(), True),
            StructField("gc_lambda", DoubleType(), True),
            StructField("n_variants", LongType(), True),
            StructField("n_variants_sig", LongType(), True),
        ]
    )
    sumstats_qc = session.spark.read.schema(schema).parquet(
        sumstats_qc_path, recursiveFileLookup=True
    )
    study_index = study_index.annotate_sumstats_qc(sumstats_qc)

In [12]:
study_index.df.show(2,truncate=False)

+----------+----------------------+------------------------+------+----------------------------------------------------------------+---------+---------+------------------+----------------------------------------------------------------------------------------------------+--------+--------------------------+-------+----------------------------------+-------------+--------+---------------------+-------------------+---------+---------------+---------------+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+-----------+
|studyId   |publicationFirstAuthor|traitFromSourceMappedIds|nCases|initialSampleSize                                               |nControls|projectId|publicationJournal|publicationTitle                                                                                    |nSamples|traitFromSource           |cohorts|backgroundTraitFromSourceMappedIds|analysisFlags|pubmedId|ldPopulationStructure|replicationSamples |studyType|publicationDate|qualityControls|discoverySamples                 |sumStatQCValues                                                                                                                                               |sumStatQCPerformed|hasSumstats|
+----------+----------------------+------------------------+------+----------------------------------------------------------------+---------+---------+------------------+----------------------------------------------------------------------------------------------------+--------+--------------------------+-------+----------------------------------+-------------+--------+---------------------+-------------------+---------+---------------+---------------+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+-----------+
|GCST000569|Saxena R              |[EFO_0004307]           |0     |15,234 individuals                                              |0        |GCST     |Nat Genet         |Genetic variation in GIPR influences the glucose and insulin responses to an oral glucose challenge.|15234   |Two-hour glucose challenge|null   |null                              |[]           |20081857|[{nfe, 1.0}]         |[{European, 30620}]|gwas     |2010-01-17     |[]             |[{European, 7617}, {Other, 7617}]|[{mean_beta, -1.863105E-4}, {mean_diff_pz, -2.662145E-4}, {se_diff_pz, 0.015551462}, {gc_lambda, 1.0218483}, {n_variants, 2392760.0}, {n_variants_sig, 2.0}]  |true              |true       |
|GCST001791|Kottgen A             |[EFO_0004531]           |0     |49,825 European ancestry males, 60,522 European ancestry females|0        |GCST     |Nat Genet         |Genome-wide association analyses identify 18 new loci associated with serum urate concentrations.   |110347  |Urate levels              |null   |null                              |[]           |23263486|[{nfe, 1.0}]         |[{European, 32813}]|gwas     |2012-12-23     |[]             |[{European, 110347}]             |[{mean_beta, -3.57746E-5}, {mean_diff_pz, -0.038851246}, {se_diff_pz, 0.060762085}, {gc_lambda, 1.1686996}, {n_variants, 2430146.0}, {n_variants_sig, 2010.0}]|true              |true       |
+----------+----------------------+------------------------+------+----------------------------------------------------------------+---------+---------+------------------+----------------------------------------------------------------------------------------------------+--------+--------------------------+-------+----------------------------------+-------------+--------+---------------------+-------------------+---------+---------------+---------------+---------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+-----------+
only showing top 2 rows

In [23]:
df=study_index.df
df.count()

52441

In [26]:
df = df.join(
    sumstats_qc, how="left", on="studyId"
)

In [28]:
df = df.drop(
    "mean_beta",
    "mean_diff_pz",
    "se_diff_pz",
    "gc_lambda",
    "n_variants",
    "n_variants_sig",
)

In [29]:
df.printSchema()

root
 |-- studyId: string (nullable = false)
 |-- publicationFirstAuthor: string (nullable = true)
 |-- traitFromSourceMappedIds: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- nCases: integer (nullable = true)
 |-- initialSampleSize: string (nullable = true)
 |-- nControls: integer (nullable = true)
 |-- projectId: string (nullable = false)
 |-- publicationJournal: string (nullable = true)
 |-- publicationTitle: string (nullable = true)
 |-- nSamples: integer (nullable = true)
 |-- traitFromSource: string (nullable = false)
 |-- cohorts: array (nullable = true)
 |    |-- element: string (containsNull = false)
 |-- backgroundTraitFromSourceMappedIds: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- analysisFlags: array (nullable = true)
 |    |-- element: string (containsNull = false)
 |-- pubmedId: string (nullable = true)
 |-- ldPopulationStructure: array (nullable = true)
 |    |-- element: struct (containsNull = false)
 |    |    |-- ldPopulation: string (nullable = true)
 |    |    |-- relativeSampleSize: double (nullable = true)
 |-- replicationSamples: array (nullable = true)
 |    |-- element: struct (containsNull = false)
 |    |    |-- ancestry: string (nullable = true)
 |    |    |-- sampleSize: integer (nullable = true)
 |-- studyType: string (nullable = false)
 |-- publicationDate: string (nullable = true)
 |-- qualityControls: array (nullable = true)
 |    |-- element: string (containsNull = false)
 |-- discoverySamples: array (nullable = true)
 |    |-- element: struct (containsNull = false)
 |    |    |-- ancestry: string (nullable = true)
 |    |    |-- sampleSize: integer (nullable = false)
 |-- sumStatQCValues: array (nullable = false)
 |    |-- element: struct (containsNull = false)
 |    |    |-- QCCheckName: string (nullable = false)
 |    |    |-- QCCheckValue: float (nullable = true)
 |-- sumStatQCPerformed: boolean (nullable = false)
 |-- hasSumstats: boolean (nullable = true)

In [ ]:
df_exploded = study_index.df.withColumn("analysisFlags_e", f.explode("analysisFlags"))

# Group by the exploded elements and count the occurrences
df_counts = df_exploded.groupBy("analysisFlags_e").count()
df_counts.show(truncate=False)

In [11]:
# Group by the exploded elements and count the occurrences
df_counts = study_index.df.groupBy("studyType").count()
df_counts.show(truncate=False)

+----------+-----+
|studyType |count|
+----------+-----+
|gwas      |34140|
|pQTL      |16736|
|Microbiome|1565 |
+----------+-----+

In [7]:
study_index.df.printSchema()

root
 |-- studyId: string (nullable = false)
 |-- publicationFirstAuthor: string (nullable = true)
 |-- traitFromSourceMappedIds: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- nCases: integer (nullable = true)
 |-- initialSampleSize: string (nullable = true)
 |-- nControls: integer (nullable = true)
 |-- projectId: string (nullable = false)
 |-- publicationJournal: string (nullable = true)
 |-- publicationTitle: string (nullable = true)
 |-- nSamples: integer (nullable = true)
 |-- traitFromSource: string (nullable = false)
 |-- cohorts: array (nullable = true)
 |    |-- element: string (containsNull = false)
 |-- backgroundTraitFromSourceMappedIds: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- analysisFlags: array (nullable = true)
 |    |-- element: string (containsNull = false)
 |-- pubmedId: string (nullable = true)
 |-- ldPopulationStructure: array (nullable = true)
 |    |-- element: struct (containsNull = false)
 |    |    |-- ldPopulation: string (nullable = true)
 |    |    |-- relativeSampleSize: double (nullable = true)
 |-- replicationSamples: array (nullable = true)
 |    |-- element: struct (containsNull = false)
 |    |    |-- ancestry: string (nullable = true)
 |    |    |-- sampleSize: integer (nullable = true)
 |-- studyType: string (nullable = false)
 |-- publicationDate: string (nullable = true)
 |-- qualityControls: array (nullable = true)
 |    |-- element: string (containsNull = false)
 |-- discoverySamples: array (nullable = true)
 |    |-- element: struct (containsNull = false)
 |    |    |-- ancestry: string (nullable = true)
 |    |    |-- sampleSize: integer (nullable = false)
 |-- sumStatQCValues: array (nullable = false)
 |    |-- element: struct (containsNull = false)
 |    |    |-- QCCheckName: string (nullable = false)
 |    |    |-- QCCheckValue: float (nullable = true)
 |-- sumStatQCPerformed: boolean (nullable = false)
 |-- hasSumstats: boolean (nullable = true)

In [7]:
study_index.df.filter(f.col("sumStatQCPerformed")==True).count()

52441

In [5]:
session.spark.read.csv(catalog_study_files, sep="\t", header=True)

DataFrame[DATE ADDED TO CATALOG: string, PUBMED ID: string, FIRST AUTHOR: string, DATE: string, JOURNAL: string, LINK: string, STUDY: string, DISEASE/TRAIT: string, INITIAL SAMPLE SIZE: string, REPLICATION SAMPLE SIZE: string, PLATFORM [SNPS PASSING QC]: string, ASSOCIATION COUNT: string, MAPPED_TRAIT: string, MAPPED_TRAIT_URI: string, STUDY ACCESSION: string, GENOTYPING TECHNOLOGY: string, SUBMISSION DATE: string, STATISTICAL MODEL: string, BACKGROUND TRAIT: string, MAPPED BACKGROUND TRAIT: string, MAPPED BACKGROUND TRAIT URI: string, COHORT: string, FULL SUMMARY STATISTICS: string, SUMMARY STATS LOCATION: string]

In [6]:
# Core Study Index Generation:
study_index = StudyIndexGWASCatalogParser.from_source(
    session.spark.read.csv(list(catalog_study_files), sep="\t", header=True),
    session.spark.read.csv(list(catalog_ancestry_files), sep="\t", header=True),
)

In [7]:
study_index.df.show()

+------------+---------+---------+--------+----------------------+---------------+--------------------+--------------------+--------------------+--------------------+------------------------+----------------------------------+--------------------+--------------------+---------------------+--------------------+------+---------+--------+
|     studyId|projectId|studyType|pubmedId|publicationFirstAuthor|publicationDate|  publicationJournal|    publicationTitle|     traitFromSource|   initialSampleSize|traitFromSourceMappedIds|backgroundTraitFromSourceMappedIds|             cohorts|    discoverySamples|ldPopulationStructure|  replicationSamples|nCases|nControls|nSamples|
+------------+---------+---------+--------+----------------------+---------------+--------------------+--------------------+--------------------+--------------------+------------------------+----------------------------------+--------------------+--------------------+---------------------+--------------------+------+---------+--------+
|  GCST004746|     GCST|     gwas|28604730|              McKay JD|     2017-06-12|           Nat Genet|Large-scale assoc...|Small cell lung c...|2,664 European an...|           [EFO_0000702]|                              null|                null| [{European, 24108}]|         [{nfe, 1.0}]|                  []|  2664|    21444|   24108|
|  GCST005499|     GCST|     gwas|29084231|              Davis JP|     2017-10-30|          PLoS Genet|Common, low-frequ...|Phospholipid leve...|8,372 Finnish anc...|    [EFO_0004612, EFO...|                              null|                null|  [{European, 8372}]|         [{nfe, 1.0}]|                  []|     0|        0|    8372|
|  GCST005501|     GCST|     gwas|29084231|              Davis JP|     2017-10-30|          PLoS Genet|Common, low-frequ...|Cholesterol ester...|8,372 Finnish anc...|    [EFO_0004612, EFO...|                              null|                null|  [{European, 8372}]|         [{nfe, 1.0}]|                  []|     0|        0|    8372|
|  GCST005505|     GCST|     gwas|29084231|              Davis JP|     2017-10-30|          PLoS Genet|Common, low-frequ...|Total cholesterol...|8,372 Finnish anc...|           [EFO_0004612]|                              null|                null|  [{European, 8372}]|         [{nfe, 1.0}]|                  []|     0|        0|    8372|
|  GCST007578|     GCST|     gwas|30339177|               Shane B|     2018-10-19|      Am J Clin Nutr|The 677C→T varian...|Plasma homocystei...|2,232 Irish ances...|           [EFO_0004578]|                              null|                null|  [{European, 2232}]|         [{nfe, 1.0}]|                  []|     0|        0|    2232|
|  GCST009160|     GCST|     gwas|23696881|               Wood AR|     2013-05-16|            PLoS One|Imputation of var...|   Carotenoid levels|up to 1,200 Europ...|           [EFO_0004737]|                              null|                null|  [{European, 1200}]|         [{nfe, 1.0}]|                  []|     0|        0|    1200|
|  GCST009163|     GCST|     gwas|23696881|               Wood AR|     2013-05-16|            PLoS One|Imputation of var...|Hormone measurements|up to 1,200 Europ...|           [EFO_0004730]|                              null|                null|  [{European, 1200}]|         [{nfe, 1.0}]|                  []|     0|        0|    1200|
|  GCST011794|     GCST|     gwas|33235445|                Lee YJ|     2020-11-17|Int J Chron Obstr...|A Genome-Wide Ass...|Early chronic obs...|130 Korean ancest...|           [EFO_0000341]|                              null|                null|[{East Asian, 3608}]|         [{eas, 1.0}]|                  []|   130|     3478|    3608|
|GCST90079246|     GCST|     gwas|34662886|            Backman JD|     2021-10-18|              Nature|Exome sequencing ...|Cognitive functio...|86,002 European a...|           [EFO_0008354]|                              null|               [UKB]|[{European, 139370}]|         [{nfe, 1.0}]|                  []| 86002|    53368|  139370|
|GCST90087611|     GCST|     gwas|35078996|          Gudjonsson A|     2022-01-25|          Nat Commun|A genome-wide ass...|Serum levels of p...|5,357 Icelandic a...|           [EFO_0007937]|                              null|              [AGES]|  [{European, 5357}]|         [{nfe, 1.0}]|                  []|     0|        0|    5357|
|GCST90088472|     GCST|     gwas|35078996|          Gudjonsson A|     2022-01-25|          Nat Commun|A genome-wide ass...|Serum levels of p...|5,353 Icelandic a...|           [EFO_0007937]|                              null|              [AGES]|  [{European, 5353}]|         [{nfe, 1.0}]|                  []|     0|        0|    5353|
|GCST90088473|     GCST|     gwas|35078996|          Gudjonsson A|     2022-01-25|          Nat Commun|A genome-wide ass...|Serum levels of p...|5,368 Icelandic a...|           [EFO_0007937]|                              null|              [AGES]|  [{European, 5368}]|         [{nfe, 1.0}]|                  []|     0|        0|    5368|
|GCST90089143|     GCST|     gwas|35078996|          Gudjonsson A|     2022-01-25|          Nat Commun|A genome-wide ass...|Serum levels of p...|5,368 Icelandic a...|           [EFO_0007937]|                              null|              [AGES]|  [{European, 5368}]|         [{nfe, 1.0}]|                  []|     0|        0|    5368|
|GCST90089345|     GCST|     gwas|35078996|          Gudjonsson A|     2022-01-25|          Nat Commun|A genome-wide ass...|Serum levels of p...|5,365 Icelandic a...|           [EFO_0007937]|                              null|              [AGES]|  [{European, 5365}]|         [{nfe, 1.0}]|                  []|     0|        0|    5365|
|GCST90089477|     GCST|     gwas|35078996|          Gudjonsson A|     2022-01-25|          Nat Commun|A genome-wide ass...|Serum levels of p...|5,342 Icelandic a...|           [EFO_0007937]|                              null|              [AGES]|  [{European, 5342}]|         [{nfe, 1.0}]|                  []|     0|        0|    5342|
|GCST90093173|     GCST|     gwas|34734193|                 Sun D|     2020-10-31|             HGG Adv|Multi-Ancestry Ge...|Pulse pressure x ...|12,800 European a...|    [EFO_0005230, EFO...|                              null|[AGES, ARIC, CARD...| [{European, 12800}]|         [{nfe, 1.0}]| [{European, 21322}]|     0|        0|   12800|
|GCST90093177|     GCST|     gwas|34734193|                 Sun D|     2020-10-31|             HGG Adv|Multi-Ancestry Ge...|Mean arterial pre...|43,335 European a...|    [EFO_0006340, MON...|                              null|[AGES, ARIC, CARD...| [{European, 43335}]|         [{nfe, 1.0}]| [{European, 42700}]|     0|        0|   43335|
|GCST90093182|     GCST|     gwas|34734193|                 Sun D|     2020-10-31|             HGG Adv|Multi-Ancestry Ge...|Diastolic blood p...|12,800 European a...|    [EFO_0005230, EFO...|                              null|[AGES, ARIC, CARD...| [{European, 12800}]|         [{nfe, 1.0}]| [{European, 21322}]|     0|        0|   12800|
|GCST90100641|     GCST|     gwas|28240269|               Suhre K|     2017-02-27|          Nat Commun|Connecting geneti...|Alpha-L-iduronida...|997 European ance...|           [EFO_0020139]|                              null|              [KORA]|   [{European, 997}]|         [{nfe, 1.0}]|[{South Asian, As...|     0|        0|     997|
|GCST90101599|     GCST|     gwas|28240269|               Suhre K|     2017-02-27|          Nat Commun|Connecting geneti...|Thymidine kinase,...|997 European ance...|           [EFO_0020773]|                              null|              [KORA]|   [{European, 997}]|         [{nfe, 1.0}]|[{South Asian, As...|     0|        0|     997|
+------------+---------+---------+--------+----------------------+---------------+--------------------+--------------------+--------------------+--------------------+------------------------+----------------------------------+--------------------+--------------------+---------------------+--------------------+------+---------+--------+
only showing top 20 rows

In [9]:
gwas_catalog_study_curation = StudyIndexGWASCatalogOTCuration.from_csv(
            session, gwas_catalog_study_curation_file
        )

In [10]:
gwas_catalog_study_curation.show(2)

+----------+---------+-------------+---------------+---------+
|   studyId|studyType|analysisFlags|qualityControls|isCurated|
+----------+---------+-------------+---------------+---------+
|GCST000028|     null|           []|             []|     true|
|GCST000392|     null|           []|             []|     true|
+----------+---------+-------------+---------------+---------+
only showing top 2 rows

In [11]:
# Annotate with curation if provided:
if gwas_catalog_study_curation_file:
    if (gwas_catalog_study_curation_file.endswith(".tsv") | gwas_catalog_study_curation_file.endswith(".tsv")):
        gwas_catalog_study_curation = StudyIndexGWASCatalogOTCuration.from_csv(
            session, gwas_catalog_study_curation_file
        )
    elif gwas_catalog_study_curation_file.startswith("http"):
        gwas_catalog_study_curation = StudyIndexGWASCatalogOTCuration.from_url(
            session, gwas_catalog_study_curation_file,
        )
    else:
        raise ValueError(
            "Only CSV files or URLs are accepted as curation file."
        )
    study_index = study_index.annotate_from_study_curation(
        gwas_catalog_study_curation
    )

In [12]:
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, LongType

# Annotate with sumstats QC if provided:
if sumstats_qc_path:
    schema = StructType([
        StructField("studyId", StringType(), True),
        StructField("mean_beta", DoubleType(), True),
        StructField("mean_diff_pz", DoubleType(), True),
        StructField("se_diff_pz", DoubleType(), True),
        StructField("gc_lambda", DoubleType(), True),
        StructField("n_variants", LongType(), True),
        StructField("n_variants_sig", LongType(), True)
    ])
    sumstats_qc = session.spark.read.schema(schema).parquet(sumstats_qc_path,recursiveFileLookup=True)

In [13]:
sumstats_qc.show(2)

+------------+--------------------+--------------------+--------------------+------------------+----------+--------------+
|     studyId|           mean_beta|        mean_diff_pz|          se_diff_pz|         gc_lambda|n_variants|n_variants_sig|
+------------+--------------------+--------------------+--------------------+------------------+----------+--------------+
|GCST90000047|-4.13776584488885...|0.001489360466501...| 0.06464638468525331| 1.356996071104317|  16298931|         17113|
|GCST90000448|4.499510274945693E-4|-1.67316909891496...|6.299456349660006E-5|1.0123659198314245|   7887487|             0|
+------------+--------------------+--------------------+--------------------+------------------+----------+--------------+
only showing top 2 rows

In [42]:
from gentropy.common.spark_helpers import convert_from_wide_to_long


cols = [c for c in sumstats_qc.columns if c != "studyId"]


melted_df = convert_from_wide_to_long(sumstats_qc, id_vars = ["studyId"], value_vars= cols, var_name="QCCheckName", value_name="QCCheckValue")
qc_df = melted_df.groupBy("studyId").agg(f.collect_list(f.struct(f.col("QCCheckName"), f.col("QCCheckValue"))).alias("sumStatQCValues")).withColumn("sumStatQCPerformed", f.lit(True))
qc_df.show(truncate=False)

+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
|studyId   |sumStatQCValues                                                                                                                                                    |sumStatQCPerformed|
+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
|GCST000569|[{mean_beta, -1.863105E-4}, {mean_diff_pz, -2.662145E-4}, {se_diff_pz, 0.015551462}, {gc_lambda, 1.0218483}, {n_variants, 2392760.0}, {n_variants_sig, 2.0}]       |true              |
|GCST000758|[{mean_beta, 1.5269937E-4}, {mean_diff_pz, 0.0034558668}, {se_diff_pz, 0.15163296}, {gc_lambda, 1.0103346}, {n_variants, 2626961.0}, {n_variants_sig, 1562.0}]     |true              |
|GCST000998|[{mean_beta, 3.5235167E-5}, {mean_diff_pz, -9.978134E-8}, {se_diff_pz, 4.271737E-5}, {gc_lambda, 1.0961434}, {n_variants, 2414914.0}, {n_variants_sig, 147.0}]     |true              |
|GCST001791|[{mean_beta, -3.57746E-5}, {mean_diff_pz, -0.038851246}, {se_diff_pz, 0.060762085}, {gc_lambda, 1.1686996}, {n_variants, 2430146.0}, {n_variants_sig, 2010.0}]     |true              |
|GCST002221|[{mean_beta, 7.823449E-5}, {mean_diff_pz, -0.0315406}, {se_diff_pz, 0.18033175}, {gc_lambda, 1.1281898}, {n_variants, 2418436.0}, {n_variants_sig, 3560.0}]        |true              |
|GCST002920|[{mean_beta, -2.1290523E-5}, {mean_diff_pz, -1.7085275E-5}, {se_diff_pz, 0.0044061407}, {gc_lambda, 1.0535316}, {n_variants, 6897111.0}, {n_variants_sig, 1.0}]    |true              |
|GCST002964|[{mean_beta, -7.779062E-5}, {mean_diff_pz, -4.129334E-5}, {se_diff_pz, 0.0074132173}, {gc_lambda, 1.0164057}, {n_variants, 2474864.0}, {n_variants_sig, 1.0}]      |true              |
|GCST003045|[{mean_beta, -6.6959945E-4}, {mean_diff_pz, 3.432134E-7}, {se_diff_pz, 4.7485268E-5}, {gc_lambda, 2.565568}, {n_variants, 110942.0}, {n_variants_sig, 2780.0}]     |true              |
|GCST003129|[{mean_beta, 0.0013804991}, {mean_diff_pz, -1.5603987E-7}, {se_diff_pz, 4.0252682E-5}, {gc_lambda, 1.0614264}, {n_variants, 1124241.0}, {n_variants_sig, 659.0}]   |true              |
|GCST003156|[{mean_beta, -0.0015407328}, {mean_diff_pz, -1.3757018E-7}, {se_diff_pz, 4.2451546E-5}, {gc_lambda, 1.4088843}, {n_variants, 7071163.0}, {n_variants_sig, 14317.0}]|true              |
|GCST003374|[{mean_beta, 0.0018355009}, {mean_diff_pz, -8.248277E-4}, {se_diff_pz, 0.01885436}, {gc_lambda, 1.0389501}, {n_variants, 2174599.0}, {n_variants_sig, 99.0}]       |true              |
|GCST003375|[{mean_beta, 1.061561E-5}, {mean_diff_pz, -0.0056775007}, {se_diff_pz, 0.025166702}, {gc_lambda, 1.0770736}, {n_variants, 2154723.0}, {n_variants_sig, 238.0}]     |true              |
|GCST003392|[{mean_beta, -4.237055E-5}, {mean_diff_pz, 4.203674E-5}, {se_diff_pz, 0.0040411744}, {gc_lambda, 1.0830083}, {n_variants, 9436090.0}, {n_variants_sig, 0.0}]       |true              |
|GCST003738|[{mean_beta, 0.0018494558}, {mean_diff_pz, -3.4224487E-7}, {se_diff_pz, 9.736061E-4}, {gc_lambda, 1.0440618}, {n_variants, 1.1818789E7}, {n_variants_sig, 98.0}]   |true              |
|GCST003766|[{mean_beta, -2.982135E-5}, {mean_diff_pz, -0.023756089}, {se_diff_pz, 0.1023071}, {gc_lambda, 1.3297205}, {n_variants, 2058391.0}, {n_variants_sig, 0.0}]         |true              |
|GCST003769|[{mean_beta, -1.1298199E-5}, {mean_diff_pz, 0.0025227773}, {se_diff_pz, 0.08497671}, {gc_lambda, 1.2364365}, {n_variants, 6019632.0}, {n_variants_sig, 2.0}]       |true              |
|GCST004075|[{mean_beta, 1.2420938E-5}, {mean_diff_pz, -1.3591623E-4}, {se_diff_pz, 0.016031772}, {gc_lambda, 1.0997084}, {n_variants, 1.114952E7}, {n_variants_sig, 1810.0}]  |true              |
|GCST004132|[{mean_beta, 0.0010059315}, {mean_diff_pz, -2.1648705E-6}, {se_diff_pz, 0.0020469953}, {gc_lambda, 1.2173413}, {n_variants, 9457998.0}, {n_variants_sig, 9612.0}]  |true              |
|GCST004137|[{mean_beta, 9.389989E-5}, {mean_diff_pz, -3.1076767E-4}, {se_diff_pz, 0.009171905}, {gc_lambda, 1.0637354}, {n_variants, 1.1094833E7}, {n_variants_sig, 1279.0}]  |true              |
|GCST004292|[{mean_beta, 1.7991567E-4}, {mean_diff_pz, 0.004244354}, {se_diff_pz, 0.024963312}, {gc_lambda, 0.9769375}, {n_variants, 7827.0}, {n_variants_sig, 1.0}]           |true              |
+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
only showing top 20 rows

In [39]:
import pyspark.sql.types as t
sumstats_qc_aggregated = sumstats_qc.groupBy("studyId").agg(
    f.collect_list(
        f.struct(
            *[
                f.struct(
                    f.lit(col).alias("QCCheckName"),
                    f.col(col).alias("QCCheckValue").cast(t.FloatType()),
                )
                for col in sumstats_qc.columns
                if col != "studyId"
            ]
        )
    ).alias("sumStatQCValues")
).withColumn("sumStatQCPerformed", f.lit(True))

In [37]:
sumstats_qc_aggregated.printSchema()

root
 |-- studyId: string (nullable = true)
 |-- sumStatQCValues: array (nullable = false)
 |    |-- element: struct (containsNull = false)
 |    |    |-- col1: struct (nullable = false)
 |    |    |    |-- QCCheckName: string (nullable = false)
 |    |    |    |-- col2: float (nullable = true)
 |    |    |-- col2: struct (nullable = false)
 |    |    |    |-- QCCheckName: string (nullable = false)
 |    |    |    |-- col2: float (nullable = true)
 |    |    |-- col3: struct (nullable = false)
 |    |    |    |-- QCCheckName: string (nullable = false)
 |    |    |    |-- col2: float (nullable = true)
 |    |    |-- col4: struct (nullable = false)
 |    |    |    |-- QCCheckName: string (nullable = false)
 |    |    |    |-- col2: float (nullable = true)
 |    |    |-- col5: struct (nullable = false)
 |    |    |    |-- QCCheckName: string (nullable = false)
 |    |    |    |-- col2: float (nullable = true)
 |    |    |-- col6: struct (nullable = false)
 |    |    |    |-- QCCheckName: string (nullable = false)
 |    |    |    |-- col2: float (nullable = true)
 |-- sumStatQCPerformed: boolean (nullable = false)

In [31]:
sumstats_qc_aggregated.show(1,truncate=False)

+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
|studyId   |sumStatQCValues                                                                                                                                               |sumStatQCPerformed|
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
|GCST000569|[{{mean_beta, -1.863105E-4}, {mean_diff_pz, -2.662145E-4}, {se_diff_pz, 0.015551462}, {gc_lambda, 1.0218483}, {n_variants, 2392760.0}, {n_variants_sig, 2.0}}]|true              |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
only showing top 1 row

In [15]:
sumstats_qc_aggregated.count()

69286

In [43]:
df=study_index.df.drop("sumStatQCValues", "sumStatQCPerformed").join(qc_df, how="left", on="studyId").withColumn(
    "sumStatQCPerformed",
    f.coalesce(f.col("sumStatQCPerformed"), f.lit(False)),
).withColumn(
    "sumStatQCValues", f.coalesce(f.col("sumStatQCValues"), f.array())
)

In [44]:
df.count()

114252

In [45]:
df.show(1)

+----------+-------------------+--------------------+---------------+------------------+--------------------+----------------------------------+--------+---------+------------------+------------------------+----------------------+---------------------+-------------+-------+--------+--------------------+---------+---------+---------------+------+--------------------+------------------+
|   studyId|   discoverySamples|   initialSampleSize|publicationDate|publicationJournal|    publicationTitle|backgroundTraitFromSourceMappedIds|nSamples|studyType|replicationSamples|traitFromSourceMappedIds|publicationFirstAuthor|ldPopulationStructure|analysisFlags|cohorts|pubmedId|     traitFromSource|projectId|nControls|qualityControls|nCases|     sumStatQCValues|sumStatQCPerformed|
+----------+-------------------+--------------------+---------------+------------------+--------------------+----------------------------------+--------+---------+------------------+------------------------+----------------------+---------------------+-------------+-------+--------+--------------------+---------+---------+---------------+------+--------------------+------------------+
|GCST004746|[{European, 24108}]|2,664 European an...|     2017-06-12|         Nat Genet|Large-scale assoc...|                              null|   24108|     gwas|                []|           [EFO_0000702]|              McKay JD|         [{nfe, 1.0}]|           []|   null|28604730|Small cell lung c...|     GCST|    21444|             []|  2664|[{mean_beta, 0.00...|              true|
+----------+-------------------+--------------------+---------------+------------------+--------------------+----------------------------------+--------+---------+------------------+------------------------+----------------------+---------------------+-------------+-------+--------+--------------------+---------+---------+---------------+------+--------------------+------------------+
only showing top 1 row

In [28]:
df.printSchema()

root
 |-- studyId: string (nullable = false)
 |-- discoverySamples: array (nullable = true)
 |    |-- element: struct (containsNull = false)
 |    |    |-- ancestry: string (nullable = true)
 |    |    |-- sampleSize: integer (nullable = false)
 |-- initialSampleSize: string (nullable = true)
 |-- publicationDate: string (nullable = true)
 |-- publicationJournal: string (nullable = true)
 |-- publicationTitle: string (nullable = true)
 |-- backgroundTraitFromSourceMappedIds: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- nSamples: integer (nullable = true)
 |-- studyType: string (nullable = false)
 |-- replicationSamples: array (nullable = true)
 |    |-- element: struct (containsNull = false)
 |    |    |-- ancestry: string (nullable = true)
 |    |    |-- sampleSize: integer (nullable = true)
 |-- traitFromSourceMappedIds: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- publicationFirstAuthor: string (nullable = true)
 |-- ldPopulationStructure: array (nullable = true)
 |    |-- element: struct (containsNull = false)
 |    |    |-- ldPopulation: string (nullable = true)
 |    |    |-- relativeSampleSize: double (nullable = true)
 |-- analysisFlags: array (nullable = true)
 |    |-- element: string (containsNull = false)
 |-- cohorts: array (nullable = true)
 |    |-- element: string (containsNull = false)
 |-- pubmedId: string (nullable = true)
 |-- traitFromSource: string (nullable = false)
 |-- projectId: string (nullable = false)
 |-- nControls: integer (nullable = true)
 |-- qualityControls: array (nullable = true)
 |    |-- element: string (containsNull = false)
 |-- nCases: integer (nullable = true)
 |-- sumStatQCValues: array (nullable = false)
 |    |-- element: struct (containsNull = false)
 |    |    |-- col1: struct (nullable = false)
 |    |    |    |-- QCCheckName: string (nullable = false)
 |    |    |    |-- col2: float (nullable = true)
 |    |    |-- col2: struct (nullable = false)
 |    |    |    |-- QCCheckName: string (nullable = false)
 |    |    |    |-- col2: float (nullable = true)
 |    |    |-- col3: struct (nullable = false)
 |    |    |    |-- QCCheckName: string (nullable = false)
 |    |    |    |-- col2: float (nullable = true)
 |    |    |-- col4: struct (nullable = false)
 |    |    |    |-- QCCheckName: string (nullable = false)
 |    |    |    |-- col2: float (nullable = true)
 |    |    |-- col5: struct (nullable = false)
 |    |    |    |-- QCCheckName: string (nullable = false)
 |    |    |    |-- col2: float (nullable = true)
 |    |    |-- col6: struct (nullable = false)
 |    |    |    |-- QCCheckName: string (nullable = false)
 |    |    |    |-- col2: float (nullable = true)
 |-- sumStatQCPerformed: boolean (nullable = false)

In [46]:
StudyIndex(_df=df,_schema=StudyIndex.get_schema())

StudyIndex(_df=DataFrame[studyId: string, discoverySamples: array<struct<ancestry:string,sampleSize:int>>, initialSampleSize: string, publicationDate: string, publicationJournal: string, publicationTitle: string, backgroundTraitFromSourceMappedIds: array<string>, nSamples: int, studyType: string, replicationSamples: array<struct<ancestry:string,sampleSize:int>>, traitFromSourceMappedIds: array<string>, publicationFirstAuthor: string, ldPopulationStructure: array<struct<ldPopulation:string,relativeSampleSize:double>>, analysisFlags: array<string>, cohorts: array<string>, pubmedId: string, traitFromSource: string, projectId: string, nControls: int, qualityControls: array<string>, nCases: int, sumStatQCValues: array<struct<QCCheckName:string,QCCheckValue:float>>, sumStatQCPerformed: boolean], _schema=StructType([StructField('studyId', StringType(), False), StructField('projectId', StringType(), False), StructField('studyType', StringType(), False), StructField('traitFromSource', StringType(), True), StructField('traitFromSourceMappedIds', ArrayType(StringType(), True), True), StructField('diseaseIds', ArrayType(StringType(), True), True), StructField('geneId', StringType(), True), StructField('biosampleFromSourceId', StringType(), True), StructField('biosampleId', StringType(), True), StructField('pubmedId', StringType(), True), StructField('publicationTitle', StringType(), True), StructField('publicationFirstAuthor', StringType(), True), StructField('publicationDate', StringType(), True), StructField('publicationJournal', StringType(), True), StructField('backgroundTraitFromSourceMappedIds', ArrayType(StringType(), True), True), StructField('backgroundDiseaseIds', ArrayType(StringType(), True), True), StructField('initialSampleSize', StringType(), True), StructField('nCases', IntegerType(), True), StructField('nControls', IntegerType(), True), StructField('nSamples', IntegerType(), True), StructField('cohorts', ArrayType(StringType(), True), True), StructField('ldPopulationStructure', ArrayType(StructType([StructField('ldPopulation', StringType(), True), StructField('relativeSampleSize', DoubleType(), True)]), False), True), StructField('discoverySamples', ArrayType(StructType([StructField('sampleSize', IntegerType(), True), StructField('ancestry', StringType(), True)]), False), True), StructField('replicationSamples', ArrayType(StructType([StructField('sampleSize', IntegerType(), True), StructField('ancestry', StringType(), True)]), False), True), StructField('qualityControls', ArrayType(StringType(), True), True), StructField('analysisFlags', ArrayType(StringType(), True), True), StructField('summarystatsLocation', StringType(), True), StructField('hasSumstats', BooleanType(), True), StructField('condition', StringType(), True), StructField('sumStatQCPerformed', BooleanType(), True), StructField('sumStatQCValues', ArrayType(StructType([StructField('QCCheckName', StringType(), True), StructField('QCCheckValue', FloatType(), True)]), True), True)]))

In [ ]:
from gentropy.sumstat_qc_step import SummaryStatisticsQCStep 
x=SummaryStatisticsQCStep(session=session,
gwas_path="gs://ot_orchestration/ukb_ppp_eur_data/harmonised_summary_statistics/",
output_path="gs://genetics-portal-dev-analysis/yt4/UKBB_PPP_QC_LOG_20241004",
pval_threshold= 1e-8)

In [3]:
x=SummaryStatistics.from_parquet(session,"gs://gwas_catalog_data/harmonised_summary_statistics/GCST003401.parquet")

In [4]:
x.df.count()

2119618

In [8]:
x.df=x.df.filter(f.col("pValueExponent")<=(-10000))

In [9]:
x.df.count()

0

In [10]:
from gentropy.method.sumstat_quality_controls import SummaryStatisticsQC

In [11]:
y=SummaryStatisticsQC.number_of_snps(x, pval_threshold=1e-8)

In [12]:
y.show()

+-------+----------+--------------+
|studyId|n_variants|n_variants_sig|
+-------+----------+--------------+
+-------+----------+--------------+

In [14]:
y=SummaryStatisticsQC.get_quality_control_metrics(gwas=x, pval_threshold=1e-8)

In [16]:
y.printSchema()

root
 |-- studyId: string (nullable = true)
 |-- mean_beta: double (nullable = true)
 |-- mean_diff_pz: double (nullable = true)
 |-- se_diff_pz: double (nullable = true)
 |-- gc_lambda: double (nullable = true)
 |-- n_variants: long (nullable = true)
 |-- n_variants_sig: long (nullable = true)

In [3]:
from gentropy.locus_breaker_clumping import LocusBreakerClumpingStep


ss1=LocusBreakerClumpingStep(session,
summary_statistics_input_path="gs://gwas_catalog_data/harmonised_summary_statistics/GCST003401.parquet",
clumped_study_locus_output_path="gs://genetics-portal-dev-analysis/yt4/tmp_v3",
lbc_baseline_pvalue=1e-5,
lbc_distance_cutoff=500_000,
lbc_pvalue_threshold=1.7e-7,
lbc_flanking_distance=250_000,
large_loci_size=1e6,
wbc_clump_distance=500_000,
wbc_pvalue_threshold=1.7e-7,
collect_locus = False,
remove_mhc = True)

In [7]:
type(1e6//2)

float

In [4]:
x.df.count()

2119618

In [5]:
from gentropy.sumstat_qc_step import SummaryStatisticsQCStep

In [14]:
x=SummaryStatisticsQCStep(session=session,
                          gwas_path="gs://gwas_catalog_data/harmonised_summary_statistics/GCST003401.parquet",
        output_path="gs://genetics-portal-dev-analysis/yt4/sumstat_qc_output_log_example",
        pval_threshold= 1e-8)

In [12]:
y=session.spark.read.parquet("file:///Users/yt4/Projects/gentropy/notebooks/temp_files/sumstat_qc_output_log")

In [13]:
y.show(truncate=False)

+----------+----------------------+--------------------+-------------------+-----------------+----------+--------------+
|studyId   |mean_beta             |mean_diff_pz        |se_diff_pz         |gc_lambda        |n_variants|n_variants_sig|
+----------+----------------------+--------------------+-------------------+-----------------+----------+--------------+
|GCST003401|-1.0276427167536857E-5|-0.01287489120315704|0.04625858339667292|1.272534943024209|2119618   |1399          |
+----------+----------------------+--------------------+-------------------+-----------------+----------+--------------+

In [3]:
x=StudyLocus.from_parquet(session,"gs://ot_orchestration/ukb_ppp_eur_data/study_locus_datasets/locus_breaker_clumping")

In [5]:
x.df.count()

17670

In [6]:
x.df.show(2)

+---------+---------------+----------+--------+------+--------------------+---------+------+--------------+--------------+-------------------------------+-------------+-------------------+---------------+-----------------+----------------+------------------+------------+-----------+----------+--------+----------+-----+--------------------+----------+--------------------+
|studyType|      variantId|chromosome|position|region|             studyId|     beta|zScore|pValueMantissa|pValueExponent|effectAlleleFrequencyFromSource|standardError|subStudyDescription|qualityControls|finemappingMethod|credibleSetIndex|credibleSetlog10BF|purityMeanR2|purityMinR2|locusStart|locusEnd|sampleSize|ldSet|               locus|confidence|        studyLocusId|
+---------+---------------+----------+--------+------+--------------------+---------+------+--------------+--------------+-------------------------------+-------------+-------------------+---------------+-----------------+----------------+------------------+------------+-----------+----------+--------+----------+-----+--------------------+----------+--------------------+
|     null| 8_18067230_A_T|         8|18067230|  null|UKB_PPP_EUR_ASAH1...| -1.09931|  null|     2.5351286|          -727|                           null|    0.0190287|               null|             []|             null|            null|              null|        null|       null|  17317230|18817230|     33610| null|[{null, null, nul...|      null|adf6d303aa503970c...|
|     null|16_82629683_G_T|        16|82629683|  null|UKB_PPP_EUR_ADIPO...|-0.424385|  null|     3.3143625|           -35|                           null|    0.0342773|               null|             []|             null|            null|              null|        null|       null|  81879683|83379683|     33995| null|[{null, null, nul...|      null|657a52a10f8662cf7...|
+---------+---------------+----------+--------+------+--------------------+---------+------+--------------+--------------+-------------------------------+-------------+-------------------+---------------+-----------------+----------------+------------------+------------+-----------+----------+--------+----------+-----+--------------------+----------+--------------------+
only showing top 2 rows

In [11]:
y=session.spark.read.parquet("gs://genetics-portal-dev-analysis/dc16/output/ukb_ppp/clean_loci.parquet")
from pyspark.sql.types import StringType
# Assuming x is your DataFrame
y = y.withColumn("studyLocusId", f.col("studyLocusId").cast(StringType()))

df2=StudyLocus(
            _df=y,
            _schema=StudyLocus.get_schema(),
        )

AnalysisException: Path does not exist: gs://genetics-portal-dev-analysis/dc16/output/ukb_ppp/clean_loci.parquet

In [9]:
df2.df.count()

16015

In [10]:
df2.df.show(2)

+--------------------+---------------+----------+---------+------+--------------------+---------+------+--------------+--------------+-------------------------------+-------------+-------------------+---------------+-----------------+----------------+------------------+------------+-----------+----------+-----+--------------------+
|        studyLocusId|      variantId|chromosome| position|region|             studyId|     beta|zScore|pValueMantissa|pValueExponent|effectAlleleFrequencyFromSource|standardError|subStudyDescription|qualityControls|finemappingMethod|credibleSetIndex|credibleSetlog10BF|purityMeanR2|purityMinR2|sampleSize|ldSet|               locus|
+--------------------+---------------+----------+---------+------+--------------------+---------+------+--------------+--------------+-------------------------------+-------------+-------------------+---------------+-----------------+----------------+------------------+------------+-----------+----------+-----+--------------------+
|-9186501991283637650|3_100003585_C_T|         3|100003585|  null|UKB_PPP_EUR_FLT4_...| 0.230472|  null|     1.0143784|           -38|                           null|    0.0179503|               null|             []|             null|            null|              null|        null|       null|     33822| null|[{3_101094952_G_C...|
|-9129651954653072270| 6_44789173_T_C|         6| 44789173|  null|UKB_PPP_EUR_GPHA2...|0.0547006|  null|         1.024|           -12|                           null|    0.0080325|               null|             []|             null|            null|              null|        null|       null|     33796| null|[{6_44168954_G_T,...|
+--------------------+---------------+----------+---------+------+--------------------+---------+------+--------------+--------------+-------------------------------+-------------+-------------------+---------------+-----------------+----------------+------------------+------------+-----------+----------+-----+--------------------+
only showing top 2 rows

In [3]:
x=session.spark.read.parquet("temp_fiels/nan_locus2")
from pyspark.sql.types import StringType
# Assuming x is your DataFrame
x = x.withColumn("studyLocusId", f.col("studyLocusId").cast(StringType()))

df2=StudyLocus(
            _df=x,
            _schema=StudyLocus.get_schema(),
        )

df2=StudyLocus.from_parquet(session, "temp_fiels/nan_locus3")
df2=df2.df
#df2.show()

In [4]:
si=StudyIndex.from_parquet(session,"gs://genetics_etl_python_playground/releases/24.06/study_index/gwas_catalog")

In [5]:
session=session
study_locus_row=df2.collect()[1]
study_index=si
max_causal_snps=10
cs_lbf_thr=2
sum_pips=0.99
susie_est_tausq=False
run_carma=False
carma_tau=0.04
run_sumstat_imputation=False
carma_time_limit=6000
imputed_r2_threshold=0.8
ld_score_threshold=5

purity_mean_r2_threshold=0
purity_min_r2_threshold=0.25
lead_pval_threshold=1e-5
ld_min_r2=0.8

In [16]:
result_logging = SusieFineMapperStep.susie_finemapper_one_sl_row_v4_ss_gathered_boundaries(
    session=session,
    study_locus_row=study_locus_row,
    study_index=study_index,
    max_causal_snps=max_causal_snps,
    purity_mean_r2_threshold=purity_mean_r2_threshold,
    purity_min_r2_threshold=purity_min_r2_threshold,
    cs_lbf_thr=cs_lbf_thr,
    sum_pips=sum_pips,
    lead_pval_threshold=1e-5,
    susie_est_tausq=susie_est_tausq,
    run_carma=False,
    run_sumstat_imputation=run_sumstat_imputation,
    carma_tau=0.2,
    carma_time_limit=carma_time_limit,
    imputed_r2_threshold=imputed_r2_threshold,
    ld_score_threshold=ld_score_threshold,
    ld_min_r2=ld_min_r2,
)

In [17]:
result_logging["study_locus"] is not None

True

In [18]:
result_logging is not None

True

In [19]:
result_logging["log"]

,N_gwas_before_dedupl,N_gwas,N_ld,N_overlap,N_outliers,N_imputed,N_final_to_fm,elapsed_time
0,3498,3498,3498,3498,0,0,3498,25.492343

In [20]:
result_logging["study_locus"].df.show(truncate=False)

+----------------+--------------------------------+------------+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+----------+---------+-----------------+------------------+------------+-----------+-------------------+--------------+--------------+----------+---------+
|credibleSetIndex|studyLocusId                    |studyId     |region              |locus                                                                                                                                                                                                                                                                                                                            |variantId       |chromosome|position |finemappingMethod|credibleSetlog10BF|purityMeanR2|purityMinR2|zScore             |pValueMantissa|pValueExponent|locusStart|locusEnd |
+----------------+--------------------------------+------------+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+----------+---------+-----------------+------------------+------------+-----------+-------------------+--------------+--------------+----------+---------+
|3               |8ed6a6e421ac04a2293bce9b910086a3|GCST90002391|7:99238175-100738175|[{7_100638579_G_A, 0.9772850209566597, 364.2227948644375, 0.08331741667796712}, {7_100638347_C_A, 0.01791654127153941, 360.223740903693, 0.08265067865900952}]                                                                                                                                                                   |7_100638579_G_A |7         |100638579|SuSiE-inf        |154.6461089444019 |1.0         |1.0        |22.032925673701083 |1.3928045     |-107          |99238175  |100738175|
|9               |fdd4fbc5183fb67357004581390f9c47|GCST90002391|7:99238175-100738175|[{7_100621008_C_T, 1.0, 72.2445266427373, 0.03454911334437}]                                                                                                                                                                                                                                                                     |7_100621008_C_T |7         |100621008|SuSiE-inf        |27.831579463302216|1.0         |1.0        |11.436719354482149 |2.7405345     |-30           |99238175  |100738175|
|8               |28a4033f4597e5566e98e87f95be0f9d|GCST90002391|7:99238175-100738175|[{7_100717534_C_CT, 0.9999950682655304, 99.71676545452326, -0.04423611093299747}]                                                                                                                                                                                                                                                |7_100717534_C_CT|7         |100717534|SuSiE-inf        |39.76262332653022 |1.0         |1.0        |-10.770290838783989|4.7549677     |-27           |99238175  |100738175|
|7               |d07625117917c992b1bfdd77b6a031ea|GCST90002391|7:99238175-100738175|[{7_99613384_A_G, 0.9999940711528521, 122.90393901041688, 0.043446751014759984}]                                                                                                                                                                                                                                                 |7_99613384_A_G  |7         |99613384 |SuSiE-inf        |49.8326852857553  |1.0         |1.0        |9.024065216371504  |1.8123603     |-19           |99238175  |100738175|
|1               |f656b7ad4eede0f4763f7f014dfd4db1|GCST90002391|7:99238175-100738175|[{7_99970285_C_T, 0.49006999067828716, 493.7649585448591, -0.09873047743183157}, {7_99968784_G_A, 0.4228579964464839, 493.61744674272006, -0.09871896793851824}, {7_99969832_C_T, 0.061023494753073754, 491.6816692757406, -0.0985288243920375}, {7_99966338_G_A, 0.024985965007233137, 490.78872459334957, -0.0984422993014042}]|7_99970285_C_T  |7         |99970285 |SuSiE-inf        |211.2053189370907 |1.0         |1.0        |-7.650038456812317 |2.0091922     |-14           |99238175  |100738175|
|6               |36f83518e6edcc1ed2030ad050eaf12f|GCST90002391|7:99238175-100738175|[{7_99922677_C_CA, 1.0, 198.4031460658081, -0.06282484370908413}]                                                                                                                                                                                                                                                                |7_99922677_C_CA |7         |99922677 |SuSiE-inf        |82.62157172286402 |1.0         |1.0        |-5.191237951965294 |2.0890045     |-7            |99238175  |100738175|
|2               |29157608e183a0c1f9ffb3603ad2d3a4|GCST90002391|7:99238175-100738175|[{7_99969408_T_TA, 1.0, 419.98659599180314, 0.09108187472052097}]                                                                                                                                                                                                                                                                |7_99969408_T_TA |7         |99969408 |SuSiE-inf        |178.85404130608862|1.0         |1.0        |5.18049084777481   |2.213028      |-7            |99238175  |100738175|
+----------------+--------------------------------+------------+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+----------+---------+-----------------+------------------+------------+-----------+-------------------+--------------+--------------+----------+---------+

In [21]:
variant_id_list = result_logging["study_locus"].df.select("variantId").rdd.flatMap(lambda x: x).collect()
variant_id_to_index = {variant: idx for idx, variant in enumerate(result_logging["GWAS_df"]['variantId'])}
indices = [variant_id_to_index[variant] for variant in variant_id_list if variant in variant_id_to_index]

In [22]:
variant_id_list

['7_100638579_G_A',
 '7_100621008_C_T',
 '7_100717534_C_CT',
 '7_99613384_A_G',
 '7_99970285_C_T',
 '7_99922677_C_CA',
 '7_99969408_T_TA']

In [23]:
indices

[3207, 3162, 3431, 922, 1742, 1586, 1740]

In [24]:
result_logging["GWAS_df"].iloc[indices]

      index         variantId          z
3207   3207   7_100638579_G_A  22.032926
3162   3162   7_100621008_C_T  11.436719
3431   3431  7_100717534_C_CT -10.770291
922     922    7_99613384_A_G   9.024065
1742   1742    7_99970285_C_T  -7.650038
1586   1586   7_99922677_C_CA  -5.191238
1740   1740   7_99969408_T_TA   5.180491

In [25]:
x=result_logging["LD"][indices, :][:, indices]
x=x**2
x[x>=ld_min_r2]=1
x[x<ld_min_r2]=0
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [6]:
import logging
import time
from typing import Any

import numpy as np
import pandas as pd
import pyspark.sql.functions as f
import scipy as sc
from pyspark.sql import DataFrame, Row, Window
from pyspark.sql.functions import row_number
from pyspark.sql.types import (
    DoubleType,
    IntegerType,
    StringType,
    StructField,
    StructType,
)

from gentropy.common.session import Session
from gentropy.common.spark_helpers import (
    neglog_pvalue_to_mantissa_and_exponent,
    order_array_of_structs_by_field,
)
from gentropy.dataset.study_index import StudyIndex
from gentropy.dataset.study_locus import StudyLocus
from gentropy.datasource.gnomad.ld import GnomADLDMatrix
from gentropy.method.carma import CARMA
from gentropy.method.sumstat_imputation import SummaryStatisticsImputation
from gentropy.method.susie_inf import SUSIE_inf

In [7]:
# PLEASE DO NOT REMOVE THIS LINE
pd.DataFrame.iteritems = pd.DataFrame.items

chromosome = study_locus_row["chromosome"]
studyId = study_locus_row["studyId"]
locusStart = study_locus_row["locusStart"]
locusEnd = study_locus_row["locusEnd"]

study_index_df = study_index._df
study_index_df = study_index_df.filter(f.col("studyId") == studyId)
major_population = study_index_df.select(
    "studyId",
    order_array_of_structs_by_field(
        "ldPopulationStructure", "relativeSampleSize"
    )[0]["ldPopulation"].alias("majorPopulation"),
).collect()[0]["majorPopulation"]

region = chromosome + ":" + str(int(locusStart)) + "-" + str(int(locusEnd))

schema = StudyLocus.get_schema()
gwas_df = session.spark.createDataFrame([study_locus_row], schema=schema)
exploded_df = gwas_df.select(f.explode("locus").alias("locus"))

result_df = exploded_df.select(
    "locus.variantId", "locus.beta", "locus.standardError"
)
gwas_df = (
    result_df.withColumn("z", f.col("beta") / f.col("standardError"))
    .withColumn(
        "chromosome", f.split(f.col("variantId"), "_")[0].cast("string")
    )
    .withColumn("position", f.split(f.col("variantId"), "_")[1].cast("int"))
    .filter(f.col("chromosome") == chromosome)
    .filter(f.col("position") >= int(locusStart))
    .filter(f.col("position") <= int(locusEnd))
    .filter(f.col("z").isNotNull())
)

# Remove ALL duplicated variants from GWAS DataFrame - we don't know which is correct
variant_counts = gwas_df.groupBy("variantId").count()
unique_variants = variant_counts.filter(f.col("count") == 1)
gwas_df = gwas_df.join(unique_variants, on="variantId", how="left_semi")

ld_index = (
    GnomADLDMatrix()
    .get_locus_index_boundaries(
        study_locus_row=study_locus_row,
        major_population=major_population,
    )
    .withColumn(
        "variantId",
        f.concat(
            f.lit(chromosome),
            f.lit("_"),
            f.col("`locus.position`"),
            f.lit("_"),
            f.col("alleles").getItem(0),
            f.lit("_"),
            f.col("alleles").getItem(1),
        ).cast("string"),
    )
)
# Remove ALL duplicated variants from ld_index DataFrame - we don't know which is correct
variant_counts = ld_index.groupBy("variantId").count()
unique_variants = variant_counts.filter(f.col("count") == 1)
ld_index = ld_index.join(unique_variants, on="variantId", how="left_semi").sort(
    "idx"
)

if not run_sumstat_imputation:
    # Filtering out the variants that are not in the LD matrix, we don't need them
    gwas_index = gwas_df.join(
        ld_index.select("variantId", "alleles", "idx"), on="variantId"
    ).sort("idx")
    gwas_df = gwas_index.select(
        "variantId",
        "z",
        "chromosome",
        "position",
        "beta",
        "StandardError",
    )
    gwas_index = gwas_index.drop(
        "z", "chromosome", "position", "beta", "StandardError"
    )

    gnomad_ld = GnomADLDMatrix.get_numpy_matrix(
        gwas_index, gnomad_ancestry=major_population
    )

    # Module to remove NANs from the LD matrix
    if sum(sum(np.isnan(gnomad_ld))) > 0:
        gwas_index = gwas_index.toPandas()

        # First round of filtering out the variants with NANs
        nan_count = 1 - (sum(np.isnan(gnomad_ld)) / len(gnomad_ld))
        indices = np.where(nan_count >= 0.98)
        indices = indices[0]
        gnomad_ld = gnomad_ld[indices][:, indices]

        gwas_index = gwas_index.iloc[indices, :]


        # Second round of filtering out the variants with NANs
        nan_count = sum(np.isnan(gnomad_ld))
        indices = np.where(nan_count == 0)
        indices = indices[0]

        gnomad_ld = gnomad_ld[indices][:, indices]
        gwas_index = gwas_index.iloc[indices, :]

 
        gwas_index = session.spark.createDataFrame(gwas_index)

else:
    gwas_index = gwas_df.join(
        ld_index.select("variantId", "alleles", "idx"), on="variantId"
    ).sort("idx")

    gwas_index = ld_index
    gnomad_ld = GnomADLDMatrix.get_numpy_matrix(
        gwas_index, gnomad_ancestry=major_population
    )

    # Module to remove NANs from the LD matrix
    if sum(sum(np.isnan(gnomad_ld))) > 0:
        gwas_index = gwas_index.toPandas()

        # First round of filtering out the variants with NANs
        nan_count = 1 - (sum(np.isnan(gnomad_ld)) / len(gnomad_ld))
        indices = np.where(nan_count >= 0.98)
        indices = indices[0]
        gnomad_ld = gnomad_ld[indices][:, indices]

        gwas_index = gwas_index.iloc[indices, :]



        # Second round of filtering out the variants with NANs
        nan_count = sum(np.isnan(gnomad_ld))
        indices = np.where(nan_count == 0)
        indices = indices[0]

        gnomad_ld = gnomad_ld[indices][:, indices]
        gwas_index = gwas_index.iloc[indices, :]


        gwas_index = session.spark.createDataFrame(gwas_index)

# sanity filters on LD matrix
np.fill_diagonal(gnomad_ld, 1)
gnomad_ld[gnomad_ld > 1] = 1
gnomad_ld[gnomad_ld < -1] = -1
upper_triangle = np.triu(gnomad_ld)
gnomad_ld = (
    upper_triangle + upper_triangle.T - np.diag(upper_triangle.diagonal())
)
np.fill_diagonal(gnomad_ld, 1)

ERROR:root:KeyboardInterrupt while sending command.
Traceback (most recent call last):
  File "/Users/yt4/Library/Caches/pypoetry/virtualenvs/gentropy-krNFZEZg-py3.10/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/Users/yt4/Library/Caches/pypoetry/virtualenvs/gentropy-krNFZEZg-py3.10/lib/python3.10/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/Users/yt4/.pyenv/versions/3.10.8/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt

2024-10-01 15:15:35.210 Hail: INFO: Table.join: renamed the following fields on the right to avoid name conflicts:
    'age_distribution' -> 'age_distribution_1'
    'freq_index_dict' -> 'freq_index_dict_1'
    'popmax_index_dict' -> 'popmax_index_dict_1'
    'rf' -> 'rf_1'
    'faf_index_dict' -> 'faf_index_dict_1'
    'freq_meta' -> 'freq_meta_1'
    'age_index_dict' -> 'age_index_dict_1'

KeyboardInterrupt:

In [20]:
gnomad_ld.shape

(3087, 3087)

In [10]:
gwas_index.count()

3087

In [11]:
GWAS_df=gwas_df
ld_index=gwas_index
gnomad_ld=gnomad_ld
L=max_causal_snps
session=session
studyId=studyId
region=region
susie_est_tausq=susie_est_tausq
run_carma=run_carma
run_sumstat_imputation=run_sumstat_imputation
carma_time_limit=carma_time_limit
carma_tau=carma_tau
imputed_r2_threshold=imputed_r2_threshold
ld_score_threshold=ld_score_threshold
sum_pips=sum_pips

In [12]:
# PLEASE DO NOT REMOVE THIS LINE
pd.DataFrame.iteritems = pd.DataFrame.items

start_time = time.time()
GWAS_df = GWAS_df.toPandas()
N_gwas_before_dedupl = len(GWAS_df)

GWAS_df = GWAS_df.drop_duplicates(subset="variantId", keep=False)
GWAS_df = GWAS_df.reset_index()

ld_index = ld_index.toPandas()
ld_index = ld_index.reset_index()

N_gwas = len(GWAS_df)
N_ld = len(ld_index)

# Filtering out the variants that are not in the LD matrix, we don't need them
df_columns = ["variantId", "z"]
GWAS_df = GWAS_df.merge(ld_index, on="variantId", how="inner")
GWAS_df = GWAS_df[df_columns].reset_index()
N_after_merge = len(GWAS_df)

merged_df = GWAS_df.merge(
    ld_index, left_on="variantId", right_on="variantId", how="inner"
)
indices = merged_df["index_y"].values

ld_to_fm = gnomad_ld[indices][:, indices]
z_to_fm = GWAS_df["z"].values

if run_carma:
    carma_output = CARMA.time_limited_CARMA_spike_slab_noEM(
        z=z_to_fm, ld=ld_to_fm, sec_threshold=carma_time_limit, tau=carma_tau
    )
    if carma_output["Outliers"] != [] and carma_output["Outliers"] is not None:
        GWAS_df.drop(carma_output["Outliers"], inplace=True)
        GWAS_df = GWAS_df.reset_index()
        ld_index = ld_index.reset_index()
        merged_df = GWAS_df.merge(
            ld_index, left_on="variantId", right_on="variantId", how="inner"
        )
        indices = merged_df["index_y"].values

        ld_to_fm = gnomad_ld[indices][:, indices]
        z_to_fm = GWAS_df["z"].values
        N_outliers = len(carma_output["Outliers"])
    else:
        N_outliers = 0
else:
    N_outliers = 0

if run_sumstat_imputation:
    known = indices
    unknown = [
        index for index in list(range(len(gnomad_ld))) if index not in known
    ]
    sig_t = gnomad_ld[known, :][:, known]
    sig_i_t = gnomad_ld[unknown, :][:, known]
    zt = z_to_fm

    sumstat_imp_res = SummaryStatisticsImputation.raiss_model(
        z_scores_known=zt,
        ld_matrix_known=sig_t,
        ld_matrix_known_missing=sig_i_t,
        lamb=0.01,
        rtol=0.01,
    )

    bool_index = (sumstat_imp_res["imputation_r2"] >= imputed_r2_threshold) * (
        sumstat_imp_res["ld_score"] >= ld_score_threshold
    )
    if sum(bool_index) >= 1:
        indices = np.where(bool_index)[0]
        index_to_add = [unknown[i] for i in indices]
        index_to_fm = np.concatenate((known, index_to_add))

        ld_to_fm = gnomad_ld[index_to_fm][:, index_to_fm]

        snp_info_to_add = pd.DataFrame(
            {
                "variantId": ld_index.iloc[index_to_add, :]["variantId"],
                "z": sumstat_imp_res["mu"][indices],
            }
        )
        GWAS_df = pd.concat([GWAS_df, snp_info_to_add], ignore_index=True)
        z_to_fm = GWAS_df["z"].values

        N_imputed = len(indices)
    else:
        N_imputed = 0
else:
    N_imputed = 0

susie_output = SUSIE_inf.susie_inf(
    z=z_to_fm, LD=ld_to_fm, L=L, est_tausq=susie_est_tausq
)

schema = StructType(
    [
        StructField("variantId", StringType(), True),
        StructField("z", DoubleType(), True),
    ]
)
variant_index = (
    session.spark.createDataFrame(
        GWAS_df[["variantId", "z"]],
        schema=schema,
    )
    .withColumn(
        "chromosome", f.split(f.col("variantId"), "_")[0].cast("string")
    )
    .withColumn("position", f.split(f.col("variantId"), "_")[1].cast("int"))
)

In [13]:
susie_output

{'PIP': array([[1.01952713e-55, 3.77183367e-12, 0.00000000e+00, ...,
         9.92106496e-49, 2.65700035e-12, 2.32022272e-56],
        [1.71119348e-54, 5.64004050e-11, 0.00000000e+00, ...,
         1.83274434e-47, 4.49528792e-12, 3.10650968e-55],
        [1.03952330e-55, 3.86169306e-12, 0.00000000e+00, ...,
         1.02390098e-48, 2.50815896e-12, 2.38139879e-56],
        ...,
        [9.18199368e-56, 3.54896586e-12, 0.00000000e+00, ...,
         8.89186746e-49, 2.29414421e-12, 2.16036911e-56],
        [1.08252407e-05, 7.00170215e-11, 0.00000000e+00, ...,
         3.03519949e-24, 4.53366085e-11, 1.23030396e-40],
        [1.01759382e-55, 5.38264112e-12, 0.00000000e+00, ...,
         1.01846032e-48, 4.29630166e-12, 2.47062003e-56]]),
 'mu': array([[-5.43962982e-04, -4.55719606e-04, -7.51670254e-04, ...,
         -2.79725944e-04, -1.28516100e-03, -4.44932182e-04],
        [-6.59472240e-03, -6.42173013e-03, -8.03372366e-03, ...,
         -6.68762350e-03, -3.24227791e-03, -6.33049105e-03],
        [-1.00593761e-04, -8.97092538e-05, -8.46365314e-05, ...,
         -1.12809336e-04, -1.62775284e-05, -1.82514928e-04],
        ...,
        [ 5.00318154e-04, -8.92795398e-04, -6.23484701e-03, ...,
          5.09036976e-05, -8.48391252e-04,  8.12893900e-04],
        [-4.29433335e-02, -6.88117635e-03,  4.66656929e-02, ...,
         -3.00485961e-02, -6.87397893e-03, -2.40953410e-02],
        [ 1.01556916e-03,  2.59842839e-03,  1.94096584e-02, ...,
          1.13868756e-03,  3.17645611e-03, -1.41748825e-03]]),
 'omega': array([[110227.93519073, 111716.36146197, 109807.89390717, ...,
         110250.15764304, 111830.35683567, 110196.82103515],
        [135138.99239347, 136627.4186647 , 134718.9511099 , ...,
         135161.21484577, 136741.41403841, 135107.87823789],
        [102732.37595046, 104220.8022217 , 102312.3346669 , ...,
         102754.59840277, 104334.7975954 , 102701.26179488],
        ...,
        [136096.07087507, 137584.49714631, 135676.02959151, ...,
         136118.29332738, 137698.49252001, 136064.95671949],
        [125011.20022074, 126499.62649198, 124591.15893718, ...,
         125033.42267305, 126613.62186569, 124980.08606517],
        [121379.08926119, 122867.51553242, 120959.04797762, ...,
         121401.31171349, 122981.51090613, 121347.97510561]]),
 'lbf_variable': array([[-2.72286066e+00, -2.01278234e+00, -3.92404575e+00, ...,
         -2.71138366e+00, -1.90411667e+00, -2.76311091e+00],
        [ 9.75765757e-02,  6.92132732e-01,  2.90132669e-01, ...,
          2.04940741e-01, -1.37828475e+00, -1.68689188e-01],
        [-2.70343735e+00, -1.98923790e+00, -3.91934939e+00, ...,
         -2.67983902e+00, -1.96176547e+00, -2.73708605e+00],
        ...,
        [-2.82754032e+00, -2.07368735e+00, -1.42374701e+00, ...,
         -2.82090684e+00, -2.05095459e+00, -2.83449500e+00],
        [ 1.12466350e+02,  9.08394770e-01,  1.31642048e+02, ...,
          5.36688605e+01,  9.32800372e-01,  3.34438487e+01],
        [-2.72475875e+00, -1.65716444e+00,  1.87813169e+01, ...,
         -2.68516684e+00, -1.42355989e+00, -2.70030494e+00]]),
 'ssq': array([0.0021723 , 0.00051314, 0.02481384, 0.010293  , 0.03040325,
        0.03317893, 0.00416464, 0.00207226, 0.00048479, 0.00232977]),
 'sigmasq': 0.9913087248869352,
 'tausq': 0,
 'alpha': array([-0., -0., -0., ..., -0., -0.,  0.]),
 'lbf': array([ 115.8650255 ,   16.25572248, 1334.78664794,  560.15492314,
        1717.66654456, 1840.69365943,  218.87311978,   99.7856706 ,
          16.71475162,  117.3050361 ])}

In [14]:
susie_output=susie_output
session=session
studyId=studyId
region=region
variant_index=variant_index
sum_pips=sum_pips
ld_matrix=ld_to_fm
cs_lbf_thr=cs_lbf_thr

In [15]:
# PLEASE DO NOT REMOVE THIS LINE
pd.DataFrame.iteritems = pd.DataFrame.items

variants = np.array(
    [row["variantId"] for row in variant_index.select("variantId").collect()]
).reshape(-1, 1)

PIPs = susie_output["PIP"]
lbfs = susie_output["lbf_variable"]
mu = susie_output["mu"]
susie_result = np.hstack((variants, PIPs, lbfs, mu))

L_snps = PIPs.shape[1]

# Extracting credible sets
order_creds = list(enumerate(susie_output["lbf"]))
order_creds.sort(key=lambda x: x[1], reverse=True)

counter = 0
for i, cs_lbf_value in order_creds:
    if counter > 0 and cs_lbf_value < cs_lbf_thr:
        counter += 1
        continue
    counter += 1
    sorted_arr = susie_result[
        susie_result[:, i + 1].astype(float).argsort()[::-1]
    ]
    cumsum_arr = np.cumsum(sorted_arr[:, i + 1].astype(float))
    filter_row = np.argmax(cumsum_arr >= sum_pips)
    if filter_row == 0 and cumsum_arr[0] < sum_pips:
        filter_row = len(cumsum_arr)
    filter_row += 1
    filtered_arr = sorted_arr[:filter_row]
    cred_set = filtered_arr[:, [0, i + 1, i + L_snps + 1, i + 2 * L_snps + 1]]
    win = Window.rowsBetween(
        Window.unboundedPreceding, Window.unboundedFollowing
    )

    cred_set = (
        session.spark.createDataFrame(
            cred_set.tolist(),
            ["variantId", "posteriorProbability", "logBF", "beta"],
        )
        .join(
            variant_index.select(
                "variantId",
                "chromosome",
                "position",
            ),
            "variantId",
        )
        .sort(f.desc("posteriorProbability"))
        .withColumn(
            "locus",
            f.collect_list(
                f.struct(
                    f.col("variantId").cast("string").alias("variantId"),
                    f.col("posteriorProbability")
                    .cast("double")
                    .alias("posteriorProbability"),
                    f.col("logBF").cast("double").alias("logBF"),
                    f.col("beta").cast("double").alias("beta"),
                )
            ).over(win),
        )
        .limit(1)
        .withColumns(
            {
                "studyId": f.lit(studyId),
                "region": f.lit(region),
                "credibleSetIndex": f.lit(counter),
                "credibleSetlog10BF": f.lit(cs_lbf_value * 0.4342944819),
                "finemappingMethod": f.lit("SuSiE-inf"),
            }
        )
        .withColumn(
            "studyLocusId",
            StudyLocus.assign_study_locus_id(
                f.col("studyId"), f.col("variantId"), f.col("finemappingMethod")
            ),
        )
        .select(
            "studyLocusId",
            "studyId",
            "region",
            "credibleSetIndex",
            "locus",
            "variantId",
            "chromosome",
            "position",
            "finemappingMethod",
            "credibleSetlog10BF",
        )
    )
    if counter == 1:
        cred_sets = cred_set
    else:
        cred_sets = cred_sets.unionByName(cred_set)

# Calulating purity
variant_index_df = variant_index.toPandas()
cred_sets_variantId = cred_sets.select("locus.variantId").toPandas()

lead_variantId_list = (
    cred_sets.select("variantId").toPandas()["variantId"].tolist()
)
cred_set_index = (
    cred_sets.select("credibleSetIndex").toPandas()["credibleSetIndex"].tolist()
)
vlist_series = pd.Series(lead_variantId_list)
ind = vlist_series.map(variant_index_df.set_index("variantId").index.get_loc)
z_values = variant_index_df.iloc[ind]["z"].tolist()
z_values_array = np.array(z_values)
pval = sc.stats.chi2.sf((z_values_array**2), 1)

# sometimes pval is 0, we need to avoid it
pval[pval < 1e-322] = 1e-322

neglogpval = -np.log10(pval)
neglogpval = neglogpval.tolist()

list_purity_mean_r2 = []
list_purity_min_r2 = []
for _, row in cred_sets_variantId.iterrows():
    row = row.iloc[0]
    vlist_series = pd.Series(row)
    ind = vlist_series.map(
        variant_index_df.set_index("variantId").index.get_loc
    )
    # print(variant_index_df.iloc[ind,0]==vlist)
    squared_matrix = ld_matrix[ind, :][:, ind] ** 2
    purity_mean_r2 = np.mean(squared_matrix)
    purity_min_r2 = np.min(squared_matrix)
    list_purity_mean_r2.append(purity_mean_r2)
    list_purity_min_r2.append(purity_min_r2)

cred_sets = cred_sets.drop("pValueMantissa", "pValueExponent")

df = pd.DataFrame(
    {
        "credibleSetIndex": cred_set_index,
        "purityMeanR2": purity_mean_r2,
        "purityMinR2": purity_min_r2,
        "zScore": z_values,
        "neglogpval": neglogpval,
    }
)
schema = StructType(
    [
        StructField("credibleSetIndex", IntegerType(), True),
        StructField("purityMeanR2", DoubleType(), True),
        StructField("purityMinR2", DoubleType(), True),
        StructField("zScore", DoubleType(), True),
        StructField("neglogpval", DoubleType(), True),
    ]
)

df_spark = session.spark.createDataFrame(df, schema=schema)

cred_sets = cred_sets.join(df_spark, on="credibleSetIndex")

mantissa, exponent = neglog_pvalue_to_mantissa_and_exponent(
    cred_sets.neglogpval
)
cred_sets = cred_sets.withColumn("pValueMantissa", mantissa)
cred_sets = cred_sets.withColumn("pValueExponent", exponent)
cred_sets = cred_sets.withColumn(
    "pValueMantissa", f.col("pValueMantissa").cast("float")
)

In [16]:
cred_sets.show(truncate=False)

+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+-------------------+--------------+--------------+
|credibleSetIndex|studyLocusId        |studyId     |region              |locus                                                                                                                                                                                                                                                |variantId      |chromosome|position|finemappingMethod|credibleSetlog10BF|purityMeanR2|purityMinR2|zScore             |neglogpval         |pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+-------------------+--------------+--------------+
|1               |923949982765216720  |GCST90002322|15:42236528-43736528|[{15_43520398_G_C, 1.0, 1848.7286144548993, -0.1821286026134763}]                                                                                                                                                                                    |15_43520398_G_C|15        |43520398|SuSiE-inf        |799.4030991589394 |1.0         |1.0        |-6.0429371499688855|8.820064587990306  |1.5133362     |-9            |
|2               |3381653650770367723 |GCST90002322|15:42236528-43736528|[{15_43521189_T_C, 1.0, 1725.7014995861196, 0.17434100293412702}]                                                                                                                                                                                    |15_43521189_T_C|15        |43521189|SuSiE-inf        |745.9731020473508 |1.0         |1.0        |-1.3934996402014872|0.7865652483244161 |1.6346875     |-1            |
|3               |-2632831884834309933|GCST90002322|15:42236528-43736528|[{15_43510514_A_C, 1.0, 1342.8216029661196, 0.1574992525978152}]                                                                                                                                                                                     |15_43510514_A_C|15        |43510514|SuSiE-inf        |579.6904757148425 |1.0         |1.0        |0.4236150708364402 |0.17272990060103713|6.718466      |-1            |
|4               |6356608581566170109 |GCST90002322|15:42236528-43736528|[{15_43509840_A_C, 0.9999999876753237, 568.1898781506557, -0.10141569069174518}]                                                                                                                                                                     |15_43509840_A_C|15        |43509840|SuSiE-inf        |243.27219212815967|1.0         |1.0        |-6.140373470701867 |9.084454073301037  |8.232769      |-10           |
|5               |8858076177993068537 |GCST90002322|15:42236528-43736528|[{15_43718994_T_C, 1.0, 226.90807480116231, 0.0644703474732639}]                                                                                                                                                                                     |15_43718994_T_C|15        |43718994|SuSiE-inf        |95.05538815524126 |1.0         |1.0        |-1.8206816387013196|1.1633261530958292 |6.8655267     |-2            |
|6               |-6022298121111655759|GCST90002322|15:42236528-43736528|[{15_43481838_C_G, 0.9235071832819135, 125.26041441851586, -0.04820931639149068}, {15_43485434_A_G, 0.06543832801869778, 122.61334398271471, 0.04783979343197251}, {15_43482120_T_G, 0.005377228304895126, 120.11440889703974, -0.04739672678247319}]|15_43481838_C_G|15        |43481838|SuSiE-inf        |50.94492987516624 |1.0         |1.0        |-6.797022181707687 |10.97141386859998  |1.0680366     |-11           |
|7               |-6085008223147579656|GCST90002322|15:42236528-43736528|[{15_43658501_A_T, 0.9945646322980072, 123.89453033440324, -0.04651202114153519}]                                                                                                                                                                    |15_43658501_A_T|15        |43658501|SuSiE-inf        |50.31954122113802 |1.0         |1.0        |-10.207749251850686|23.737401987012895 |1.8306192     |-24           |
|8               |-2273701730318034092|GCST90002322|15:42236528-43736528|[{15_43331199_T_G, 1.0, 107.82062562794736, -0.04542453628920864}]                                                                                                                                                                                   |15_43331199_T_G|15        |43331199|SuSiE-inf        |43.3363661157673  |1.0         |1.0        |-7.412101593625498 |12.905481830804181 |1.2431346     |-13           |
|9               |-983329156187741650 |GCST90002322|15:42236528-43736528|[{15_42520524_T_G, 0.9999962562417314, 24.74970290478215, 0.021820027812435954}]                                                                                                                                                                     |15_42520524_T_G|15        |42520524|SuSiE-inf        |7.259124396651924 |1.0         |1.0        |1.9200000000000002 |1.2607608262087409 |5.48579       |-2            |
|10              |-5327263775886500084|GCST90002322|15:42236528-43736528|[{15_43297635_A_G, 0.9999993762056993, 24.29067688470837, -0.02245114123516229}]                                                                                                                                                                     |15_43297635_A_G|15        |43297635|SuSiE-inf        |7.059770574099266 |1.0         |1.0        |-5.653412648716343 |7.803290421657356  |1.5729307     |-8            |
+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+-------------------+--------------+--------------+

In [20]:
lead_pval_threshold=1e-3
purity_mean_r2_threshold=0.01
purity_min_r2_threshold=0.01
cs_lbf_thr=2
ld_min_r2=0.8

In [61]:
from pyspark.sql.functions import desc, row_number
# Filter by lead p-value, credible set logBF, purity mean r2 and purity min r2
cred_sets = cred_sets.filter(
    (f.col("neglogpval") >= -np.log10(lead_pval_threshold))
    & (f.col("credibleSetlog10BF") >= cs_lbf_thr * 0.4342944819)
    & (f.col("purityMinR2") >= purity_min_r2_threshold)
    & (f.col("purityMeanR2") >= purity_mean_r2_threshold)
)


# Remove duplicated by lead variant
if cred_sets.count() > 1:
    window = Window.partitionBy("variantId").orderBy("credibleSetIndex")
    cred_sets = cred_sets.withColumn("rank", row_number().over(window))
    cred_sets = cred_sets.filter(cred_sets["rank"] == 1).drop("rank")
    cred_sets = cred_sets.orderBy("credibleSetIndex")

# Remove CSs with high LD between leads
if cred_sets.count() > 1:
    cred_sets = cred_sets.orderBy(desc("neglogpval"))
    lead_variantId_list = (
        cred_sets.select("variantId").toPandas()["variantId"].tolist()
    )
    vlist_series = pd.Series(lead_variantId_list)
    ind = vlist_series.map(
        variant_index_df.set_index("variantId").index.get_loc
    )
    ld_leads = ld_matrix[ind, :][:, ind]
    ld_leads = ld_leads**2
    ld_leads = ld_leads - np.tril(ld_leads)
    np.fill_diagonal(ld_leads, 0)

In [62]:
cred_sets.show(truncate=False)

+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+------------------+--------------+--------------+
|credibleSetIndex|studyLocusId        |studyId     |region              |locus                                                                                                                                                                                                                                                |variantId      |chromosome|position|finemappingMethod|credibleSetlog10BF|purityMeanR2|purityMinR2|zScore             |neglogpval        |pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+------------------+--------------+--------------+
|7               |-6085008223147579656|GCST90002322|15:42236528-43736528|[{15_43658501_A_T, 0.9945646322980072, 123.89453033440324, -0.04651202114153519}]                                                                                                                                                                    |15_43658501_A_T|15        |43658501|SuSiE-inf        |50.31954122113802 |1.0         |1.0        |-10.207749251850686|23.737401987012895|1.8306192     |-24           |
|8               |-2273701730318034092|GCST90002322|15:42236528-43736528|[{15_43331199_T_G, 1.0, 107.82062562794736, -0.04542453628920864}]                                                                                                                                                                                   |15_43331199_T_G|15        |43331199|SuSiE-inf        |43.3363661157673  |1.0         |1.0        |-7.412101593625498 |12.905481830804181|1.2431346     |-13           |
|6               |-6022298121111655759|GCST90002322|15:42236528-43736528|[{15_43481838_C_G, 0.9235071832819135, 125.26041441851586, -0.04820931639149068}, {15_43485434_A_G, 0.06543832801869778, 122.61334398271471, 0.04783979343197251}, {15_43482120_T_G, 0.005377228304895126, 120.11440889703974, -0.04739672678247319}]|15_43481838_C_G|15        |43481838|SuSiE-inf        |50.94492987516624 |1.0         |1.0        |-6.797022181707687 |10.97141386859998 |1.0680366     |-11           |
|4               |6356608581566170109 |GCST90002322|15:42236528-43736528|[{15_43509840_A_C, 0.9999999876753237, 568.1898781506557, -0.10141569069174518}]                                                                                                                                                                     |15_43509840_A_C|15        |43509840|SuSiE-inf        |243.27219212815967|1.0         |1.0        |-6.140373470701867 |9.084454073301037 |8.232769      |-10           |
|1               |923949982765216720  |GCST90002322|15:42236528-43736528|[{15_43520398_G_C, 1.0, 1848.7286144548993, -0.1821286026134763}]                                                                                                                                                                                    |15_43520398_G_C|15        |43520398|SuSiE-inf        |799.4030991589394 |1.0         |1.0        |-6.0429371499688855|8.820064587990306 |1.5133362     |-9            |
|10              |-5327263775886500084|GCST90002322|15:42236528-43736528|[{15_43297635_A_G, 0.9999993762056993, 24.29067688470837, -0.02245114123516229}]                                                                                                                                                                     |15_43297635_A_G|15        |43297635|SuSiE-inf        |7.059770574099266 |1.0         |1.0        |-5.653412648716343 |7.803290421657356 |1.5729307     |-8            |
+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+------------------+--------------+--------------+

In [63]:
lead_variantId_list

['15_43658501_A_T',
 '15_43331199_T_G',
 '15_43481838_C_G',
 '15_43509840_A_C',
 '15_43520398_G_C',
 '15_43297635_A_G']

In [64]:
lead_variantId_list_to_delete = []
for idx in range(len(lead_variantId_list)):
    vId = lead_variantId_list[idx]
    if vId in lead_variantId_list_to_delete:
        continue
    high_ld_indices = np.where(ld_leads[idx, :] >= ld_min_r2)[0]
    if len(high_ld_indices) > 0:
        lead_variantId_list_to_delete=lead_variantId_list_to_delete+list(np.array(lead_variantId_list)[high_ld_indices])

In [65]:
lead_variantId_list_to_delete

['15_43509840_A_C']

In [67]:
ld_leads[ld_leads >= ld_min_r2] = 1
ld_leads[ld_leads < ld_min_r2] = 0

In [68]:
ld_leads

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [69]:
lead_variantId_list

['15_43658501_A_T',
 '15_43331199_T_G',
 '15_43481838_C_G',
 '15_43509840_A_C',
 '15_43520398_G_C',
 '15_43297635_A_G']

In [43]:
high_ld_indices = np.where(ld_leads[idx, :] >= ld_min_r2)[0]

In [55]:
list(np.array(lead_variantId_list)[high_ld_indices])

['15_43509840_A_C']

In [45]:
len(high_ld_indices)

1

In [42]:
lead_variantId_list_to_delete

[]

In [29]:
idx=0
vId = lead_variantId_list[idx]

In [33]:
high_ld_indices = np.where(ld_leads[idx, :] >= ld_min_r2)[0]

In [34]:
high_ld_indices

array([], dtype=int64)

In [37]:
high_ld_indices = np.where(ld_leads[idx, :] >= ld_min_r2)[0]

In [39]:
len(high_ld_indices)

0

In [22]:
cred_sets2 = cred_sets.filter(
    (f.col("neglogpval") >= -np.log10(lead_pval_threshold))
    & (f.col("credibleSetlog10BF") >= cs_lbf_thr * 0.4342944819)
    & (f.col("purityMinR2") >= purity_min_r2_threshold)
    & (f.col("purityMeanR2") >= purity_mean_r2_threshold)
)

In [23]:
cred_sets2.show(truncate=False)

+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+------------------+--------------+--------------+
|credibleSetIndex|studyLocusId        |studyId     |region              |locus                                                                                                                                                                                                                                                |variantId      |chromosome|position|finemappingMethod|credibleSetlog10BF|purityMeanR2|purityMinR2|zScore             |neglogpval        |pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+------------------+--------------+--------------+
|1               |923949982765216720  |GCST90002322|15:42236528-43736528|[{15_43520398_G_C, 1.0, 1848.7286144548993, -0.1821286026134763}]                                                                                                                                                                                    |15_43520398_G_C|15        |43520398|SuSiE-inf        |799.4030991589394 |1.0         |1.0        |-6.0429371499688855|8.820064587990306 |6.6079173     |-9            |
|4               |6356608581566170109 |GCST90002322|15:42236528-43736528|[{15_43509840_A_C, 0.9999999876753237, 568.1898781506557, -0.10141569069174518}]                                                                                                                                                                     |15_43509840_A_C|15        |43509840|SuSiE-inf        |243.27219212815967|1.0         |1.0        |-6.140373470701867 |9.084454073301037 |1.2146581     |-10           |
|6               |-6022298121111655759|GCST90002322|15:42236528-43736528|[{15_43481838_C_G, 0.9235071832819135, 125.26041441851586, -0.04820931639149068}, {15_43485434_A_G, 0.06543832801869778, 122.61334398271471, 0.04783979343197251}, {15_43482120_T_G, 0.005377228304895126, 120.11440889703974, -0.04739672678247319}]|15_43481838_C_G|15        |43481838|SuSiE-inf        |50.94492987516624 |1.0         |1.0        |-6.797022181707687 |10.97141386859998 |9.362975      |-11           |
|7               |-6085008223147579656|GCST90002322|15:42236528-43736528|[{15_43658501_A_T, 0.9945646322980072, 123.89453033440324, -0.04651202114153519}]                                                                                                                                                                    |15_43658501_A_T|15        |43658501|SuSiE-inf        |50.31954122113802 |1.0         |1.0        |-10.207749251850686|23.737401987012895|5.4626327     |-24           |
|8               |-2273701730318034092|GCST90002322|15:42236528-43736528|[{15_43331199_T_G, 1.0, 107.82062562794736, -0.04542453628920864}]                                                                                                                                                                                   |15_43331199_T_G|15        |43331199|SuSiE-inf        |43.3363661157673  |1.0         |1.0        |-7.412101593625498 |12.905481830804181|8.044181      |-13           |
|10              |-5327263775886500084|GCST90002322|15:42236528-43736528|[{15_43297635_A_G, 0.9999993762056993, 24.29067688470837, -0.02245114123516229}]                                                                                                                                                                     |15_43297635_A_G|15        |43297635|SuSiE-inf        |7.059770574099266 |1.0         |1.0        |-5.653412648716343 |7.803290421657356 |6.357559      |-8            |
+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+------------------+--------------+--------------+

In [24]:
cred_sets2.count()

6

In [44]:
cred_sets=cred_sets2

In [45]:
window = Window.partitionBy("variantId").orderBy("credibleSetIndex")
cred_sets = cred_sets.withColumn("rank", row_number().over(window))
cred_sets = cred_sets.filter(cred_sets["rank"] == 1).drop("rank")
cred_sets = cred_sets.orderBy("credibleSetIndex")

In [46]:
cred_sets.count()

6

In [52]:
from pyspark.sql.functions import desc

cred_sets = cred_sets.orderBy(desc("neglogpval"))

In [53]:
lead_variantId_list = (
    cred_sets.select("variantId").toPandas()["variantId"].tolist()
)

In [54]:
lead_variantId_list

['15_43658501_A_T',
 '15_43331199_T_G',
 '15_43481838_C_G',
 '15_43509840_A_C',
 '15_43520398_G_C',
 '15_43297635_A_G']

In [55]:
cred_sets.show(truncate=False)

+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+------------------+--------------+--------------+
|credibleSetIndex|studyLocusId        |studyId     |region              |locus                                                                                                                                                                                                                                                |variantId      |chromosome|position|finemappingMethod|credibleSetlog10BF|purityMeanR2|purityMinR2|zScore             |neglogpval        |pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+------------------+--------------+--------------+
|7               |-6085008223147579656|GCST90002322|15:42236528-43736528|[{15_43658501_A_T, 0.9945646322980072, 123.89453033440324, -0.04651202114153519}]                                                                                                                                                                    |15_43658501_A_T|15        |43658501|SuSiE-inf        |50.31954122113802 |1.0         |1.0        |-10.207749251850686|23.737401987012895|5.4626327     |-24           |
|8               |-2273701730318034092|GCST90002322|15:42236528-43736528|[{15_43331199_T_G, 1.0, 107.82062562794736, -0.04542453628920864}]                                                                                                                                                                                   |15_43331199_T_G|15        |43331199|SuSiE-inf        |43.3363661157673  |1.0         |1.0        |-7.412101593625498 |12.905481830804181|8.044181      |-13           |
|6               |-6022298121111655759|GCST90002322|15:42236528-43736528|[{15_43481838_C_G, 0.9235071832819135, 125.26041441851586, -0.04820931639149068}, {15_43485434_A_G, 0.06543832801869778, 122.61334398271471, 0.04783979343197251}, {15_43482120_T_G, 0.005377228304895126, 120.11440889703974, -0.04739672678247319}]|15_43481838_C_G|15        |43481838|SuSiE-inf        |50.94492987516624 |1.0         |1.0        |-6.797022181707687 |10.97141386859998 |9.362975      |-11           |
|4               |6356608581566170109 |GCST90002322|15:42236528-43736528|[{15_43509840_A_C, 0.9999999876753237, 568.1898781506557, -0.10141569069174518}]                                                                                                                                                                     |15_43509840_A_C|15        |43509840|SuSiE-inf        |243.27219212815967|1.0         |1.0        |-6.140373470701867 |9.084454073301037 |1.2146581     |-10           |
|1               |923949982765216720  |GCST90002322|15:42236528-43736528|[{15_43520398_G_C, 1.0, 1848.7286144548993, -0.1821286026134763}]                                                                                                                                                                                    |15_43520398_G_C|15        |43520398|SuSiE-inf        |799.4030991589394 |1.0         |1.0        |-6.0429371499688855|8.820064587990306 |6.6079173     |-9            |
|10              |-5327263775886500084|GCST90002322|15:42236528-43736528|[{15_43297635_A_G, 0.9999993762056993, 24.29067688470837, -0.02245114123516229}]                                                                                                                                                                     |15_43297635_A_G|15        |43297635|SuSiE-inf        |7.059770574099266 |1.0         |1.0        |-5.653412648716343 |7.803290421657356 |6.357559      |-8            |
+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+------------------+--------------+--------------+

In [56]:
vlist_series = pd.Series(lead_variantId_list)

In [57]:
vlist_series

0    15_43658501_A_T
1    15_43331199_T_G
2    15_43481838_C_G
3    15_43509840_A_C
4    15_43520398_G_C
5    15_43297635_A_G
dtype: object

In [58]:
ind = vlist_series.map(
    variant_index_df.set_index("variantId").index.get_loc
)

In [59]:
ind

0    2982
1    2279
2    2659
3    2728
4    2741
5    2207
dtype: int64

In [60]:
ld_leads = ld_matrix[ind, :][:, ind]
ld_leads = ld_leads**2

In [61]:
ld_leads

array([[1.00000000e+00, 4.23977780e-01, 2.02906542e-01, 1.97427250e-01,
        2.12597673e-01, 3.40106831e-04],
       [4.23977780e-01, 1.00000000e+00, 1.03494589e-01, 9.93705632e-02,
        1.05278816e-01, 3.33426953e-05],
       [2.02906542e-01, 1.03494589e-01, 1.00000000e+00, 8.17014822e-01,
        7.67409092e-01, 7.45504130e-03],
       [1.97427250e-01, 9.93705632e-02, 8.17014822e-01, 1.00000000e+00,
        8.58464755e-01, 1.32570702e-02],
       [2.12597673e-01, 1.05278816e-01, 7.67409092e-01, 8.58464755e-01,
        1.00000000e+00, 1.72855712e-02],
       [3.40106831e-04, 3.33426953e-05, 7.45504130e-03, 1.32570702e-02,
        1.72855712e-02, 1.00000000e+00]])

In [62]:
ld_min_r2=0.8

In [63]:
ld_leads[ld_leads >= ld_min_r2] = 1
ld_leads[ld_leads < ld_min_r2] = 0
np.fill_diagonal(ld_leads, 0)

In [64]:
ld_leads

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [65]:
ld_leads = ld_leads - np.tril(ld_leads)

In [66]:
ld_leads

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [67]:
column_sums = ld_leads.sum(axis=0)

In [68]:
column_sums

array([0., 0., 0., 1., 1., 0.])

In [69]:
sum(column_sums) > 0

True

In [87]:
non_zero_mask = column_sums != 0

# Apply the mask to lead_variantId_list
lead_variantId_list_to_delete = list(np.array(lead_variantId_list)[non_zero_mask])

In [88]:
list(lead_variantId_list_to_delete)

['15_43509840_A_C', '15_43520398_G_C']

In [86]:
ld_leads

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [89]:
for vId in lead_variantId_list_to_delete:
    cred_sets = cred_sets.filter(f.col("variantId") != vId)

In [93]:
cred_sets.show(truncate=False)

+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+--------------+--------------+
|credibleSetIndex|studyLocusId        |studyId     |region              |locus                                                                                                                                                                                                                                                |variantId      |chromosome|position|finemappingMethod|credibleSetlog10BF|purityMeanR2|purityMinR2|zScore             |pValueMantissa|pValueExponent|
+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+--------------+--------------+
|7               |-6085008223147579656|GCST90002322|15:42236528-43736528|[{15_43658501_A_T, 0.9945646322980072, 123.89453033440324, -0.04651202114153519}]                                                                                                                                                                    |15_43658501_A_T|15        |43658501|SuSiE-inf        |50.31954122113802 |1.0         |1.0        |-10.207749251850686|5.4626327     |-24           |
|8               |-2273701730318034092|GCST90002322|15:42236528-43736528|[{15_43331199_T_G, 1.0, 107.82062562794736, -0.04542453628920864}]                                                                                                                                                                                   |15_43331199_T_G|15        |43331199|SuSiE-inf        |43.3363661157673  |1.0         |1.0        |-7.412101593625498 |8.044181      |-13           |
|6               |-6022298121111655759|GCST90002322|15:42236528-43736528|[{15_43481838_C_G, 0.9235071832819135, 125.26041441851586, -0.04820931639149068}, {15_43485434_A_G, 0.06543832801869778, 122.61334398271471, 0.04783979343197251}, {15_43482120_T_G, 0.005377228304895126, 120.11440889703974, -0.04739672678247319}]|15_43481838_C_G|15        |43481838|SuSiE-inf        |50.94492987516624 |1.0         |1.0        |-6.797022181707687 |9.362975      |-11           |
|10              |-5327263775886500084|GCST90002322|15:42236528-43736528|[{15_43297635_A_G, 0.9999993762056993, 24.29067688470837, -0.02245114123516229}]                                                                                                                                                                     |15_43297635_A_G|15        |43297635|SuSiE-inf        |7.059770574099266 |1.0         |1.0        |-5.653412648716343 |6.357559      |-8            |
+----------------+--------------------+------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------+--------+-----------------+------------------+------------+-----------+-------------------+--------------+--------------+

In [92]:
cred_sets = cred_sets.drop("neglogpval")

In [94]:
StudyLocus(
            _df=cred_sets,
            _schema=StudyLocus.get_schema(),
        )

StudyLocus(_df=DataFrame[credibleSetIndex: int, studyLocusId: bigint, studyId: string, region: string, locus: array<struct<variantId:string,posteriorProbability:double,logBF:double,beta:double>>, variantId: string, chromosome: string, position: int, finemappingMethod: string, credibleSetlog10BF: double, purityMeanR2: double, purityMinR2: double, zScore: double, pValueMantissa: float, pValueExponent: int], _schema=StructType([StructField('studyLocusId', LongType(), False), StructField('studyType', StringType(), True), StructField('variantId', StringType(), False), StructField('chromosome', StringType(), True), StructField('position', IntegerType(), True), StructField('region', StringType(), True), StructField('studyId', StringType(), False), StructField('beta', DoubleType(), True), StructField('zScore', DoubleType(), True), StructField('pValueMantissa', FloatType(), True), StructField('pValueExponent', IntegerType(), True), StructField('effectAlleleFrequencyFromSource', FloatType(), True), StructField('standardError', DoubleType(), True), StructField('subStudyDescription', StringType(), True), StructField('qualityControls', ArrayType(StringType(), False), True), StructField('finemappingMethod', StringType(), True), StructField('credibleSetIndex', IntegerType(), True), StructField('credibleSetlog10BF', DoubleType(), True), StructField('purityMeanR2', DoubleType(), True), StructField('purityMinR2', DoubleType(), True), StructField('locusStart', IntegerType(), True), StructField('locusEnd', IntegerType(), True), StructField('sampleSize', IntegerType(), True), StructField('ldSet', ArrayType(StructType([StructField('tagVariantId', StringType(), True), StructField('r2Overall', DoubleType(), True)]), True), True), StructField('locus', ArrayType(StructType([StructField('is95CredibleSet', BooleanType(), True), StructField('is99CredibleSet', BooleanType(), True), StructField('logBF', DoubleType(), True), StructField('posteriorProbability', DoubleType(), True), StructField('variantId', StringType(), True), StructField('pValueMantissa', FloatType(), True), StructField('pValueExponent', IntegerType(), True), StructField('beta', DoubleType(), True), StructField('standardError', DoubleType(), True), StructField('r2Overall', DoubleType(), True)]), True), True)]))